### ISSUE TITLE
관리자 대시보드에서 widget~~~어쩌구 문제점 발생.

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xpressengine#1]
![_111515_095329_am](https://cloud.githubusercontent.com/assets/4381756/11166598/ba8c3470-8b7e-11e5-98c7-1cd79e1ea3f3.jpg)
오른쪽 빨간색 박스처럼 뜨는구간이 있네요..

**Comment by findstar** [comment]
view 파일 위치의 대소문자가 맞지 않는 문제입니다. 
resources/views/widget/widgets/ContentInfo 디렉토리를
resources/views/widget/widgets/contentInfo  으로 변경해주면 해결됩니다.

**Comment by findstar** [comment]
수정이 완료되었습니다.

**Comment by findstar** [comment]
개발과정에서 git 이 대소문자 rename 을 tracking 하지 않아서 발생한 문제로 추정됩니다. 
추후 개발과정의 git 환경 설정을 변경할 이슈가 있습니다.

**Comment by findstar** [comment]
@khongchi 인스톨러에 포함예정.

**Comment by findstar** [comment]
개발환경이 맥일 경우 git config core.ignorecase false 설정해서 관리할것
