### ISSUE TITLE
관리자 페이지 (대시보드) 복합적인 오류들

### ISSUE THREAD

**Issue by closers-seulbi** [xpressengine/xpressengine#100]
제가 테스트 중인 XE3.0 - dev4 버그들입니다.

- 설정>사이트 기본 설정>파비콘 등록 오류

> 파비콘 등록시 **XE3.0 전체**가 먹통이 되는 현상이 있습니다.

- 설정>관리페이지 권한 설정 접근 오류
- 컨텐츠>게시물>휴지통 접근 오류
- 컨텐츠>댓글 및 하위 모듈 접근 오류

> 서버 제원
> Ubuntu Server 14.04.3 LTS i686
> WebServer : Apache/2.4.18 (Ubuntu)
> PHP Version : 7.0.4-5+deb.sury.org~trusty+1
> XE3.0 - dev4.0
> 권한 0755 www-data

**Comment by akasima** [comment]
컨텐츠>게시물>휴지통 접근 오류
컨텐츠>댓글 및 하위 모듈 접근 오류

위 두개 페이지에서 오류를 발견하지 못했습니다. dev4 배포 후 버그 수정하면서 처리되었을 수 있을것 같습니다.

**Comment by closers-seulbi** [comment]
코멘트 감사합니다!

권한을 XE 기본값인 0707 로 재설치 해 보겠습니다.

**Comment by closers-seulbi** [comment]
@akasima 
권한을 0707 으로, 사용자 및 그룹은 www-data:www-data 를 이용해 재설치 하였습니다.

**컨텐츠 > 게시물 > 휴지통**은 접근이 가능해 졌으나
**컨텐츠 > 댓글 및 하위 모듈**은 여전히 접근이 불가능 합니다.
