### ISSUE TITLE
인스톨러로 설치 불가

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#101]
관리자 비밀번호 입력후
```
[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1458091912--' for key 'documents_head_reply_unique'
```
예외가 발생합니다.

**Comment by akasima** [comment]
Document 에 오류가 있었습니다. 아래 커밋으로 해결했습니다.
https://github.com/xpressengine/xpressengine/commit/1b9ea7365061e5d99a425dc384f569fc08d0324f
