### ISSUE TITLE
회원 가입에서 캡챠 사용을 켜면 회원가입이 안되는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#1029]
https://www.xpressengine.io/qna/회원가입-활성화시-시스템에-오류가-있습니다-관리자에게-문의하세요

![스크린샷 2019-07-29 오후 4 54 09](https://user-images.githubusercontent.com/5836237/62031097-882fa700-b221-11e9-90ea-30c4ac02de73.png)

회원가입 설정에서 캡챠를 사용함으로 할 경우 회원가입이 되지 않습니다.
XE3에서 기본으로 구글 캡챠를 사용하도록 설정 되어 있는데요. `config/captcha.php`
회원가입에서 캡챠 사용을 설정 후 API 연동을 위한 값을 입력하지 않아 발생한 문제로 보여집니다.

#96 에서 다뤘던 문제로, 관련 설정을 추가하는 방법에 대해서 제공되야할 것 같습니다. 
캡챠 사용 메뉴얼이 없는 것도 문제인 것 같습니다.

**Comment by jhyeon1010** [comment]
#1033 과 같은 이슈
