### ISSUE TITLE
댓글 관리 문제

### ISSUE THREAD

**Issue by closers-seulbi** [xpressengine/xpressengine#103]
권한을 0707 으로, 사용자 및 그룹은 www-data:www-data 를 이용해 재설치 하였습니다.

**컨텐츠 > 게시물 > 휴지통**은 접근이 가능해 졌으나
**컨텐츠 > 댓글 및 하위 모듈**은 여전히 접근이 불가능 합니다.

해당 영상입니다.
[YouTube](https://www.youtube.com/watch?v=WrlDp-GoZb4)

**Comment by jhyeon1010** [comment]
정확한 에러 내용을 알기위해서 root 위치에 있는 `.env` 파일의
환경변수 `APP_DEBUG` 를  `true` 로 변경하신후 테스트 부탁드립니다.

**Comment by closers-seulbi** [comment]
@jhyeon1010 

.env 의 APP_DEBUG 를 True 로 한 후 발생하는 창을 .html 로 다운로드 후 txt 로 변환하였습니다.
[comment.txt](https://github.com/xpressengine/xpressengine/files/179569/comment.txt)

**Comment by jhyeon1010** [comment]
@closers-seulbi 
내용 확인 하였습니다.
해당 문제는 Presenter 의 인터페이스가 변경된 부분이 comment plugin 에서 반영되지 않아서 생긴 문제로 보입니다.
관련되어 수정된 코드는 이미 commit 되어 있으니 comment plugin 을 최신상태로 변경하시면 오류메시지 없이 
정상적인 페이지가 노출될것으로 보입니다.
installer 가 아닌 github 로 부터 clone 된 소스 코드로 설치하신경우 comment plugin 디렉토리에서 git pull 을 통해
master branch 의 코드로 업데이트가 가능하니 참고해주세요

**Comment by closers-seulbi** [comment]
답변 감사합니다 :)
github clone 을 이용했으니 git pull 로 업데이트 후 확인해 보겠습니다.
