### ISSUE TITLE
xe3 설치하고 php artisan route:list 했을 때 에러 메시지

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#104]
vagrant@homestead:~/Code/XE3$ php artisan route:list

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Xpressengine\Plugins\Board\UrlHandler::set
  Config() must be an instance of Xpressengine\Config\ConfigEntity, null give
  n, called in /home/vagrant/Code/XE3/plugins/board/src/Controllers/UserContr
  oller.php on line 122

**Comment by jhyeon1010** [comment]
board plugin 의 controller 생성자에서 route 를 이용하는 instanceConfig 를 사용하는 부분이 문제가 되었던것 같습니다. 해당 부분의 코드를 확인하고 수정방안을 찾아보도록 하겠습니다.
