### ISSUE TITLE
회원 > 설정 > 기본설정 저장시 오류가 발생됩니다.

### ISSUE THREAD

**Issue by geusgod** [xpressengine/xpressengine#1045]
3.0.5 버전이고 git, composer로 설치 했습니다.
최초 옵션은 captcha 사용안함, 회원가입허용 거절로 되어 있어서
허용으로 바꿔 볼려고 하니 오류가 발생되네요.

디버그 옵션을 켜보니 아래와 같은 오류가 나오네요.

`/var/www/xpressengine/app/Http/Controllers/User/Settings/SettingController.php
        return XePresenter::make(
            'user.settings.setting.common',
            compact('config', 'captcha', 'parts')
        );
    }
 
    /**
     * update user setting
     *
     * @param Request        $request request
     * @param CaptchaManager $captcha CaptchaManager instance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateSetting(Request $request, CaptchaManager $captcha)
    {
        $inputs = $request->except('_token');
        $config = app('xe.config')->get('user.common');
 
        if ($inputs['useCaptcha'] === 'true' && !$captcha->available()) {
            throw new ConfigurationNotExistsException();
        }
 
        $inputs['forms'] = array_keys(array_get($inputs, 'forms', []));
        $inputs['guard_forced'] = $inputs['guard_forced'] === 'true';
 
        foreach ($inputs as $key => $val) {
            $config->set($key, $val);
        }
        app('xe.config')->modify($config);
 
        return redirect()->back()->with('alert', ['type' => 'success', 'message' => xe_trans('xe::saved')]);
    }
 
    /**
     * get Common setting
     *
     * @param CaptchaManager $captcha CaptchaManager instance
     * @return \Xpressengine\Presenter\Presentable
     *
Arguments
"Undefined index: useCaptcha"`

**Comment by woongbin** [comment]
이슈를 제보해주셔서 감사합니다.
해당 이슈는 #1033 이슈에서 처리 되었습니다. 다음 배포에 반영될 예정입니다.
필요하시다면 이슈에서 수정된 내용과 같이 수정 하신다면 옵션 변경이 가능할 것으로 생각됩니다.
해결되지 않는다면 다시 댓글 남겨주시면 확인해보도록 하겠습니다.
감사합니다.

**Comment by geusgod** [comment]
적용하니 이제 잘 작동됩니다. 감사합니다.
