### ISSUE TITLE
테마 에디터에서 수정한 내용이 반영이 안됩니다.

### ISSUE THREAD

**Issue by geusgod** [xpressengine/xpressengine#1046]
버전 3.0.5 이며, XE3 가이드 보며 진행하고 있습니다.

플러그인 생성
$ php artisan make:plugin my_plugin GilDongHong
빈 테마 생성
$ php artisan make:theme my_plugin 'First Theme'

까지 진행후
설정 > 테마 > 테마 에디터 메뉴에서 새로 생성한 테마를 수정하면 반영이 안됩니다.
설치시 기본으로 생성된 Together 테마는 수정하면 반영이 잘 됩니다.

privates 폴더에 있어서 발생된 문제인지, cache 문제인지
정확한 원인을 파악하지는 못하였습니다.

**Comment by Kazto-lsk** [comment]
안녕하세요,
XE와 함께해주셔서 감사합니다.

테마 생성시에 문제가 있었던 것 같습니다.
First Theme 부분에 있는 ' 를 없애 아래 처럼 실행 부탁드립니다.

```
$ php artisan make:theme my_plugin First Theme
```

만약 이래도 동일한 문제가 발생하신다면 댓글 부탁드립니다.

**Comment by geusgod** [comment]
> 안녕하세요,
> XE와 함께해주셔서 감사합니다.
> 
> 테마 생성시에 문제가 있었던 것 같습니다.
> First Theme 부분에 있는 ' 를 없애 아래 처럼 실행 부탁드립니다.
> 
> ```
> $ php artisan make:theme my_plugin First Theme
> ```
> 
> 만약 이래도 동일한 문제가 발생하신다면 댓글 부탁드립니다.


동일한 문제가 발생하는것 같습니다.
홑따옴표 없이 띄어쓰니 오류가나서... 이미지처럼 SecondTheme 붙여서 생성했는데
"테마 에디터"에서 수정하면 반영이 안되네요.
ftp 접속하여 테마 파일을 직접 수정하면 반영이 잘 됩니다.

권한 문제인가 하고 chown chmod 처리하고 했으나,
이 문제는 아닌것 같습니다.

저는 급하게 처리해야할 문제는 아니고, 다른분들도 같은 문제인가 싶어서 이슈 등록했습니다^^

![image](https://user-images.githubusercontent.com/3859253/65419477-b0aada80-de39-11e9-8668-3bdb97a59e23.png)

**Comment by Kazto-lsk** [comment]
> > 안녕하세요,
> > XE와 함께해주셔서 감사합니다.
> > 테마 생성시에 문제가 있었던 것 같습니다.
> > First Theme 부분에 있는 ' 를 없애 아래 처럼 실행 부탁드립니다.
> > ```
> > $ php artisan make:theme my_plugin First Theme
> > ```
> > 
> > 
> > 만약 이래도 동일한 문제가 발생하신다면 댓글 부탁드립니다.
> 
> 동일한 문제가 발생하는것 같습니다.
> 홑따옴표 없이 띄어쓰니 오류가나서... 이미지처럼 SecondTheme 붙여서 생성했는데
> "테마 에디터"에서 수정하면 반영이 안되네요.
> ftp 접속하여 테마 파일을 직접 수정하면 반영이 잘 됩니다.
> 
> 권한 문제인가 하고 chown chmod 처리하고 했으나,
> 이 문제는 아닌것 같습니다.
> 
> 저는 급하게 처리해야할 문제는 아니고, 다른분들도 같은 문제인가 싶어서 이슈 등록했습니다^^
> 
> ![image](https://user-images.githubusercontent.com/3859253/65419477-b0aada80-de39-11e9-8668-3bdb97a59e23.png)

안녕하세요,
해당 문제를 확인하기 위해 SSH명령어를 통해 실행해보았는데요, Theme이름에 띄어쓰기가 있는 경우 정상적으로 반영되지 않는 문제가 있는 것 같습니다.

해당 이슈가 해결되기 이전에는

```
$ php artisan make:theme my_plugin First_Theme 
```

명령어를 통해서 테마를 행성해주시기 바라며, 
잘못 생성된 플러그인은

```
$ php artisan plugin:uninstall my_plugin
```

명령어로 삭제 후 재 생성 부탁드립니다 😃

**Comment by Kazto-lsk** [comment]
안녕하세요,
XE와 함께해주셔서 감사합니다.

해당 이슈에 대해서 추가 코멘트 작성해드립니다.

테마 생성시에 
```
$ php artisan make:theme my_plugin First Theme
```
로 명령어를 실행하는 경우 Excepted Arguments라는 에러와 함께 생성할 수 없게됩니다.
그 이유에는
[플러그인 생성 시작하기](https://www.xpressengine.io/guide/extension-make-guide/start-make-extension) 페이지를 확인해보시게 되면, 

```
$ php artisan make:plugin <플러그인명> <제작자명>
```
으로 처리됩니다. 따라서 입력한 플러그인은 플러그인명은 정상적으로 입력되었으나, 제작자 명에는 First만 사용되면서 Theme라는 항목이 오버되면서 플러그인이 제작되지 않는 문제가 있습니다.

하지만, 이번 케이스에서는 

테마생성시 
```
$ php artisan make:theme my_plugin 'First Theme'
```
명령어를 사용하였고 마지막 arguments가 '' 로 감싸져 있기 때문에,  하나의 argument로 보이고 있으나, 띄어쓰기가 문제였던 것으로 파악되었습니다.

따라서 테마 생성시에 아래의 명령어 처럼 실행을 부탁드립니다.

```
$ php artisan make:theme my_plugin 'First_Theme'
```

항상 행복한 하루 되시기 바라며, 익스텐션 개발 및 테마 제작에 궁금한 사항이 있으실 경우 XE QnA 게시판 또는 이슈를 통해 문의해주시면 감사하겠습니다.


감사합니다.

**Comment by geusgod** [comment]
상세한 설명 너무 감사드립니다~

정확한 이슈는 이렇게 생성된 별도 테마에서 "테마 에디터"를 이용해 수정한 부분이
웹사이트에 반영이 안되고 있습니다.
다른 분들은 잘 되시는지 궁금하구요~~~
저만 안되는거면 좀 더 다양한 환경에서 테스트 한 후에 피드백을 드려야 할듯 합니다.


![image](https://user-images.githubusercontent.com/3859253/66625057-92acea80-ec2d-11e9-82c5-051534ab7b5b.png)

**Comment by Kazto-lsk** [comment]
해당 방식으로 생성된 테마는 정상적으로 구동되지 않을 수 있습니다.
따라서 상단의 명령어로 생성한 테마로 진행하셔야 할 것으로 판단됩니다.
