### ISSUE TITLE
플러그인에서 익스텐션으로 명칭이 변경된 이유가 무엇인가요?

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1050]
제곧내입니다

**Comment by akasima** [comment]
플러그인은 프로그램이 배포되는 단위를 말합니다. 
플러그인은 여러개 컴포넌트 조합으로 이루어 집니다. 
플러그인을 구성하는 요소에 따라 특징을 나눌 수 있습니다. 
그 분류로 "테마", "익스텐션" 이 존재 합니다. 

플러그인을 익스텐션으로 변경한 것이 아니라 플러그인의 분류를 정의한 것으로 이해하시면 됩니다.


<img width="894" alt="스크린샷 2019-10-15 오후 12 31 07" src="https://user-images.githubusercontent.com/5836237/66798037-b16df280-ef47-11e9-8a5f-019a1e49a10d.png">

**Comment by darron1217** [comment]
상세한 설명 감사합니다^^
