### ISSUE TITLE
사이트맵 사용시 오류 발생

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#1055]
사이트 맵을 이동 및 Depth를 높이기 위하여 드래그 앤 드랍 하였으나 콘솔로그에 아래와 같은 에러로그가 출력됩니다.
```
Uncaught SyntaxError: Unexpected token u in JSON at position 0                                   VM408:1
    at JSON.parse (<anonymous>)
    at HTMLDocument.<anonymous> (common.js?1571727698:16)
    at HTMLDocument.dispatch (vendor.js?1571727698:1)
    at HTMLDocument.w.handle (vendor.js?1571727698:1)
    at Object.trigger (vendor.js?1571727698:1)
    at HTMLDivElement.<anonymous> (vendor.js?1571727698:1)
    at Function.each (vendor.js?1571727698:1)
    at t.fn.init.each (vendor.js?1571727698:1)
    at t.fn.init.trigger (vendor.js?1571727698:1)
    at Y (vendor.js?1571727698:1)
(anonymous) @ common.js?1571727698:16
dispatch @ vendor.js?1571727698:1
w.handle @ vendor.js?1571727698:1
trigger @ vendor.js?1571727698:1
(anonymous) @ vendor.js?1571727698:1
each @ vendor.js?1571727698:1
each @ vendor.js?1571727698:1
trigger @ vendor.js?1571727698:1
Y @ vendor.js?1571727698:1
(anonymous) @ vendor.js?1571727698:76
XMLHttpRequest.send (async)
send @ vendor.js?1571727698:76
ajax @ vendor.js?1571727698:1
value @ common.js?1571727698:16
(anonymous) @ SiteMap.js?1566887464:157
dispatch @ vendor.js?1571727698:1
w.handle @ vendor.js?1571727698:1


PUT http://아이디.cafe24.com/settings/menu/setHome net::ERR_TIMED_OUT              vendor.js?1571727698:76
```

캐시를 삭제 하더라도 동일한 문제가 발생하고 있습니다.

**Comment by WhiteGom** [comment]
2019-10-22일 발생한 문제이고, 이전에는 문제없었습니다.
관리자페이지의 사이트맵에서 특정 페이지를 움직이거나, 메인으로 등록할때 
무한로딩 및 콘솔 에러와 함께 home setting was failed! 라는 경고 문구가 아래 팝업됩니다.
최초 환경은 카페24 ( 10G 광아우토반 Full SSD 비즈니스 - php 7.3 ) XE 3.0.5 버전 입니다.
XE 3.0.7버전으로 업데이트 후 or php 7.0버전 에도 같습니다.

**Comment by Kazto-lsk** [comment]
@WhiteGom 안녕하세요,
해당 문제를 재현하기 위해서 아래의 두가지 방법을 사용해 보았습니다.

1. XE 3.0.7을 새로 설치
-> 해당 방법으로는 지금 이 이슈의 문제를 재현할 수 없었습니다. 😢 

2. XE 3.0.5 를 설치한 후, XE 3.0.7로 업데이트 (Changed 파일 업로드 -> Composer install)
-> 이 방법으로도 지금 이 이슈의 문제를 재현할 수 없었습니다. 😢 


조금 번거로우시겠지만, XE 3.0.5 에서 3.0.7로 업데이트 하셨을때의 방법이 어떻게 되었는지 알려주실 수 있으신가요? 
해당 문제를 찾을 수 있도록 조금의 도움을 부탁드리겠습니다 🙏

**Comment by WhiteGom** [comment]
문제 발생은 XE 3.0.5 에서 이미 발생했었고, 고쳐보고자 3.0.7로 업데이트 하였습니다.
업데이트 방식은 모두 zip 파일을 덮어씌운후 관리자페이지 업데이트 적용하는 방식으로 하였습니다.

**Comment by WhiteGom** [comment]
특이한점은 사이트맵에서 아이템 생성, 삭제는 정상작동 한다는 점입니다.
이동, 홈페이지 지정 이 2가지 에서 발생합니다.

**Comment by Kazto-lsk** [comment]
안녕하세요, @WhiteGom 님.
해당 문제를 확인하는데에 시간이 조금 걸렸습니다.

혹시 해당 XE3를 설치해주신 환경이 CAFE24의 웹 호스팅을 사용하시는 것이 맞으신가요?
별다른 설정을 제어할 수 없는 웹 호스팅인 경우 서버의 아파치 설정등에 의해서 HTTP PUT, DELETE 요청시 403 에러가 반환되는 것 같습니다.

안녕하세요, @WhiteGom 님.
해당 문제를 확인하는데에 시간이 조금 걸렸습니다.

혹시 해당 XE3를 설치해주신 환경이 CAFE24의 웹 호스팅을 사용하시는 것이 맞으신가요?
별다른 설정을 제어할 수 없는 웹 호스팅인 경우 서버의 아파치 설정등에 의해서 HTTP PUT, DELETE 요청시 403 에러가 반환되는 것 같습니다.

가능하시다면 해당 문제가 일어났던 사이트의 주소를 남겨주시면 감사하겠습니다.

**Comment by Kazto-lsk** [comment]
호스팅을 사용하는 호스팅사에 테스트 계정을 만들어 확인했을때에 2개의 계정 모두 정상적으로 해당 기능이 동작한 것으로 확인되었습니다.
테스트 결과 http에서는 PUT이 동작하지 않고, https 일때 PUT과 관련된 메소드가 동작하는 것으로 확인되었는데요.

https일때 정상적으로 해당 기능이 동작하는지 확인 가능하실까요?

**Comment by WhiteGom** [comment]
현재 사이트에서 https 확인은 개발 완료후 약 3주 뒤에 알수있고, 다른 개발 완료된 https 사이트 2개는 정상 작동하는것 확인하였습니다.
