### ISSUE TITLE
익스텐션 및 테마 설치시 search filter가 작동하지 않음

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#1064]
`익스텐션 > 익스텐션 추가` 페이지에서 익스텐션 명의 일부를 입력하거나 전부를 입력해서 search 필터가 작동하지 않습니다.

![image](https://user-images.githubusercontent.com/47233861/67923566-952daf00-fbf1-11e9-8d0a-21be65ff6aa5.png)

위 사진 처럼 target이 없이 들어가고, target을 넣어줘도 정상적으로 출력되지 않습니다.

**Comment by akasima** [comment]
`3.0.12` 버전 에서 정상 동작됩니다.
