### ISSUE TITLE
개발자 모드(디버깅)에서 플러그인을 강제 비활성 기능 제외

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#1065]
`APP_DEBUG=true`일 때 플러그인의 오류 발생 시 플러그인을 자동 비활성화하는 기능이 동작하지 않도록 분리 처리 필요.

**Comment by akasima** [comment]
플러그인 강제 비활성화 기능은 core가 불안정하던 시기에 발생하는 문제를 해결하기 위함 이었으나,
현재는 플러그인 오류로 인해 코어 전체에 미치는 영향이 크지 않다고 판단되어 강제 비활성화 기능을 제거하기로 결정
