### ISSUE TITLE
미디어 라이브러리. 자신이 업로드한 파일만 반환하는 API 추가

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#1072]
- user ID로 필터링하여 해당 user가 업로드한 파일만 목록으로 반환
- 폴더 목록 및 폴더 구조에 따른 경로를 반환할 필요 없음
- 요청
  - `GET /media_library`과 동일하나, User ID(String. UUID) 추가
- 반환
  - `GET /media_library`에서 `file` 섹션만 반환. path, folder 제외

**Comment by woongbin** [comment]
미디어라이브러리 파일 목록 기준이 변경되면서 필요 없어짐
