### ISSUE TITLE
XE가 이미 설치 되어 있을때 경고 문구 발생

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#1078]
XE가 이미 설치되어 동일한 prefix가 겹치는 경우 에러메시지 또는 경고메시지를 통해 이미 설치되어 있음을 안내하는 것이 좋을거 같아요.

그 이후 헬프센터 또는 QnA 게시글로 이동하여 설정하는 방법을 안내하는 것이 좋을 것 같습니다.

**Comment by bnu** [comment]
중복 #1047
