### ISSUE TITLE
게시판 생성시 중복된 이름으로 생성시 발생하는 오류.

### ISSUE THREAD

**Issue by haegyung** [xpressengine/xpressengine#1081]
게시판 생성에서
url이 blog 라는 게시판이 존재하는데 다시 blog 로 생성시
1. 정상적으로 생성됨.
2. 기존에 생성된 게시판과, 이후에 생긴 게시판 모두 접속이 안됨.
3. 이후, 기존에 생성되어 있던 게시판과, 이후에 생긴 게시판 모두 삭제도 안됩니다.
이런 문제가 있습니다.

**Comment by jhyeon1010** [comment]
메뉴생성시 같은 url 이름을 가질 수 없도록 중복 검사를 추가하였습니다.
