### ISSUE TITLE
익스텐션 업로드가 동작하지 않음

### ISSUE THREAD

**Issue by limslee** [xpressengine/xpressengine#1089]
설정 > 설치된 익스텐션 에서 익스텐션 업로드를 누르고 파일을 업로드해도
익스텐션 업로드가 동작하지 않습니다.

**Comment by akasima** [comment]
시간이 오래 지난 건이어서, 
현재 업로드 오류 건은 없을 걸로 생각됩니다. 

관련해서 문제가 있다면 3.0.13 배포 후 점검 하겠습니다.
