### ISSUE TITLE
루트가 아닌 디렉토리에 설치시에 스크립트를 불러 오지 못하는 문제가 발생합니다.

### ISSUE THREAD

**Issue by hhgyu** [xpressengine/xpressengine#109]
컴포져로 설치시에

site url [http://localhost]:
되어 있어서

서브디렉토리까지 작성 했으나 스크립트 단에서 오류가 발생하여서

db 테이블과 app.php 에서 변경 후 사이트가 열리기는 하는데 일부 파일이 경로 문제로 사이트가 제대로 동작을 안합니다.

혹시 서브디렉토리에서는 정상적으로 동작이 안되는 건가요.

설명서에는 그런 문구가 없어서....

eot 파일은 실제로 없는 파일 인거 같습니다.

![1](https://cloud.githubusercontent.com/assets/4644504/14064641/27661ae6-f445-11e5-9e99-35cb32fa8f69.PNG)

**Comment by khongchi** [comment]
서브디렉토리 환경을 많이 고려하지 않아서 발생한 문제인것 같습니다.
위 목록에서 대부분의 파일로딩 오류는 바로잡은 것으로 생각됩니다.

감사합니다.
