### ISSUE TITLE
플러그인의 composer.json파일에 외부 패키지 의존성 추가하는 방법

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1091]
플러그인에 composer.json에 의존성을 추가하였는데 플러그인을 설치해도, 활성화해도 composer가 자동으로 의존된 패키지들을 가져오지는 않는것 같습니다.
플러그인별로 패키지 의존성을 설정해주고 싶은데 현재 플러그인 방식에서는 안되는 기능인지 궁금합니다.

예를들면 아래와 같이 require 필드를 설정하고 싶습니다.
```
  "require": {
    "xpressengine/xpressengine": "~3.0.8",
    "nanigans/single-table-inheritance": "0.8.*"
  },
```

**Comment by jhyeon1010** [comment]
composer 에 옵션으로 `minimum-stability` 라는 항목이 있습니다.
이 항목은 설치될 패키지의 최소안정성 조건을 지정하는것인데, 별도 지정되지 않은 경우 `stable` 이 기본값으로 지정됩니다. 이 값은 정식버전으로 배포된 것을 의미하는데 `0` 으로 시작하는 버전은 composer 에서 `dev` 로 취급하도록 되어 있습니다. 
따라서 `0`, `dev-master` 등의 개발 버전의 패키지를 사용하시는 경우 `minimum-stability` 값을 `dev`  로 지정하여야 합니다.
참고하셔야 할 사항은 이 옵션이 루트 패키지, 즉 XE3 의 루트에 있는 composer.json 에 명시되어야 옵션이 적용된다는 점입니다. 그러므로 설치하시기 전 XE3 루트에 있는 composer.json 파일에 해당 옵션을 작성하신 후 설치하시면 정상동작할 것으로 보입니다.
작성 위치는 `name` 이나 `require` 와 같이 최상위에 작성되어야 합니다.
```
{
    "name": "xpressengine/xpressengine",
    ...
    "require": {
        ...
    }
    ...
    "minimum-stability": "dev"
}
```

**Comment by akasima** [comment]
@jhyeon1010 해결된 문제인가요? 확인 부탁드립니다.

**Comment by darron1217** [comment]
따로 설정하지 않아도 다시 잘 됩니다.
제가 설치할때 어떤 과정을 빼먹었었나봐요. 해결된 사항입니다 :)
