### ISSUE TITLE
PHP 7.4에서 설치가 되지 않거나 동작하지 않음

### ISSUE THREAD

**Issue by woongbin** [xpressengine/xpressengine#1097]
PHP 7.4에서 설치가 되지 않거나 동작하지 않음

**Comment by superior0528** [comment]
그러면 latest version 을 설치하면, 해결된건가요? 4일전쯤에 7.4환경에서 했는데 안되서요, 이 내용은 16일전에 해결된거 같은데 말이죠...

**Comment by woongbin** [comment]
@superior0528 
이 이슈에 있는 내용은 아직 배포되지 않은 작업 내용입니다.
다음 배포에 반영될 예정입니다.
PHP 7.4에 XE3를 설치하시려면 develop branch에서 설치를 하시거나 위 내용처럼 소스 수정이 필요합니다.

**Comment by woongbin** [comment]
https://github.com/xpressengine/xpressengine/commit/4a6aac97e5651e0fe87f3a6ebe1f7dde1061e59f
