### ISSUE TITLE
플러그인 이름 길이에 제한이 있습니까?

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#110]
플러그인 개발중에 발생한 에러입니다.

https://www.youtube.com/watch?v=F40bTQExNPc&feature=youtu.be

'preg_match(): Compilation failed: subpattern name is too long (maximum 32 characters) 에러가 발생합니다.

plugin.php, composer.json 에서
module/imageUploader@imageUploader 이런 이름을  
module/iUploader@iUploader 짧게 이런식으로 수정하면
위의 에러는 발생하지 않습니다.

**Comment by khongchi** [comment]
`Route::instance()`를 통해 라우트를 등록하는 과정에서 모듈아이디가 사용됩니다.
그런데 모듈아이디가 너무 길면 preg_match() 함수의 제약사항으로 인해 오류가 발생하는군요. 

조치를 취하겠습니다. 감사합니다.
