### ISSUE TITLE
미디어 라이브러리 업로드 영역 UI 오류

### ISSUE THREAD

**Issue by cert1970** [xpressengine/xpressengine#1100]
미디어 라이브러리를 사용할 때 관리자 계정에서는 UI가 정상적으로 표시되지만, 일반 계정에서는 UI가 깨지는 현상이 있습니다.

`#media-manager-modal-container`에서 로그인된 계정 권한에 따라 `.media-library-layer-popup--sidebar` CSS 클래스가 달라짐으로 인해 미디어 박스의 `.media-library-layer-popup--sidebar .media-library-upload`, `.media-library-layer-popup--sidebar .media-library-content` 등의 CSS 규칙이 영향을 받습니다.

![2020-01-24+test1 - XE3 - Firefox Developer Edition](https://user-images.githubusercontent.com/24864600/73068673-23fb5080-3eef-11ea-8551-500e09bb2e5e.png)
![2020-01-24+test2 - XE3 - Google Chrome](https://user-images.githubusercontent.com/24864600/73068686-2b225e80-3eef-11ea-982e-bbcad69ce35a.png)

**Comment by bnu** [comment]
https://github.com/xpressengine/xpressengine/pull/1101 PR로 해결 예정
