### ISSUE TITLE
게시판에 이모지 등록시 ????로 나타나는 문제

### ISSUE THREAD

**Issue by pers0n4** [xpressengine/xpressengine#1102]
![2020-01-24+Selection](https://user-images.githubusercontent.com/24864600/73072252-13030d00-3ef8-11ea-9f25-b8e5f6ee4962.png)
![2020-01-24+Selection(001)](https://user-images.githubusercontent.com/24864600/73072258-15fdfd80-3ef8-11ea-9ce4-2cb62ecac2fc.png)

Laravel 5.4 버전부터 기본 charset이 `utf8mb4`로 바뀐 걸로 알고 있는데, xpressengine에서는 아직 `utf8`을 기본으로 하고 있어서 이모지 등의 특수문자가 제대로 저장되지 않습니다.
혹시 charset을 `utf8mb4`로 바꿀 예정은 없으신가요?

**Comment by smaker** [comment]
#977 `utf8mb4` 로 변경했을 때 인덱스가 생성되지 않는 이슈가 있어 `utf8` 로 다시 바꾼 것으로 알고 있습니다.

**Comment by cert1970** [comment]
아하, 그렇군요. 가이드에 utf8mb4로 설치하는 방법이 나와있었다면 미리 바꿔서 설치했을 텐데, 일단 설치한 상황에서 마이그레이트하는 방법을 찾아봐야겠네요.

**Comment by akasima** [comment]
#1140 에서 해결 되었습니다.
