### ISSUE TITLE
회원 설정 어디갔죠?

### ISSUE THREAD

**Issue by parangee** [xpressengine/xpressengine#1121]
XE 가이드에서는 회원 -> 설정 들어가라고 하는데 저는 그게 없는데...

**Comment by woongbin** [comment]
회원 가입에 대한 설정은 3.0.8버전부터 관리자메뉴->설정->가입 설정 메뉴로 이동되었습니다.
매뉴얼 수정하도록 하겠습니다.
감사합니다.
