### ISSUE TITLE
COMPOSER_HOME 경로에 대한 기본값을 지정하면 안될까요?

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1124]
매번 XE3를 설치하고 나서 composer를 사용하려고 하면 아래와 같은 오류를 마주하게 됩니다.
```
 Checking COMPOSER_HOME environment variable: 

In ComposerRunTrait.php line 111:
                                                                                                                                       
  COMPOSER_HOME environment variable must be set for composer to run correctly. set the variable to http://localhost/settings/setting                                                                                                                                         
```

관리자페이지에 가서 설정을 해주면 해결이 되긴 하지만, 비전문가들이 보기엔 복잡해 보일것 같습니다.
![image](https://user-images.githubusercontent.com/8064923/77249159-7ef8bc00-6c82-11ea-8e49-82e413b5b295.png)

저 같은 경우는 보통 사이트 최상위폴더에 `.composer` 폴더를 만들어서 사용합니다. 보통의 경우 그렇게 사용할것 같은데 이를 기본값으로(상대경로로) 넣어주면 어떨까 하는 생각을 해봤습니다. (COMPOSER_HOME 변수가 지정되어있지 않은경우)

다른분들은 어떻게 생각하시는지 궁금합니다.

**Comment by darron1217** [comment]
그리고 위와같이 기본값을 넣어주면 .gitignore에 .composer를 추가해주어야 할것 같네요

**Comment by akasima** [comment]
site_manager 플러그인에서 이 문제를 해결해 보려고 시도 했습니다.
https://store.xehub.io/plugins/site_manager

.composer 경로를 쓰기 권한이 있는 디렉토리로 맞추면 될 거라고 생각했습니다.
해당 플러그인에서는 storage/framework/ 를 composer home 으로 사용하도록 했습니다.

댓글 쓰면서 생각하는건데.. storage/framework/.composer 로 하는게 더 좋겠네요.

코어에서는 .composer 디렉토리를 사용하지 않도록 composer 에서 cache를 사용하지 않는 방법을 고민중입니다.
업데이트가 느려지겠지만 composer에 다루는 cache 파일이 디스크를 많이 차지해서 발생하는 문제도 해결해야 해서 고민하고 있습니다.

**Comment by darron1217** [comment]
@akasima 
storage/framework/.composer을 기본값으로 하는건 좋은 의견인것 같습니다.
cache파일이 디스크를 많이 차지한다면, site_manager 플러그인에서 캐시 비우기와 같은 기능을 제공하는건 어떨까요?
특정 용량이상 차지하면 대시보드에 알림이 뜨게해서 사용자가 선택적으로 비우는거죠

**Comment by akasima** [comment]
cache 를 선택적으로 사용하도록 옵션을 추가하는 것도 생각해 봤습니다. 
최근에 닷홈에서 오류 신고가 많이 있었는데.. 확인해보니까.. 닷홈 무료 상품 사용해서 composer 로 땡겨온 캐시파일이 1GB 가 넘어가면서 디스크 full 나서 문제가 되더라구요..
정말 생각도 못해본 사이드이팩트라..

site_manager 통해서 운영에 필요한 팁이나 개선안을 빠르게 대응해 나갈 생각입니다.(코어 배포는 너무 무거운 작업이라서..)
아이디어 주신 거 추진해 볼게요.

**Comment by akasima** [comment]
#1150 에서 해결 되었습니다.
