### ISSUE TITLE
[건의] 사이트 관리 > 공통 요소 선택지 추가

### ISSUE THREAD

**Issue by cansmile** [xpressengine/xpressengine#1130]
같은 외부 페이지를 참조하는 메뉴를 여러 개 만들려고보니 이미 있는 주소라며 안 되더라고요.
![2020040300008](https://user-images.githubusercontent.com/459021/78375805-4e147180-7608-11ea-9009-e824500d35af.png)
왜 이런 삽질을 하냐 싶으시겠지만, 원래 탐색바를 버리고 xe메뉴로 접근 통제를 하려고 하다보니 이런 변태(?)적인 메뉴를 구성할 수 밖에 없더라고요.

메뉴 추가는 같은 이름으로 가능한데, 외부 페이지 주소는 사용할 수가 없어요. 
결국 안되서 각기 다른 이름을 넣어서 만들고 데이터베이스에서 검색하고 변경했습니다.

뭐 저 같은 사람이 얼마나 되겠습니까만 선택지는 많으면 좋으니까요.
그리고 메뉴는 정렬이 안 되는건가요?

그러니 간단하게 정리하면 

1. 외부 페이지와 같은 항목은 같은 주소를 사용할 수 있게 하면 어떨까요?
2. 메뉴는 정렬이 안 되나요?

정도가 되겠네요. 쩝.

**Comment by akasima** [comment]
1. 외부 페이지와 같은 항목은 같은 주소를 사용할 수 있게 하면 어떨까요?
외부페이지가 directLink 인가요?
배포 준비하고 있는 3.0.10에서 direct link 는 중복 사용할 수 있게 개선한다고 합니다. 
외부 페이지(external_page)는 대상에 있지 않습니다. 

권한설정을 어떻게 설계 하셨나요?

2. 메뉴는 정렬이 안 되나요?
메뉴 정렬은 저도 많이 아쉬워하는 부부인데.. 
우선 order 기능을 database 에 넣어 보겠습니다.
메뉴에서 ui, ux 로 풀어 내는거는 그 다음 과제일 것 같습니다.

**Comment by akasima** [comment]
배포전에  컬럼 추가를 하려면 tinker 에서 아래 코드를 실행하세요.
`(new Xpressengine\Migrations\MenuMigration())->update();`

**Comment by cansmile** [comment]
> 1. 외부 페이지와 같은 항목은 같은 주소를 사용할 수 있게 하면 어떨까요?
>    외부페이지가 directLink 인가요?
>    배포 준비하고 있는 3.0.10에서 direct link 는 중복 사용할 수 있게 개선한다고 합니다.
>    외부 페이지(external_page)는 대상에 있지 않습니다.
> 
> 권한설정을 어떻게 설계 하셨나요?
메뉴 자체 노출과 접근은 일부(0, 1, 6과)는 비회원 공개이고, 나머지는 회원만 공개입니다.
그리고 메뉴 안에 있는 반복 요소들은 상위 권한으로 설정되어 있고요.

> 
> 1. 메뉴는 정렬이 안 되나요?
>    메뉴 정렬은 저도 많이 아쉬워하는 부부인데..
>    우선 order 기능을 database 에 넣어 보겠습니다.
>    메뉴에서 ui, ux 로 풀어 내는거는 그 다음 과제일 것 같습니다.

**Comment by cansmile** [comment]
> 배포전에 컬럼 추가를 하려면 tinker 에서 아래 코드를 실행하세요.
> `(new Xpressengine\Migrations\MenuMigration())->update();`

네 감사합니다. :)

**Comment by akasima** [comment]
null 이 나오는게 맞습니다. 
업데이트하면서 처리는되는거는 다시 확인해볼겠습니다.
