### ISSUE TITLE
위젯박스 편집 영역에 위젯 형식 설명 추가

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#1131]
<img width="938" alt="스크린샷 2020-04-05 오전 11 07 51" src="https://user-images.githubusercontent.com/5836237/78465225-b3ae4e00-772d-11ea-8727-fbe0388b570d.png">

위젯박스에 설정한 위젯 제목만 나오고 있는데.. 어떤 위젯인지 부가 설명이 없어 관리에 어려움이 있음
위젯, 위젯 스킨에 대한 설명을 추가하여 관리에 참고할 수 있도록 기능 개선

**Comment by akasima** [comment]
위젯 이름, 스킨 이름 표시되록 개선 했습니다.
이름 요소에 따라 구분되어 보여질 수 있도록 마크업 구조를 재정의하고 css 에 따른 아이콘 표시등 개선이 필요합니다.

<img width="941" alt="스크린샷 2020-04-05 오후 8 34 55" src="https://user-images.githubusercontent.com/5836237/78473644-3f030000-777d-11ea-92b7-4cbdc176001e.png">

**Comment by junnaa** [comment]
위젯명, 스킨명 외에 위젯이 어떤 위젯인지도 보여줬으면 합니다.
배너 위젯, 게시판 최신글 위젯인지.. 알 수가 없습니다.

해당 마크업 구조 및 스타일의 개선 처리 안은 별도로 올리도록 할게요.
