### ISSUE TITLE
스킨 설정에서 파일 업로드가 처리되지않는 문제

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#1134]
스킨 설정(게시판, 페이지 등의 스킨)에서 이미지 업로드 사용 시 _configId가 없어 파일 업로드를 처리하지 못하는 문제 있음.

config key 예시: skins.configs.module/page@page:cc337daf

참조: https://github.com/xpressengine/xpressengine/blob/master/core/src/Xpressengine/Skin/GenericSkin.php#L152-L210

테마 설정과 동일한 방식으로 처리하여 해결 될 것으로 보임.

**Comment by jhyeon1010** [comment]
문제의 원인은 이전 설정값이 없어서 인것으로 보입니다

**Comment by bnu** [comment]
@jhyeon1010 이미지 업로드 완료 후 설정을 다시 저장 시 기존에 등록된 파일이 삭제되는 문제가 있습니다.

<img width="192" alt="스크린샷 2020-04-08 오후 7 37 36" src="https://user-images.githubusercontent.com/53764/78774951-6ac9f400-79d0-11ea-93dc-740a6f7594b0.png">

`<input type="checkbox" class="__xe_delete_file_1" value="__delete_file__" name="type_a1">`
위와 같이 삭제 체크한 항목은 type_a1=__delete_file__ 전달될 항목만 삭제처리해야 합니다.

**Comment by bnu** [comment]
@jhyeon1010 가이드 하신대로 e99b752 커밋했습니다.
