### ISSUE TITLE
3.1.10 - 최초 설치 후 artisan 이용 시 COMPOSER_HOME 설정 요구

### ISSUE THREAD

**Issue by cansmile** [xpressengine/xpressengine#1138]
윈도우 Valet 환경에서 3.1.10을 땡겨서 설치했는데, 익스텐션 설치하면서 오류가 나는데, 로그에는 아무것도 안 나타나기에 artisan으로 시도했더니 COMPOSER_HOME을 설정하라는 메시지가 나오더라고요.

직전에 SiteManager를 설치하고 활성화할 때는 문제가 없었는데, 이미지 오리엔테이터를 설치하고 난 뒤에 시도했는데도 저렇습니다.

처음 artisan 명령 쓰기 전에 원래 별도로 설정을 한 번 더 저장해 줘야 하는 건가요?

**Comment by akasima** [comment]
composer 관련 환경 설정을 더 확인해보겠습니다. 
최근에 COMPOSER_HOME 을 사용하지 않는 방향으로 얘기중입니다.
composer 가 서버 리소스를 많이 사용하다보니까, 웹호스팅에 솔루션 레벨로 사용하는데 어려움이 많네요 ;

**Comment by akasima** [comment]
https://github.com/xpressengine/xpressengine/issues/1124 여기에서 이슈와 같이 처리하겠습니다.
설치할 때 composer_home 을 지정하도록 개선할 계획입니다.

업데이트 하면서 관련 설정이 없는 경우 설정을 입력하도록 개선할 계획입니다.
