### ISSUE TITLE
install guide 따라하기 에러

### ISSUE THREAD

**Issue by gractor** [xpressengine/xpressengine#114]
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)

출력 메세지
  [PDOException]                                 
  SQLSTATE[42000] [1049] Unknown database 'xe3'

**Comment by YJSoft** [comment]
@gractor DB 생성은 직접 해주셔야 합니다.
mysql에 접속하셔서 xe3 데이터베이스를 생성해주세요.

**Comment by khongchi** [comment]
DB 생성후 다시 테스트 해보시기 바랍니다.
