### ISSUE TITLE
플러그인 lang.php 일부 수정했을 경우 적용하는 방법은?

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#115]
plugin.php 파일의 install() 함수에서
$this->putLang(); 을 실행해야하는데

일단은
boot() 함수에 넣어서 수정할 때마다 언어팩을 적용하고 있습니다.

composer 로 플러그인이 재설치 되도록 해야하는 것이 옳은 방법인가요?

**Comment by khongchi** [comment]
언어추가가 빈번하다면 boot()메소드에 넣어서 개발하시는 것도 좋은 방법입니다.

언어추가가 빈번하지 않다면 `php artisan trans` 커맨드를 사용하셔도 됩니다.

`php artisan trans --help`로 사용법을 보실수 있습니다.

**Comment by 1Sam** [comment]
PDO 클래스를 찾을 수 없다고 합니다.
서버 설정에 문제가 있는 건가요?

kmdb@kmdb.luatic.co.kr [~/public_html/xe3]# php artisan trans -help

Fatal error: Class 'PDO' not found in /home2/kmdb/public_html/xe3/config/database.php on line 16
