### ISSUE TITLE
약관 표시할 때 nl2br 제거

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#1153]
/auth/register

약관 표시할 때 html 사용을 기본으로하며 nl2br 은 처리 안하는 것으로 정책 변경

**Comment by smaker** [comment]
html을 사용할 수 있다면 textarea 대신에 에디터를 보여주는 게 어떨까요?

**Comment by akasima** [comment]
그게 더 좋을까요?
최근에 홈페이지 만들면서 디테일 한 요청이 와서 html 을 사용안하면 어렵겠다고 생각이 들었던건데..

우선 접수 하고 develop 에 넣어 볼게요.

**Comment by smaker** [comment]
설명이 없어서 html을 사용할 수 있는지 인지하기가 어렵네요. textarea를 CK에디터로 교체했으면 좋겠습니다.

**Comment by akasima** [comment]
에디터 교체는 하지 않기로 결정했습니다. 
다국어 처리에 부담이 있었습니다. 

html 사용이 가능한  요소에 대한 설명을 추가하여 안내하는 것으로 하겠습니다.
