### ISSUE TITLE
라라벨 Auth 기본 이벤트 일부 발생 안됨

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1154]
https://laravel.kr/docs/5.5/authentication#%EC%9D%B4%EB%B2%A4%ED%8A%B8

XE3 인증모듈에서 라라벨의 기본 Auth Event 들이 발생되지 않고 있다는걸 오늘 알았습니다.

호환성을 위해 구현이 필요할것 같습니다.

### 미작동 확인된 이벤트
```
Illuminate\Auth\Events\PasswordReset
Illuminate\Auth\Events\Registered
```

**Comment by darron1217** [comment]
다 안되는건 아닌것 같고 제가 테스트한건 Illuminate\Auth\Events\PasswordReset 이벤트입니다.

로그인, 로그아웃 외에 일부가 안되는것 같습니다.

**Comment by darron1217** [comment]
`Illuminate\Auth\Events\Registered` 이벤트도 발생 안됩니다

회원가입시 이벤트 발생 안되는건 심각한것 같네요...

**Comment by darron1217** [comment]
https://github.com/xpressengine/xpressengine/blob/5d09e1a1eace9f3f4006c2e49765c72ff9d3c445/core/src/Xpressengine/User/Repositories/UserRepository.php#L47-L48

그냥 요 사이에
```
event(new Registered($user));
```
이렇게만 넣어줘도 작동하는데, 조치가 상당히 길어지네요...

**Comment by akasima** [comment]
UserHandler 에 이벤츠 추가 했습니다. 
UserRepository 는 데이터 처리를 담당하는 역할이이서 event를 추가하기에 적당하지 않다고 판다했습니다.

UserRepository 를 직접 사용할 경우 이벤트가 발생하지 않습니다. 
Handler 를 통해서 사용하는 경우에만 동작 합니다.

이외 Laravel Auth 에 있는 Event 지원은 다음 버전 배포 때 검토하겠습니다. (#1254)
