### ISSUE TITLE
User 모델에서 $visible 에 email이 빠져있습니다

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1156]
보안상의 문제라고 생각하자니 fillable에는 email필드가 있습니다.

개발하면서 누락된건지, 아무튼 email이 추가되었으면 합니다.

**Comment by akasima** [comment]
개인정보로 판단해서 뺐던것 같습니다. 
visible 에 있으면, json 으로 출력할 때 포함되는 걸로 기억합니다. 

개발할 때 아무생각없이 출력하더라도 민감 데이터는 제외시키는 정책을 가져갔으면 해서 그렇게 구성했던 것 같아요.
개인정보는 조합으로 유출될 때 문제가 되는 거니까요.

다음 배포까지 시간이 있으니까, use-case 를 나열하면서 결정하면 좋겠네요.
use-case 가 특별한게 없다면 현재상태 유지

**Comment by darron1217** [comment]
API를 구성하면서 로그인된 사용자 정보를 불러오는데 email 필드가 출력되지 않아서 의문이었습니다.

저의 use-case는 로그인된 사용자의 email값을 불러와 input 이메일을 자동입력해주어야 하는 경우에 필요했습니다.

**Comment by darron1217** [comment]
XE3에서 view()로 구성하는 경우에는 `->email` 이렇게 접근할 수 있지만, API 환경에서는 데이터가 안넘어오면 할수있는게 아무것도 없습니다...ㅜ

**Comment by akasima** [comment]
플러그인에서 각 모델에 visible 구성을 하는 방법을 검토하고 있습니다.

코어에서 제공하는 기본 api 에서 이메일(개인정보)을 제공하는 것에 대한 부분은 부담이 많이 있네요.

**Comment by akasima** [comment]
기존 모델에서 수정하는 것 외에 본격적으로 API 지원을 위한 기능 추가를 검토하는 것으로 결정했습니다.

API 환경에서 이슈는 별도 플러그인에서 다루겠습니다.
