### ISSUE TITLE
쓰기 권한이 없다고 나옵니다.

### ISSUE THREAD

**Issue by cansmile** [xpressengine/xpressengine#1160]
![2020061300008](https://user-images.githubusercontent.com/459021/84561535-2e2bc780-ad88-11ea-8fc9-e8d54fb1d60e.png)
위에서 보시는 경로를 웹서버 기본 소유자(www-data), 기본 그룹(www-data)로 해 놓고 디렉토리 권한을 0777로 주었는데, 쓰기 권한이 없다는 안내문이 나와요.
물론 웹으로나 php artisan으로나 설치, 제거, 업데이트 다 잘 됩니다.
사이트 관리자에서만 저렇게 나오고 실제 동작에는 영향이 없네요.

**Comment by akasima** [comment]
composer에  쓰기 처리는 '플러그인 설치', '플러그인 업데이트' 등 특정 행위가 있을 때 동작됩니다.
웹사이트 운영에는 문제를 일으키지 않을 겁니다.

이 경우는 ssh 와 웹서버 에서 사용하는 user 가 다를 때 발생할 수 있습니다.

문제가 발생하는 이유는 ssh 에 접속해서 composer 를 실행했거나 php artisan plugin:update 명령어를 실행했고 ssh와 웹서버 user 가 다르기 때문으로 생각됩니다. 

이 문제는 ssh 로 접속해서 해당 폴더에 있는 파일 권한을 바꿔야 합니다.
