### ISSUE TITLE
회원가입후 인증메일 재발송 안되는 문제

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1161]
AuthController.php 에서 pendingEmail()은 `$request->session()->invalidate();`을 통해 세션을 초기화 합니다 (GET요청)
https://github.com/xpressengine/xpressengine/blob/5d09e1a1eace9f3f4006c2e49765c72ff9d3c445/app/Http/Controllers/Auth/AuthController.php#L240-L258

그러면 뷰에서 `{!! csrf_field() !!}`가 아래처럼 value가 없는채로 렌더링 됩니다 
`<input type="hidden" name="_token" value="">`
https://github.com/xpressengine/xpressengine/blob/5d09e1a1eace9f3f4006c2e49765c72ff9d3c445/resources/views/user/skins/default/auth/pending_email.blade.php#L8-L17

당연히 post 날리면 세션이 만료되었다는 에러가 뜨구요.

세션을 초기화하는건 RegisterController의 getSendApproveEmail()  (POST요청) 에서 처리하는게 맞다고 보는데, 어떻게 생각하시나요?

**Comment by akasima** [comment]
`관리자 승인 후 가입` 설정을 사용할 경우 가입 후
