### ISSUE TITLE
allow_url_fopen 설정 문제를 composer2로 해결하는 방안 건의

### ISSUE THREAD

**Issue by darron1217** [xpressengine/xpressengine#1166]
allow_url_fopen이 호스팅환경에서 문제를 자꾸 일으키는것 같아서 찾아보니 해외에서도 2012년부터 논의되어온 주제였습니다.
https://github.com/composer/composer/issues/704

작년 6월 composer 2.0에 file_get_content를 curl로 대체하는 기능이 추가되었고, 이슈가 해결되었습니다.

XE3의 composer 버전을 2로 고정시켜서 allow_url_fopen으로 발생하는 문제를 해결할수 있다고 생각해서 건의드립니다.

**Comment by jhyeon1010** [comment]
현재 composer 2 적용을 검토중입니다.
말씀하신 문제외에도 성능이 상당히 개선된것으로 파악되고 있어
상당히 긍정적인 결과를 가져올것으로 예상됩니다.

다만 현재 composer 2 가 정식버전이 릴리즈 되지 않은 상태라 적용시점에 대해 논의 중입니다.

의견 감사드립니다.

**Comment by arikov10** [comment]
3주전 배포된 XE 3.1.1 버전부터 컴포저 2에서 사용가능합니다.

확인 후 이슈를 닫아주시면 감사하겠습니다.
