### ISSUE TITLE
사이트맵 메뉴 url 반복 사용할 수 있게

### ISSUE THREAD

**Issue by k-danggu** [xpressengine/xpressengine#1168]
사이트맵 에서 2차메뉴(하위메뉴)를 만들었을때 
1차메뉴의 url 란에 2차메뉴 링크를 넣으면 
이미 사용중인 주소라고 나옵니다. 
2차메뉴의 링크를 1차메뉴 url에 넣을 수 있으면 좋겠네요!

**Comment by xharpenParksuhyeon** [comment]
![image](https://user-images.githubusercontent.com/54769955/140696059-4122f9b2-c048-4f80-a669-21d832df6b9c.png)

화면과 같이 사이트 맵을 구성할 수 있도록 수정했습니다. 


- Direct Link 타입 메뉴 아이템의 URL은 중복되도 에러가 발생하지 않도록 수정했습니다.
- 메뉴 생성/수정 시 Direct Link 타입인 메뉴 아이템은 URL 중복 대상에서 제외시켜줍니다.
(test - direct link 메뉴 아이템이 생성되어 있어도 test 라는 이름으로 다른 타입의 메뉴 아이템을 생성해줄 수 있습니다.)
