### ISSUE TITLE
XE3 설치시에 PDO 클래스 에러 문제

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#118]
aaa@aaa.luatic.co.kr [~/public_html/xe3_v4]# composer install
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "/usr/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled

Fatal error: Class 'PDO' not found in /home2/aaa/public_html/xe3_v4/config/database.php on line 16
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

서버 환경에 따른 문제라고 생각합니다만,  xe3 패키지의 모든 파일을 검색해 봐도 namespace PDO; 라는 내용이 담긴 파일은 없습니다. use PDO; 만 보이네요.

구글링을 해보니 php.ini 에 PDO 패키지 내용을 기입해야 한다고 하던데
제가 php 패키지(모듈)에 관해 아는 것이 없어서 도움을 요청합니다.

**Comment by jhyeon1010** [comment]
일반적으로  rpm 을 이용한 설치시에는 PDO가 대부분 설치 됩니다.
만약 소스설치를 한 경우 `configure` 명령어 실행시 `--with-pdo-mysql` 옵션이 포함 되어야 합니다.
install 과 관련된 내용은 http://php.net/manual/en/pdo.installation.php 를 참고하시어 문제를 해결하시면 좋을것 같습니다.
보다 상세한 도움을 원하시면 다음 정보를 기재해 주시기 바랍니다.
* 서버 os 종류 및 버전
* php 버전 및 설치 방식 (rpm 설치 or 소스 설치)

**Comment by akasima** [comment]
응답이 없으셔서 이슈 닫습니다.
