### ISSUE TITLE
nginx `^~` rule에 문제가 있습니다.

### ISSUE THREAD

**Issue by soundlake** [xpressengine/xpressengine#1187]
[공식문서](http://nginx.org/en/docs/http/ngx_http_core_module.html)에 따르면 `^~` 룰의 경우 정규표현식을 체크하지 않는다고 합니다.

```
location ^~ /(assets|plugins|storage/app/public)/ {
```

모든 asset, plugins, storage/app/public 파일들에서 404 에러가 나서 라인을 다음과 같이 바꾸어 해결했습니다.

```
location ~ ^/(assets|plugins|storage/app/public)/ {
```

**Comment by akasima** [comment]
#1171 에서 해결 됐습니다.
