### ISSUE TITLE
기본 Auth스킨에서 로그인 유지 선택 후 로그인 해도 유지 안되는 문제

### ISSUE THREAD

**Issue by woongbin** [xpressengine/xpressengine#1189]
기본 Auth스킨에서 로그인 유지를 선택 후 로그인을 했는데 로그인 유지가 되지 않는 문제 수정

**Comment by xharpenParksuhyeon** [comment]
로그인 유지하기 입력 필드에 name 값이 누락되어 발생한 문제입니다.

```
<input type="checkbox" class="__xe_keep_login">
```

정상적으로 작동하도록 아래와 같이 name="remember" 를 추가해줘야 합니다.

```
<input type="checkbox" class="__xe_keep_login" name="remember">
```

----

(참고)

<a href="https://laravel.kr/docs/5.5/authentication#%EC%82%AC%EC%9A%A9%EC%9E%90%20%EA%B8%B0%EC%96%B5%ED%95%98%EA%B8%B0">라라벨 가이드 >인증 > 사용자 기억하기</a>
로그인 Controller 함수 - \app\Http\Controllers\Auth\AuthController.php - postLogin

attempt 함수 두 번째 인자에 'true' 를 전달해 로그인 유지에 사용할 remember_token 토큰을 생성해줘야 한다.
name 부분이 누락되어 두 번째 인자에 항상 'false' 가 전달되고 있다. 그래서 로그인 유지에 사용할 remember_token 이 생성되지 않아 로그인 유지하기 제대로 작동되지 않는 것이다.
