### ISSUE TITLE
togther 테마 디데이 배너 미작동

### ISSUE THREAD

**Issue by dev6641** [xpressengine/xpressengine#1190]
기본테마인 xe togther 테마의

D DAY 배너에서 새 아이템을 추가하면, 설정 페이지가 출력되지 않습니다.

카테고리 배너에서는 정상작동 합니다.

xe는 최신버전이고 테마버전은 1.0.5입니다

![제목 없음](https://user-images.githubusercontent.com/73009299/96328008-9b72a080-1079-11eb-99fc-d31e608ef8dd.png)

**Comment by xharpenParksuhyeon** [comment]
https://github.com/xpressengine/plugin-together/issues/12
