### ISSUE TITLE
composer2에서 설치 안됩니다

### ISSUE THREAD

**Issue by dev6641** [xpressengine/xpressengine#1191]
가이드보면서 aws우분투에 xe를 설치하고있었는데

오늘이 composer2가 배포된 날이라 2가 설치되더군요.
컴포저2.0으로 설치하면 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires wikimedia/composer-merge-plugin 1.3.1 -> satisfiable by wikimedia/composer-merge-plugin[v1.3.1].
    - wikimedia/composer-merge-plugin v1.3.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - xpressengine/installer[1.1.1, ..., 1.1.2] require composer-plugin-api 1.1.* -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires xpressengine/installer ~1.1.1 -> satisfiable by xpressengine/installer[1.1.1, 1.1.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2

라고 출력됩니다

컴포저 버전을 1.10.16으로 버전을 내리고 하면 됩니다.

일단은 설치안내문서 같은곳에 같이 적어두거나 하는게 좋지않을까합니다

**Comment by akasima** [comment]
감사합니다. 
며칠전에 composer2 소식은 들었는데.. 이런 문제가 발생하는군요 ;;

**Comment by arikov10** [comment]
3주전 배포된 XE 3.1.1 버전부터 컴포저 2에서 사용가능합니다.
