### ISSUE TITLE
메뉴아이템 생성시 슬러그 중복체크 과정에 site_key가 누락되어있습니다.

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#1194]
메뉴아이템 생성시 슬러그 중복체크 과정에 site_key가 누락되어있습니다.

site_key를 같이체크하도록 MenuController 안에 storeItem 과 updateItem 내의 함수를 수정해서 PR하려고 해봤으나,

지금보니 xe_menu 테이블 자체에 site_key가 없네요.

마이그레이션이 함께수정되어야할것같습니다.

**Comment by akasima** [comment]
menu 테이블에 site_key 가 추가 되었습니다. 

`메뉴아이템 생성시 슬러그 중복체크 과정에 site_key가 누락` 된 이슈는 확인하지 못했습니다. 
문제가 있다면 다른 이슈에서 처리하겠습니다.
