### ISSUE TITLE
프로필 이미지를 등록시 프로필 이미지가 엑박으로 나옴.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xpressengine#120]
URL은 정상적인지 아닌지 모르겠지만 실제 프로필 이미지를 재대로 불러오지 못하는것 같아요.

URL등록시 이미지 나타내는 src에서 잡힌 url은 
`http://도메인/storage/app/member/profile/17626d84-f7c4-4dc8-807b-0e6d75f68106/26/24/17626d84-f7c4-4dc8-807b-0e6d75f68106`
으로 나타납니다.

**Comment by bjrambo** [comment]
실제로 만들어진 `17626d84-f7c4-4dc8-807b-0e6d75f68106/26/24` 디렉토리에 ssh으로 접속해보았으나, 파일이 없는것으로 보이네요.

**Comment by YJSoft** [comment]
`.htaccess`의 `RewriteCond %{REQUEST_URI} !\.mkv` 아래에 `RewriteCond %{REQUEST_URI} !storage/app/member/profile/.*`를 넣으면 됩니다.

파일이 없다면 다른 문제(권한 등) 일 가능성이 높습니다.

**Comment by bjrambo** [comment]
@YJSoft 파일은 존재하고 있었고.. (`.env`파일 불러오지않도록 오류페이지 출력하는거 보고테스트) 프로필 파일중에서 몇가지 의문점도 있었어요.

**Comment by khongchi** [comment]
실제 파일이 존재하는데 불러오지 못했다는건가요?

**Comment by khongchi** [comment]
@YJSoft 의견처럼 rewrite rule에 문제가 있는 것으로 보이는군요.
아파치 환경에서 테스트해보도록 하겠습니다.

**Comment by bjrambo** [comment]
@khongchi 네 파일이 존재하는데 불러오지 못했던것 같아요.
신기하네요. 이미지확장자 없이 이미지로 인식하고 이미지가 뜨는게 신기..

파일 저장시, `jpg`와같은 이미지 확장자를 궂이 사용하지 않는 이유라도 잇나요?

해당 부분에서 이미지확장자가 없어서 안뜬건가 생각했거든요..

**Comment by YJSoft** [comment]
@bjrambo 웹서버에서 파일을 보내면서 type 헤더도 같이 보내서 그렇습니다. 요즘 웹브라우저는 똑똑해서 `text/html`로 이미지를 보내도 잘 해석하긴 합니다(물론 이미지 파일이 `text/html` 타입으로 왔다는 경고가 콘솔에 남긴 합니다만)

**Comment by bjrambo** [comment]
@YJSoft 덕분에 해결된것 같아요. :+1:

**Comment by khongchi** [comment]
#160 에서 처리되었습니다.
