### ISSUE TITLE
회원 > 회원 목록 > dropdown menu 미동작

### ISSUE THREAD

**Issue by seungmanchoi** [xpressengine/xpressengine#121]
회원 > 회원 목록 > dropdown menu가 동작하지 않음.

**Comment by khongchi** [comment]
좀더 자세한 설명 부탁드립니다.
그리고 회원 > 설정 > 회원 토글메뉴 설정 페이지에서 원하는 메뉴를 on 하셨는지요?

**Comment by seungmanchoi** [comment]
dropdown하는 동작 처리가 누락되어 있는 상태로 이벤트 동작되도록 플러그인 연결함.
추가로 dropdown되는 메뉴에 퍼블리싱이 되어 있지 않아 xe-dropdown-menu class 추가

**Comment by akasima** [comment]
https://github.com/xpressengine/xpressengine/commit/3894c2154796768b1fa454f712eb55e8f13dcbb3
