### ISSUE TITLE
설치 오류

### ISSUE THREAD

**Issue by kayparkphotography** [xpressengine/xpressengine#1225]
최신 버전을 카페24 계정에 업로드 하고 인스톨시 아래 링크와 같은 오류가 생깁니다.

https://www.xpressengine.com/forum/%EC%84%A4%EC%B9%98-%EC%98%A4%EB%A5%98-1

카페24 측에 문의했더니 500에러(메모리 에러)라고 하면서 .htaccess 파일에 구문을 추가해 줬는데 이후에는 또다른 오류가 생기네요.
하얀 화면의 오류 내용은 아래와 같습니다.

Warning: require(/monet/www/vendor/autoload.php): failed to open stream: No such file or directory in /monet/www/index.php on line 26 Warning: require(/monet/www/vendor/autoload.php): failed to open stream: No such file or directory in /monet/www/index.php on line 26 Fatal error: require(): Failed opening required '/monet/www/vendor/autoload.php' (include_path='.:/usr/local/php73/lib/php') in /monet/www/index.php on line 26

**Comment by bi-kim** [comment]
국내 호스팅에서 현재 오류가 생기는 것은 크게 composer, php 문제입니다.
아래 서비스를 이용 해보시는 것을 추천드립니다. (SSL 무료입니다.)
https://www.xpressengine.com/hosting
