### ISSUE TITLE
위젯 개별 기능 끄기 기능

### ISSUE THREAD

**Issue by bi-kim** [xpressengine/xpressengine#1246]
위젯을 개별적으로 숨기거나 / 끄는 기능 필요.
info.php의 설정 값이 많을 수록 데이터를 삭제하고 추가하는 것이 번거롭기 때문에 일시적으로 삭제가 아닌 끄는 기능 필요.

**Comment by xharpenParksuhyeon** [comment]
끄지 않고 모두 노출한 화면

![image](https://user-images.githubusercontent.com/54769955/126860626-fd2a7305-3f6e-49b9-86e0-79199c1df44f.png)

기능을 꺼서 모두 노출하지 않는 화면
![image](https://user-images.githubusercontent.com/54769955/126860646-74b2fd1c-417a-48e9-baac-f22c2a9906eb.png)

설정창
![image](https://user-images.githubusercontent.com/54769955/126860654-bc8dee12-278b-47df-a285-b596d6eabb02.png)

**Comment by xharpenParksuhyeon** [comment]
위젯에 `@attributes.activate` 키 추가. / `@attributes.activate` 값으로 화면의 노출 여부를 결정합니다.

값
- activate : 화면에 노출
- deactivate : 화면에 노출 안함

```
{
   "@attributes":{
      "id":"widget\/xpressengine@contentInfo",
      "title":"sss",
      "activate":"deactivate",
      "skin-id":"widget\/xpressengine@contentInfo\/skin\/xpressengine@default"
   },
   "widgetName":"",
   "skinName":""
},
```
