### ISSUE TITLE
위젯에서 info.php를 사용해서 설정창을 구성할 수 있도록 코드 수정

### ISSUE THREAD

**Issue by xharpenParksuhyeon** [xpressengine/xpressengine#1271]
Skin 에서 사용되는 `info.php` 를 위젯 컴포넌트에서 사용할 수 있도록 합니다.
자체 config 페이지를 구성하고 싶다면 Skin 컴포넌트와 동일하게 `settings.blade.php` 를 사용하면 됩니다.

https://www.xpressengine.com/guide/skin-develop/skin-config-edit

![image](https://user-images.githubusercontent.com/54769955/126873713-ae910e53-4670-4350-8bb6-35c078641331.png)

```
<?php

  return [
      'setting' => [
          'sample_text2' => [
              '_type' => 'text',
              '_section' => '기본설정',
              'label' => '샘플 문구',
              'placeholder' => '샘플용 설정 필드입니다.',
              'description' => '샘플용 설정 필드입니다.',
          ],
          'logo_url_real' => [
              '_type' => 'medialibraryImage',
              '_section' => '기본설정',
              'label' => '로고 이미지',
              'placeholder' => '로고 이미지 주소 링크를 넣어주세요.',
              'description' => '콘텐츠에 등록된 이미지 주소를 등록해주세요.',
              'limit' => 1,
          ]
      ]
  ];
```

**Comment by xharpenParksuhyeon** [comment]
https://github.com/xpressengine/xpressengine/issues/1270

위젯도 스킨과 동일하게 medialibraryImage 타입에 필수적으로 'limit' => 1 를 명시해줘야 합니다.

**Comment by bi-kim** [comment]
#1273 
https://github.com/xpressengine/xpressengine/issues/1273
