### ISSUE TITLE
메뉴 이동 시 405 에러가 나오고 메뉴가 이동되지 않습니다.

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#13]
메뉴 이동 시 Progress Bar가 나타나지만, 405 에러로 인해 실제로 반영되지 않습니다.

**Comment by findstar** [comment]
메뉴 이동이 되지 않은 시점에서 storage/logs/laravel.log 에 있는 로그 내역을 함께 보내주셔야 정확한 파악이 됩니다.

**Comment by smaker** [comment]
확인해보니까 서버에서 PUT 요청을 막아놓은 경우인 것 같네요. 해결했습니다^^
