### ISSUE TITLE
위젯 박스 편집시 타이틀 등에 일부 특수문자 입력시 출력되지 않는 이슈

### ISSUE THREAD

**Issue by choijeong** [xpressengine/xpressengine#1317]
확인 된 이슈 

위젯페이지에서 위젯박스 편집시 
위젯 타이틀에 & 가 들어가면 출력되지 않습니다 - 예외처리 , 에러로그 등 남지않습니다

**Comment by choijeong** [comment]
추가 

위젯 스킨 생성시  component name 에 & 이 들어간 경우에도 출력되지 않습니다

**Comment by xharpenParksuhyeon** [comment]
#1278 위젯 설정 > 위젯 제목에 & 가 들어간 경우 화면에 표시가 안되는 문제가 발생합니다.

위젯 설정 > 위젯 목에 & 가 들어가 있는 경우 화면에 위젯이 표시가 안되는 문제는 위 이슈에서 해결했습니다.
----


타이틀을 제외한 위젯 설정에 & 엔티티 코드 라고 불리는 값이 저장되어 있는 경우에도 출력이 안되는 이슈를 확인했습니다.
