### ISSUE TITLE
Together 기본스킨의 위젯에서 참조하는 게시판을 삭제하면 오류 발생

### ISSUE THREAD

**Issue by kms0219kms** [xpressengine/xpressengine#1341]
Together 기본스킨의 위젯에서 참조하는 게시판(갤러리 등)을 삭제하면 치명적인 Widget Error 오류가 발생합니다.

Slack에서도 언급한 바 있으나 참조하는 위젯이 해당 게시판을 찾지 못하여 에러가 발생하는것으로 추정됩니다.

정말 해당게시판이 존재하면 에러가 발생하지 않습니다.

![image-1](https://user-images.githubusercontent.com/67222970/130759058-97e96d2b-011a-42c3-9f09-08f9fc61da22.png)

![image](https://user-images.githubusercontent.com/67222970/130758998-5ad8284a-11eb-4ac9-a7c3-0de220bb778d.png)

![image-2](https://user-images.githubusercontent.com/67222970/130759088-25088786-9f81-4fa2-886c-06fbd12f4d07.png)

![image-3](https://user-images.githubusercontent.com/67222970/130759094-5abb87e3-ecc6-4181-815b-86e531465240.png)

**Comment by xharpenParksuhyeon** [comment]
`위젯` 에서 발생하는 오류는 `위젯 박스에 대한 편집 권한` 을 가진 관리자에게만 보입니다.
편집 권한이 없는 일반 사용자한테는 노출되지 않습니다.

위 오류가 발생한 이유는 위에서 말씀하신 것처럼 `위젯`에 연결된 게시판이 삭제되었기 때문입니다.
관리자는 출력된 `위젯 오류`를 통해 문제를 파악해 다른 게시판을 연결하거나 해당 위젯을 지워주는 판단을 내리면 됩니다.

위에 출력되는 에러는 관리자가 해야 할 다음 행동에 대한 `이정표 역활`을 하고 있습니다.
아마 에러 메시지가 명확하지 않아 오해가 생긴 것 같습니다.

---

에러 메시지를 더 명확하게 표현하는 방향으로 가겠습니다.
