### ISSUE TITLE
사이트메뉴편집 DirectLink 생성 이후 수정 오류

### ISSUE THREAD

**Issue by bi-kim** [xpressengine/xpressengine#1354]
1) /test 위젯페이지로 이동하는 test DirectLink를 생성 이후
2) 테마 수정과 같은 메뉴 수정 행위 후
3) /test가 다이렉트 링크에 의해 편집이 불가능한 상태에 빠지는 문제가 있음.

- `/test[widgetpage@widgetpage]`
- `test[xpressengine@directLink]`

**Comment by xharpenParksuhyeon** [comment]
화면과 같이 사이트 맵을 구성할 수 있도록 수정했습니다.

Direct Link 타입 메뉴 아이템의 URL은 중복되도 에러가 발생하지 않도록 수정했습니다.
메뉴 생성/수정 시 Direct Link 타입인 메뉴 아이템은 URL 중복 대상에서 제외시켜줍니다.
(test - direct link 메뉴 아이템이 생성되어 있어도 test 라는 이름으로 다른 타입의 메뉴 아이템을 생성해줄 수 있습니다.)
