### ISSUE TITLE
ConfigEntity에서 dot(.) notation 지원 논의

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#140]
| name | vars |
|---------|-------|
| xe | {"a":{"b":"1","c":"1"}} |

위와 같이 config table에 데이터가 저장되어 있는 상태에서 `a.b`의 값(1)을 바로 조회할 수 있으면 편의상 좋을 것 같음.

아래 코드에서와 같이 ConfigEntity::get() 메소드에 dot notation을 사용하여 데이터 내부의 값을 조회할 수 있도록 지원하면 어떨까 함.

```
$configEntity = XeConfig::get('xe');
$b = $configEntity->get('a.b'); // $b = "1"
```

**Comment by jhyeon1010** [comment]
오키
