### ISSUE TITLE
플러그인 목록에서 꺼진 플러그인만 볼 수 없음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#16]
상단 전체/켜짐/꺼짐 중 꺼짐이 작동하지 않습니다. 즉, 꺼진 플러그인만 표시하는 페이지가 동작하지 않습니다.

**Comment by khongchi** [comment]
@YJSoft 
증상 다시 한번 확인해주세요. 재현되지 않습니다.

**Comment by khongchi** [comment]
증상 확인하고 수정하였습니다.
