### ISSUE TITLE
Unknown User 객체 추가

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#168]
특정글을 작성했던 사용자가 탈퇴와 같은 상황을 통해 누군지 알 수 없게된 경우
화면에 표현되어지기 위함이나
relation 을 통해 다른 영역에서 사용되어지기 위해 필요로 함

예) document 에서 작성자를 가져오는 경우를 가정하고 화면에 작성자 이름을 표현
```
$document->user->getDisplayName();
```
위 코드에서 
document 에 작성자 고유 아이디가 없는경우 user 는 `Guest`
document 에 작성자 고유 아이디는 존재하지만 user 가 조회되지 않는 경우 `UnknowUser`

사용 방식은 사용하는 측에서 알아서 자유롭게 구현함
```
public function getUser()
{
    $user = $this->user;
    if ($user === null) {
        $user = new UnknowUser();
    }
    return $user;
}
```
```
$document->getUser()->getDisplayName();
```

**Comment by khongchi** [comment]
@jhyeon1010 
게시글을 출력할 때, 해당글 작성자가 존재하지 않는다면 작성자 이름으로 뭘 출력하지?

**Comment by jhyeon1010** [comment]
@khongchi 
Guest 가 `Guest` 라는 문자로 지정되있는거 처럼
UnknowUser 도 별도로 지정하면 되고 
지정될 실제 이름은 정하기 나름
