### ISSUE TITLE
회원 페이지 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#179]
회원가입페이지

- [ ] 비밀번호 레벨 설정 문제
AuthController::getRegister() 에서 `$passwordLevel` 의 문구를 config 에서 가져와서 다국어 처리하는데 문제가 있음

- [x] 사이트 이용 약관, 개인정보 보호정책 링크 없음
링크 없음.

로그인 페이지

- [x] 로그인 유지 펼침 기능 오류

- [x] 필드명에서 회원이름 제거

**Comment by khongchi** [comment]
비밀번호 레벨 설정 문제는 #212 에서 처리할 예정
