### ISSUE TITLE
오류 페이지의 아이콘이 뜨지 않음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#18]
오류 페이지의 아이콘은 XEIcon 1.0.4 기준으로 작성되어 있으나 실제로는 XEIcon 2.0.0이 사용되고 있어 아이콘이 보이지 않습니다.

**Comment by khongchi** [comment]
아이콘 출력되도록 처리, 아이콘 크기는 xe-icon이 업데이트되면 적용될 예정입니다.
