### ISSUE TITLE
설치시, .htaccess 파일을 생성하지 않음.

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xpressengine#2]
설치시 .htaccess 파일을 생성하지 않아 문제점이 발생합니다.
그리고 셋팅정보가 들어간 텍스트형태의 파일이 브라우저 주소로 들어가면 그냥 내용이 노출되는 문제점도 있습니다

**Comment by findstar** [comment]
.htaccess 파일이 http://start.xpressengine.io/latest.zip 에 포함되어 있지 않은 문제. 확인후 수정 예정

**Comment by jdssem** [comment]
Laravel의 경우 public 폴더가 server root의 역할을 했는데 xe3의 경우에는 app root가 server root와 동일하네요. 그러면 자연스레 .env 파일이 외부에 노출될 일도 없을 것 같은데 굳이 이런 방식으로 만드신 것은 이유가 있는 거겠죠?

**Comment by findstar** [comment]
호스팅 환경에서는 별도의 public 폴더를 구성하기 어려운 경우가 많아 그렇게 처리하였습니다. 고민을 많이 했던 부분중에 하나입니다.

**Comment by khongchi** [comment]
installer에서 삭제하지않도록 변경하였습니다.
