### ISSUE TITLE
게시판 플러그인의 설정중 새글표시의 시간설정이 밀리초설정인듯합니다.

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xpressengine#20]
직관성이 떨어지고 일반 사용자가 설정에 어려움이 잇어 보입니다. 해당 부분을 시간 형태로 (1시간단위)으로 설정할 수 잇었으면 좋을 것 같습니다.

**Comment by YJSoft** [comment]
밀리초가 아니라 초 아닐까요?

**Comment by qw5414** [comment]
@YJSoft 아 초이군요..

시간 단위를 분 단위도 아닌 시간 단위가 더 설정에 용의할 것 같습니다. 유저들이 1초, 1분의 차이를 느껴가면서 새글 표시를 하지 않을 것으로 보여지기 때문이지요..
