### ISSUE TITLE
내 프로필 페이지 UI 개선

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#205]
- [x]  프로필이미지 수정 버튼
  내 프로필 페이지에서 수정 눌렀을 때 대표사진을 수정할 수 있는데 배경 no image 와 버튼 아이콘이 모두 흰색이에서 눈에 띄지 않음

  ![2016-07-07 3 16 08](https://cloud.githubusercontent.com/assets/5836237/16644216/207b4902-4456-11e6-950b-d1fe443cd51d.png)

  아이콘 색이 바뀌든.. 배경 이미지가 바뀌든 눈에 띄게 되었으면 좋겠습니다.
 
- [x]  모바일에서 프로필 페이지 좌우 짤림
  프로필 페이지의 좌우 padding이 크게 설정돼 있어 모바일 페이지에서 짤려 보입니다.

**Comment by LeeYoonGu** [comment]
![2](https://cloud.githubusercontent.com/assets/10300327/16680920/e4028b3e-452c-11e6-9bcc-5b320b8d8b1b.png)

프로필 이미지의 수정 버튼이 잘 안 보이는 이슈는 이미지 위에 딤드추가하여 처리 함.
