### ISSUE TITLE
example.xe3-nginx-rewrite.conf를 사용하면 문제가 발생함

### ISSUE THREAD

**Issue by dorami** [xpressengine/xpressengine#208]
example.xe3-nginx-rewrite.conf를 사용하면 도메인을 입력하면 파일을 다운로드 하는 현상이 발생합니다.

**Comment by bnu** [comment]
https://github.com/xpressengine/xpressengine/blob/master/example.xe3-nginx-rewrite.conf#L32-L35

.php 확장자에 대한 PHP-FPM 등의 설정이 되지 않은 예시입니다.
일부 파일에 대한 접근을 열거나 막는 등의 설정을 위한 설정의 예시이며, .php 확장자에 대한 처리는 서버 환경에 맞게 설정하세요. PHP-FPM의 기본 설정이라면 주석을 푸는 것만으로 동작 가능할 수 있습니다.
