### ISSUE TITLE
소셜 로그인 사용할 때 facebook 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#209]
https://xpressengine.io/qna/%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C

```
ErrorException in FacebookProvider.php line 90:

Undefined index: first_name
```
소셜 로그인 점검 필요

**Comment by khongchi** [comment]
소셜로그인 플러그인으로 이슈 옮겨감
