### ISSUE TITLE
사이트맵에서 2차 메뉴 세팅시...

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xpressengine#21]
사이트 맵에서 2차메뉴를 세팅시 1차메뉴가 바로가기도 아니고, 일반게시판으로 생성되었어도 링크를 사용할 수 없고 주소창의 URL에 `#`만 추가되는 문제점이 있습니다.

**Comment by findstar** [comment]
alice 테마에서 연결된 메뉴 트리를 출력하는 과정에서 2차 메뉴를 인지하지 못한것으로 보입니다. 수정하겠습니다.

**Comment by khongchi** [comment]
https://github.com/xpressengine/plugin-alice/issues/2
이슈 이동함.
