### ISSUE TITLE
plugin 에서 $installedVersion 사용 방법 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#230]
update, checkUpdated 할때 `$installedVersion`을 전달하는데 인스톨 하는 과정에서 전달하지 않음

현재 버전을 이용해서 update 할 때 해야할 때 처리할 내용을 정리하려 했으나 전달 되지 않아 어려움이 있음

**Comment by khongchi** [comment]
`$installedVersion`을 update, install 과정에서 사용하지 않는 것으로 변경
