### ISSUE TITLE
사이트맵 메뉴 설정에서 테마 수정 시 반영 안되는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#234]
/settings/menu 에서 메인메뉴 를 클릭하고 메인메뉴의 테마를 수정할 경우 
처음 수정할 때는 반영이 되지만 두번째 수정할 때는 수정사항이 반영안되는 문제가 있습니다.

**Comment by khongchi** [comment]
일단 `debug = false` 환경에서 정상작동 하는것으로 보여집니다.
문제 재발시 다시 이슈화시키는걸로 하겠습니다.
