### ISSUE TITLE
artisan serve 에러

### ISSUE THREAD

**Issue by appkr** [xpressengine/xpressengine#236]
```sh
~/xe3 $ php artisan serve
# [ErrorException]
# chdir(): No such file or directory (errno 2)
```

document_root를 public 디렉터리 밖으로 빼내면서 생긴 문제로 보입니다. 문제 발생위치는 `xe3/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:36`네요.

구조를 몰라 PR을 못드리고, 신고라도 해 봅니다.

**Comment by khongchi** [comment]
말씀하신대로 `public`  경로를 변경해서 발생하는 오류로 보입니다.

그런데, XE는 PHP 내장 웹서버 환경을 고려치 않고 개발중입니다. 위 오류를 고친 이후에 XE가 제대로 작동할지는 미지수입니다.

**Comment by appkr** [comment]
XE팀에서 뭔가 조치는 했으나, 안먹는 거였군요. 
https://github.com/xpressengine/xpressengine/blob/master/bootstrap/app.php#L84

일루미네이트 코드를 잠시 봤더니, `public` 경로가 ㅎㄷㄷ한 하드코드네요. 
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Application.php#L370

런타임에 몽키패칭도 안되고, 그렇다고 Application을 상속 받기도 그렇고... G.G 쳐야죠.

---

`artisan serve` 대신 이렇게라도 안내해 주면 좋겠네요.

```sh
~/xe3 $ php -S 0.0.0.0:8000
```

**Comment by jhyeon1010** [comment]
일단 public path를 변경하여 사용할 수 있도록 하는 코드를 PR 보내놨으니 merge 해줄지 지켜봐야겠어요.

https://github.com/laravel/framework/pull/14620

**Comment by appkr** [comment]
으이구, Reject 당했군요.

`public`으로 홈 디렉터리를 격리하는 것이 보안 측면에서 모범사례이긴한데... 그래도 `php artisan serve --docroot=.` 같은 옵션을 제공해 주면 좋을텐데... 혹시라도 혹시라도 제가 PR하게 되면 여기에 링크 남길게요.
