### ISSUE TITLE
메뉴 > 게시판 카테고리 관련 오류

### ISSUE THREAD

**Issue by clivers** [xpressengine/xpressengine#247]
오류로 보여 확인 부탁드립니다.

1.요약
게시판(Board) 모듈의 분류(Category)기능 오류.

2.설명
메뉴아이템으로 게시판 생성 후, 
상세설정에서 카테고리 '상위설정에 따름'해제, 
Use로 선택하고 저장 버튼 클릭하여 카테고리 사용으로 설정(이 부분에서도 category table의 name에 instance id 없이 입력되어 오류가 발생하는 경우가 있음)
이후 '상위설정에 따름' 체크 후 저장 버큰 클릭해도, 
게시판에 글 입력 시 분류 선택란이 계속하여 표시되고, 
등록버튼을 클릭 시 분류를 입력하라는 경고메세지가 팝업 됨.

**Comment by akasima** [comment]
https://github.com/xpressengine/plugin-board/issues/44 이것과 연결해서 처리하겠습니다.

게시판 설정에서 '카테고리 사용' 설정은 '상위설정에 따름'을 제공하지 않을 계획입니다.

설정한 카테고리를 공유하고 사용하는데 있어서 문제가 있다고 판단되어 이렇게 결정했습니다.
다음주 배포 예정인 beta4 에 포함되서 처리될 수있도록 하겠습니다.

**Comment by akasima** [comment]
카테고리를 사용함으로 설정할 경우 카테고리 패키지 컨트롤러에게 카테고리 인스턴스 아이디를 획득하는 과정이 있습니다. 이 과정이 완료되면 '카테고리 선택' 셀렉트 박스옆에 '카테고리 관리' 버튼이 활성화 되는데요.

이때 아이디를 획득하기 전에 설정을 등록하면 instance id 없이 등록되는 오류가 발생하게 될텐데요. 이걸 방지하기 위해서 설정 등록 버튼을 비활성화 시켜야하는지 고민입니다.

일단.. 고민 되어 처리하지 않고 이슈는 닫겠습니다.
