### ISSUE TITLE
XEIcon 등 일부 리소스가 http://로 하드코딩됨

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#25]
XEIcon 등 일부 리소스가 http://로 하드코딩되어 https 환경에서 불러올 수 없습니다.

**Comment by YJSoft** [comment]
일단 확인된 것은 XEIcon과, 프로필 페이지의 웹폰트입니다.

**Comment by khongchi** [comment]
프로필 페이지의 웹폰트는 하드코딩되어 있지 않아  문제가 없어보입니다.
아직 문제가 남아있다면 댓글 달아주세요.
