### ISSUE TITLE
Frontend::js before() 동작 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#255]
`XeFrontend::js('/plugins/openseminar_point/assets/test.js')->before('assets/vendor/jquery/jquery.min.js')->load()` 코드가 동작하지 않음

플러그인에서 jquery.min.js 앞에 load 하기 위해 테스트 했지만 동작 안하는걸로 보입니다.

**Comment by khongchi** [comment]
before로 지정한 파일이 먼저 로드돼요. ^^
