### ISSUE TITLE
플러그인 부팅 과정에서 로그인 체크시 비 로그인 상태로 표시되는 에러

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#257]
로그인된 상태일때 플러그인 부팅과정중 `Auth::check()` 또는 `Auth::user()` 호출시 비로그인된 상태로 처리됨.
어플리케이션 부팅과정중 Auth에 현재 사용자가 지정되기 전인 시점에서 해당 메서드들이 호출될경우 현재 사용자를 `Guest` 객체로 지정되어지게 되어있음
`Xpressengine\User\Guard` 의 다음 메서드에서 발생하는 에러로 보임
```php
    public function user()
    {
        $user = parent::user();
        if ($user === null) {
            $user = $this->makeGuest();
        }

        return $this->user = $user;
    }
```
위 코드에서 `return $this->user = $user;` 를 `return $user;` 로 변경해야 할 것으로 보임

**Comment by khongchi** [comment]
두가지 문제에 대해 처리 예정

1. Auth::user()가 플러그인 부팅과정과 같이 준비가 되기 전에 실행될 경우 예외 발생
2. `return $this->user = $user;` 를 `return $user;` 로 변경
