### ISSUE TITLE
사이트맵을 추가했습니다. 그리고 보이지 않습니다.

### ISSUE THREAD

**Issue by anakkadde** [xpressengine/xpressengine#258]
대시보드-사이트맵 에서 새로운 상위 메뉴 추가시 표시되지 않습니다.
Site패키지가 완전하지 않았다고는 들었습니다만 그것과는 관련이 있는걸까요?
데이터베이스에는 정상적으로 기록되는것으로 확인되며 표시는 되지 않는 것 같습니다.
![1](https://cloud.githubusercontent.com/assets/12424759/17829091/7f425ad0-66dd-11e6-90c7-0bc9ac8d84b1.PNG)
![2](https://cloud.githubusercontent.com/assets/12424759/17829092/7f57093a-66dd-11e6-88c2-48e02e387861.PNG)

**Comment by jhyeon1010** [comment]
메뉴정보가 갱신되어질때 cache 가 갱신되지 않는 문제로 보입니다.
확인하여 수정조치 하겠습니다.
