### ISSUE TITLE
프런트 다국어 관련 - XE3 로케일 변경시 페이지 리다이렉트 이슈

### ISSUE THREAD

**Issue by paikwiki** [xpressengine/xpressengine#259]
XE3 로케일과 관련된 이슈를 발견해서 글 남깁니다. 
로케일 변경시 로컬호스트 루트 폴더의 "locale/{lang}"으로 이동합니다({lang}은 ko와 en입니다.)

XE3가 설치된 서브디렉토리를 URL에 추가해주면 로케일 설정한 대로 한글/영문이 잘 나옵니다. 해당 내용을 쉽게 확인하실 수 있도록 "[유튜브 동영상-XE3 로케일 변경시 페이지 리다이렉트 이슈](https://youtu.be/XRMbYSForfU)"로 공유합니다. XE3를 설치한 경로는 "http://localhost/xpressengine-20160820/"입니다.

**Comment by jhyeon1010** [comment]
현재 locale 을 변경하는 방식에 대해 논의 중입니다. 변경방식이 결정되는대로 알려주신 오류에 대한 부분도 수정 적용하도록 하겠습니다.
