### ISSUE TITLE
서브디렉토리 설치 환경에서 사용자 지정 다국어 출력오류

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#265]
서브디렉토리에 XE를 설치한 환경에서 사용자 지정 다국어가 출력될 때,
지정된 서버의 주소를 잘못 지정하여 다국어가 출력되지 않은 오류가 있음.

주소를 지정할 때에는 항상 `route()` 또는 `url()`을 사용하여 지정하도록 변경해야 함.

**Comment by seungmanchoi** [comment]
https://github.com/xpressengine/xpressengine/issues/262

동일 문제 이슈로 이미 해결된 사항으로 이슈 처리
