### ISSUE TITLE
모바일 게시판에서 카테고리 선택에 따른 글 목록수 문제

### ISSUE THREAD

**Issue by GuSeoJun** [xpressengine/xpressengine#269]
PC버전에서 게시판에서 글 목록수를 20으로 지정해놓고

 

모바일 버전 게시판에서 글 목록수를 5로 지정해놓았는데요.

 

모바일 버전 게시판에서 글 목록수가 처음화면일 때는 5가 되는데..

 

카테고리를 선택해서 들어가면 글 목록수가 PC버전으로 돌아가는 것 같네요.

 

예를 들면

 

자유게시판 안에 '일상', '사회', '유머' 등의 카테고리가 있다고 하면

 

자유게시판에 들어가면 모바일에서도 글 목록이 5로 뜨는데, 일상이나 사회 등 카테고리를 클릭하거나 필터를 지정하면

 

글 목록수가 풀리게 돼요. 어떻게 해결해야 할까요?

**Comment by akasima** [comment]
XE1 이슈로 보이는데요. 
https://github.com/xpressengine/xe-core/issues 여기에 작성되어야할 사항으로 보입니다.

만약 XE3에 대한 이슈가 맞다면 comment로 알려주세요.

**Comment by GuSeoJun** [comment]
그러네요. 여기는 XE3 이슈 올리는 곳이었군요. 감사합니다..^^
