### ISSUE TITLE
getYearlyArchivedList 추가

### ISSUE THREAD

**Issue by cydemo** [xpressengine/xpressengine#270]
document 모듈에 getDailyArchivedList와 getMonthlyArchivedList의 쿼리 및 함수는 있는데, getYearlyArchivedList는 없습니다.
년월일별로 문서 아카이브를 구현할 때 년별로도 문서 갯수를 편하게 가져올 수 있으면 해서요.

덧:  getDailyArchivedList의 쿼리 id가 getMonthlyArchivedList로 되어 있는데, 깔끔하게 getDailyArchivedList로 고쳐지면 좋겠습니다.

**Comment by akasima** [comment]
XE1 이슈로 보이는데요. 
https://github.com/xpressengine/xe-core/issues 여기에 작성되어야할 사항으로 보입니다.

만약 XE3에 대한 이슈가 맞다면 comment로 알려주세요.

**Comment by cydemo** [comment]
아이고, 제가 주소를 잘못 찾아왔군요ㅠㅠ
