### ISSUE TITLE
소셜로그인 플러그인 로그인에서 CAPTCHA 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#273]
소셜로그인 스킨에서 이메일로 로그인 할 경우 CAPTCHA 적용 안되는 문제가 있음

로그인과 회원가입을 처리하는 스킨의 형태가 조금 다른데.. 기능 동작 방식을 통일하는게 좋을것 같아 보입니다.

![social_login_skin](https://cloud.githubusercontent.com/assets/5836237/18041554/1c51a3d0-6df5-11e6-9206-c91db2cb7b54.png)

**Comment by khongchi** [comment]
소셜로그인 플러그인 이슈입니다.
