### ISSUE TITLE
릴리즈 날짜

### ISSUE THREAD

**Issue by choiks14** [xpressengine/xpressengine#278]
언제 릴리즈 될지 대략적인 시점을 알수 있을까요?

**Comment by akasima** [comment]
beta 꼬리표를 언제 버릴지 물어보신 건가요?

**Comment by choiks14** [comment]
네 바쁘신중에 이런 질문이 이상하시겠지만 빨리 사용해보고 싶어서요..

**Comment by akasima** [comment]
beta 를 떼고 RC 버전으로 넘어갈 예정 입니다. RC는 11월 23일로 예정하고 있습니다.
이 버전은 안정화된 버전으로 사용에 문제 없는 수준으로 만들어 배포 할 예정입니다.

물어보신 정식 버전 배포 일정은 내부적으로 협의된 일정이 있지만 아직 공개하기는 무리가 있습니다.

**Comment by choiks14** [comment]
네 항상 감사하게 생각하고 있습니다. 
11월 23일 기대하겠습니다. ^^
