### ISSUE TITLE
소셜로그인 플러그인 사용할 때 트위터 API 를 사용하지 못하는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#283]
소셜 라이트 사용할 때 가입/로그인 은 정상 처리되지만 접속한 회원의 token을 이용해서 각 sns api 를 사용하려 할 경우 트위터 사용에 문제가 있습니다.

깃허브 에도 사용해보지 않았지만 동일한 문제가 있을것으로 생각됩니다.

socialite One/Two 로 나뉘어진 프로바이더들이 setToken() 하는 방법이 각각 다른데요.
트위터와 깃허브는 token, tokenSecret 을 set 하도록 되어있습니다.
아마도 이 두개는 두개의 키로 처리해야해서 그런것 같은데요.

social_login 플러그인과 XE3 User 는 token 만 처리하도록 되어 있어 tokenSecret 을 저장할 수 없습니다. 
그렇기 때문에 획득한 token 을 사용할 경우 api 에 인증을 할 수 없는 문제가 있습니다. ('Exception: Could not authenticate you.' )

token을 사용할 수 있도록 수정되야 할것으로 보입니다.

**Comment by khongchi** [comment]
트위터와 빗버킷을 얘기하는거죠?

`user_account` 테이블에 `tokenSecret` 컬럼을 추가하겠음.

**Comment by akasima** [comment]
코어 업데이트 할 때 user_acount 테이블 스키마 변경은 처리되지 않았습니다.
