### ISSUE TITLE
게시판 에디터에서 이미지가 아닌 파일을 본문삽입할 때 오류

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#290]
게시판 에디터에서 이미지가 아닌 파일을 업로드하고 본문삽입할 경우 본문삽입되는 이미지의 링크가 올바르지 않습니다.

**Comment by jhyeon1010** [comment]
xpressengine/plugin-ckeditor@2471029668029d3e57205abd63d1ac59a28ffe62
