### ISSUE TITLE
설치되지 않은 플러그인에 업데이트 표시 나오는 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#291]
설치하지 않은 (한번도 활성화 하지 않은) 플러그인에 "새로운 업데이트가 다운로드 되었습니다. 지금 업데이트 적용하기." 표시가 됩니다.

실제 업데이트할 플러그인이 있는데 이런 오류가 (메시지가 같은) 있으니 사용에 불편함이 있습니다.

![plugin_list_message_error](https://cloud.githubusercontent.com/assets/5836237/18372796/27f0b96e-767a-11e6-8493-7aa9ed4cccc1.png)

**Comment by khongchi** [comment]
플러그인 관련 UI를 전체적으로 손 볼 필요가 있음. 차후 이슈 잡아 처리하겠음.
