### ISSUE TITLE
xe-page에서 href 항목을 참조하지 않음.

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#292]
data 애트리뷰트를 이용한 xe-page 사용방법에서 아래와 같이 `<a>`태그에서  `data-url` 속성이 누락됐을 경우, `href` 속성을 대신 사용하지 않고 있음.  사용되도록 변경 요청
```
<a href="...." data-toggle="xe-page-modal">link</a>
```

**Comment by seungmanchoi** [comment]
href의 값을 data object의 url로 넘기고 있어서 발생한 오류 수정.
