### ISSUE TITLE
댓글 수정할 때 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#299]
댓글 작성 후 수정할 때 이전 내용을 에디터에 표시하지 않는 오류가 있습니다.

**Comment by jhyeon1010** [comment]
수정 요청에 의해 서버에서 전달하는 값은 정상적으로 보입니다. 해당 문제는 클라이언트측의 스크립트에서 이상동작을 보이는것 같습니다. 에디터가 활성화 된 후 `setContents` 메서드를 호출하여 내용을 삽입하려 해도 에디터에 내용이 표현되지 않습니다.

**Comment by seungmanchoi** [comment]
ckeditor allowedconten 설정변경으로 이슈 수정됨.
