### ISSUE TITLE
ckeditor 다이나믹 필드를 추가할 수 없습니다.

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#315]
게시판이나 회원의 추가 필드 설정에서 ckeditor 필드를 추가할 수 없습니다.

추가할 필드 타입을 ckeditor로 선택할 경우, `시스템에 오류가 있습니다. 관리자에게 문의하세요.` 토스트 팝업이 출력됩니다.

**Comment by akasima** [comment]
ckeditor 다이나믹 필드는 삭제해야겠네요.

**Comment by akasima** [comment]
연결된 이슈에서 언급했지만 다이나믹필드 지원에 대한 코드 구현은 완료했으나 이후 설정이나 운영상의 이슈가 많이 발생해서 지원하지 않는것으로 결정했습니다.
