### ISSUE TITLE
시스템 요구사항에 추가 부탁드립니다.

### ISSUE THREAD

**Issue by Enosh-Yu** [xpressengine/xpressengine#321]
GD extension 도 시스템 요구사항에 추가부탁드립니다.
GD설치가 안 되어 있을 경우 설치시 오류가 납니다.

**Comment by akasima** [comment]
웹 인스톨에서 체크하고 있는것 같은데요. 이것 말고 또 해야할게 있다는 말씀이신가요?
![ss](https://cloud.githubusercontent.com/assets/5836237/19587330/976c36e4-9798-11e6-914e-eff7fab8d6d6.png)

**Comment by akasima** [comment]
매뉴얼에 추가했습니다.

**Comment by Enosh-Yu** [comment]
감사합니다. 
git clone 해서 composer 와 artisan 을 이용해서 설치를 했습니다.
설치할 때 체크를 하기는 합니다만.
readme 파일에 시스템 요구사항에 GD extension 이 없어서 요청드렸습니다~

**Comment by akasima** [comment]
넵 매뉴얼에 추가 했으니 이슈는 닫겠습니다. 감사합니다.
