### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by tuffkidd** [xpressengine/xpressengine#322]
윈도우즈 플랫폼에서 설치 후 관리자 로그인 > 플러그인 목록 접근 시
`cURL error 60: SSL certificate problem: self signed certificate in certificate chain` 
에러가 발생합니다.

SYSTEM
-
- Windows 10
- Apache 2.4.17
- PHP 7.0.1
- MariaDB 10.1.9
- XE3 BETA 7

**Comment by khongchi** [comment]
curl을 사용하여 https 요청을 전송할 때 발생하는 오류로 보입니다.
동일한 오류를 재현하는데 성공했고, 처리중입니다.

**Comment by khongchi** [comment]
아래와 같은 방법으로 해결 가능합니다.

https://curl.haxx.se/docs/caextract.html 페이지에서 `cacert.pem` 파일을 다운로드 받습니다.

`php.ini` 파일의 curl.cainfo 항목을 찾은 다음, 다운로드 받은 파일의 경로를 아래와 같이 지정한 후, 서버를 재시작합니다. (`cacert.pem` 파일의 경로가 `c:\php\cacert.pem`일 경우)

```
curl.cainfo=c:\php\cacert.pem
```





참고: https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/

**Comment by tuffkidd** [comment]
덕분에 잘 해결했습니다. 고맙습니다.
