### ISSUE TITLE
소셜 로그인 관리자 메뉴 위치 조절

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#328]
소셜 로그인 관리자 메뉴가 최상위에 위치하고 있습니다.

다른 곳이로 이동하거나 아래로 내리는것이 좋을것 같네요.
<img width="249" alt="error4" src="https://cloud.githubusercontent.com/assets/5836237/19845617/d81ba658-9f7b-11e6-80be-898ade1101fb.png">

**Comment by khongchi** [comment]
user 키워드 변경으로 인한 문제로 발생한 문제네요.

https://github.com/xpressengine/plugin-social_login/commit/e06ef4ff9887e1af8a4ca766d44be1fb393a28d1 에서 처리되었습니다.
