### ISSUE TITLE
등록된 메뉴를 삭제, 저장하면 홈화면이 보이지 않는 문제

### ISSUE THREAD

**Issue by neoche** [xpressengine/xpressengine#334]
사이트 메뉴에 등록 된 메뉴를 삭제 후 저장하면 사이트가 500 error로 표시되는 현상이 있습니다.
이때 관리자 모드에서 메뉴를 다시 한번 저장하면 사이트가 다시 제대로 보이게 됩니다.

**Comment by jhyeon1010** [comment]
제 개발환경에서 메뉴삭제, 메뉴 아이템삭제 후 홈 화면으로 접근시 말씀해주신것과 같은 에러가 발생되지 않습니다.
어떤메뉴를 삭제하셨는지등의 좀 더 자세한 정보를 주시면 다시 확인해보도록 하겠습니다.

**Comment by neoche** [comment]
구체적인 내용을 설명하기 어려워 영상으로 남깁니다.

영상에서는 다이렉트 메뉴에 주소를 작성하여 테스트했지만 게시판이나 페이지로 해도 같은 현상입니다.


[https://youtu.be/xioEKnthNt0](https://youtu.be/xioEKnthNt0)

**Comment by jhyeon1010** [comment]
메뉴를 처리하는 과정중 캐시처리 부분에서 문제가 있는것으로 확인되었습니다.
동영상으로 보여주신 내용은 다이렉트 메뉴의 주소등록 부분에서 다른 메뉴타입과 같은 주소형식으로 등록해서 발생한 오류입니다. 다이렉트 메뉴는 XE 로 구축된 사이트 외부의 다른 사이트로의 이동을 위해 존재하는 메뉴타입입니다. 예를 들면 구축된 사이트에서 XE 공홈으로 이동하는 메뉴를 추가하고자 하는 경우,  다이렉트 메뉴를 생성하고, 메뉴 주소영역에  `http://xpressengine.io` 처럼 등록 하셔야 정상작동 하게 됩니다.
이 부분도 사용자의 혼돈이 있을수 있어 보여서 안내메세지를 추가하는 등의 처리를 하도록 하겠습니다.

캐시 오류 부분은 최대한 빠르게 수정하도록 하겠습니다.
