### ISSUE TITLE
alice 테마 로그인 버튼 동작 안하는 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#335]
엘리스 테마에서 로그인 버튼에 링크가 작동하지 않는것 같습니다.

새로 설치한 XE3 에서  /board1 페이지에서 안되네요. 메인페이지는 동작됩니다.

**Comment by khongchi** [comment]
https://github.com/xpressengine/plugin-alice/commit/6ede6e5a7854c50406add7234b8e8f94d0936f86에서 해결함.
