### ISSUE TITLE
게시판 스킨 설정 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#336]
기본 게시판 스킨은 설정을 지원하지만 
게시판 설정 > 스킨설정 에서 표시되지 않는 오류

![error7](https://cloud.githubusercontent.com/assets/5836237/20088021/bf3164a2-a5c0-11e6-93c2-4558a258545e.png)

**Comment by khongchi** [comment]
https://github.com/xpressengine/plugin-board/commit/25a1dd81d91bfcaefd5dfe6630d869beab4fc4aa에서 해결함.
