### ISSUE TITLE
이용약관, 개인정보 보호 정책 링크 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#337]
https://xpressengine.io/termOfUse
https://xpressengine.io/privacyPolicy

관련 링크가 깨집니다. 

<img width="504" alt="error8" src="https://cloud.githubusercontent.com/assets/5836237/20094293/efc77c78-a5e3-11e6-8586-1328713feb2d.png">

**Comment by khongchi** [comment]
#349 에서 처리
