### ISSUE TITLE
nginx rewrite configuration guide 제공

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#34]
nginx 웹서버를 사용하는 사용자들을 위하여 nginx용 config의 가이드를 제공할 필요가 있음.

**Comment by ibin79** [comment]
.env 등의 접근을 막기 위해 빠른 제공이 필요해 보입니다.

프로젝트에 포함된 .htaccess 를 분석하여 nginx 설정을 만들어봤는데, 보안상 누락된 항목은 없는지 궁금하네요.

https://gist.github.com/ibin79/c027285c8058e707fa95


추신) 문서 작업에 앞서 nginx 설정을 가칭 .nginx.example 파일로 프로젝트내에 포함시키면, 지속적으로 보완 해나가기 편리하리라 생각됩니다.

**Comment by ibin79** [comment]
XE1 설치시 nginx rewrite 설정을 구글링을 통해 찾아다녔던 경험이 있어 제안드린 방식인데요.

프로젝트내에 nginx 설정 예제를 포함한 사례를 찾았으니 참고해주세요.

https://github.com/magento/magento2/blob/develop/nginx.conf.sample

**Comment by khongchi** [comment]
네 제안 감사합니다. 참고하도록 하겠습니다.
nginx 설정 예제파일은 곧 프로젝트에 추가할 예정입니다.

**Comment by khongchi** [comment]
기본 설정

```
    location ~ (\.)(php|html?|back?|log?)$ {
        return 403;
    }

    location / {
        # First try and load files from the public folder, if they don't exist
        # then send the request through to laravel
        try_files $uri /index.php?$query_string;
    }
```

위의 기본설정과 함께 여러 파일/디렉토리에 대한 세밀한 설정은 이 필요함.

세밀한 설정은 .htaccess 파일을 포팅해야 함.
https://github.com/xpressengine/xpressengine/blob/master/.htaccess
