### ISSUE TITLE
개인정보 보호정책 페이지 주소

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#349]
개인정보 보호정책을 관리자에서 등록했는데.. 어디 페이지에서 볼 수 있는지 알수 없어서 문의드립니다.

관리자에서 입력후 어디로 링크를 연결해야 하는지 알려주세요.

**Comment by khongchi** [comment]
https://github.com/xpressengine/xpressengine/commit/237c4ec5a3b4ff4c4efb1759fc03d47e57063ec5 에서 해당 페이지를 생성했습니다. 아래와 같이 사용하시면 됩니다.

개인정보 보호정책: `route('policies.privacy')`
사이트 이용약관: `route('policies.terms.service')`

고민해보니, 아래와 같은 이유로 위의 두 페이지를 XE에서 자체적으로 제공하는게 좋은지 의구심이 듭니다.

- 최근 사이트들의 경우, 정책 안내 페이지가 위의 두가지보다 더 많을 수 있습니다. (예: naver: http://www.naver.com/policy/service.html)
- 회원가입시 동의를 위해 출력되는 형식(기본적으로 text에 충실한 형식)과 위의 페이지에서 출력되는 형식(완전한 페이지를 html로 작성한 형식)이 상이할 수 있습니다.
- 사이트 관리자가 자체적으로 정책 안내 페이지를 제작(페이지 플러그인 사용)하여 등록하는 방식으로 충분히 이 이슈를 해결 가능.
