### ISSUE TITLE
마리아DB10.1 에서의 설치 문제.

### ISSUE THREAD

**Issue by san0123** [xpressengine/xpressengine#351]
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter ta
  ble `xe_files` add unique `findKey`(`disk`, `path`, `filename`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

SSH 설치 웹설치 동일하게 에러가 납니다.
innoDB 사용을 강제로 disable 시킨 상태 인데 (my.cnf    skip-innodb  옵션) 
unique key 로 사용되는 path컬럼의 키값 길이varchar(255)가 너무 긴거 같은데
myisam은 포기하는 부분 인가요?

**Comment by akasima** [comment]
네. myisam 은 제공안하는 것으로 하고 있습니다. 
지원 안하는 첫번째 이유가 위에 언급된 문제 때문이긴 했습니다. myisam 을 지원해야 하는 이유에 대해서는 깊이 고민하지 않고 있습니다.

**Comment by san0123** [comment]
innoDB는 서버단에서 하나의 파일 ibdata 로 운영이 되고 관리 및 백업 문제 때문에
웹호스팅 서비스군 에서 innoDB를 허용치 않는 경우가 많습니다.

고민을 하지 않는다고 하셨는데 최소 클라우드 서비스
즉 서버 사용자군을 타겟으로 개발 한다면 초보자가 쓰기 쉬운 툴은 아니란 소리군요. 'ㅅ'a
최소한 서버에 대해 뭔가 알아야 쓸수 있을테니 말이죠.

소규모가 되고 사용자가 늘어야 대규모 서비스로 발전을 할텐데.. 소규모 사용자를 고려하지 않는게 과연 옳은 방향일까 싶네요.

**Comment by akasima** [comment]
지적하신 `웹호스팅 서비스군 에서 innoDB를 허용치 않는 경우가 많습니다.` 에 대해서 알고있지 못했습니다.
이 문제를 어떻게 다뤄야 할지 좀더 논의해보겠습니다.

**Comment by akasima** [comment]
MyISAM 으로 설치가 가능하도록 수정하는것으로 수정하기로 협의 되었습니다.
만약 MyISAM 으로 설치하는데 필요한 수정사항이 varchar 길이를 줄여서 해결된다면 우선 그 수정은 처리하기로 했습니다.

다만 XE3는 공식적으로 InnoDB 만 지원하는 지금의 정책은 이어갈 생각입니다. 코드상에 트랜잭션을 사용한 코드들이 있는데 이 부분이 MyISAM을 사용할 경우 어떤 동작을 할지 알 수 없으며 MyISAM 사용을 위해 관련 코드를 수정할 계획은 없습니다.

**Comment by san0123** [comment]
빠른 피드백 감사드립니다. 
기존에 InnoDB 트랜젝션을 이용하여 UNDO하는 부분을 지원 하는 솔루션은 없었는데.. 그런 기능이 계획되어 있었군요 'ㅅ'a

물론 path 가 그리 길어 질까 생각이 들린 합니다만..
XE3 에서 사용되는 utf8 의 경우 최대 6Byte 를 사용하기 때문에 varchar(166) 정도 까지만 지정이 됩니다.
utf8mb4 같은 경우 4Byte 이기 때문에 varchar(200) 까지 되구요. 'ㅅ'a
좋은 방향으로 발전해 갔으면 좋겠습니다.

**Comment by kijin** [comment]
MySQL과 MariaDB의 utf8은 글자당 최대 3바이트로 인코딩되므로 767 ÷ 3 = 255자까지 인덱스를 걸 수 있습니다. 대부분의 어플리케이션들이 varchar 컬럼 길이를 255자 이하로 하는 이유가 이것이고요.

최근에는 기본값이 utf8mb4로 되어서 나오는 경우도 많은데, 이 때는 글자당 최대 4바이트로 인코딩되므로 767 ÷ 4 = 191자까지 인덱스를 걸 수 있습니다. 최신 버전의 우분투 및 MariaDB 호환성을 고려한다면 모든 varchar 컬럼은 191자 이하로 제한하는 것이 바람직합니다.

이론적으로는 5~6바이트로 인코딩되는 문자도 있을 수 있으나, 이 대역은 유니코드 표준에서 제거하기로 몇 년 전에 결정이 났으니 신경쓰지 않아도 됩니다.

대부분의 RDBMS는 긴 컬럼의 앞부분 몇 글자만 인덱스 처리하는 기능을 갖고 있으므로, 꼭 255자까지 지원해야 하는 컬럼이라면 앞부분 191자만 인덱스를 걸어도 전체에 인덱스를 거는 것과 99.9% 동일한 효과를 얻을 수 있습니다.

**Comment by akasima** [comment]
https://github.com/xpressengine/xpressengine/blob/master/migrations/StorageMigration.php#L38

https://github.com/xpressengine/xpressengine/blob/master/migrations/TranslationMigration.php#L29

이 두개 unique 를 제거해야 가능합니다. unique 키를 없애고 코드 레벨에서 처리해도 될것 같은데 검토가 필요합니다.
MyISAM 지원(또는 사용하는것)이 XE3에서 공식적으로 지원하지 않는 것이지만.. 가능하다면 설치 정도는 될 수 있게 하려고 합니다. unique 키를 제거하는것이 시스템 적으로 문제가 있다면 더이상 고민하지 않고 처리하지 않도록 하겠습니다.

**Comment by kijin** [comment]
특정 컬럼만 문자셋을 utf8 또는 latin1으로 지정하는 방법도 있습니다. 서버측 파일 경로나 임의 생성한 고유키 등 utf8mb4 문자셋이 필요하지 않은 데이터라면 이 방법이 가장 좋습니다. 원래 이런 용도로 쓰라고 MySQL에서 지원하는 기능이니까요. 유니크 인덱스를 희생할 필요도 없습니다.

**Comment by akasima** [comment]
@kijin 님이 제안주신 관련 컬럼의 문자셋 변경으로 해결했습니다.

이 이슈를 처리하면서 생각한게 있는데요. 'MyISAM 공식적으로 지원하지 않는건데 이렇게까지 해야하나..' 였습니다.
이번은 설치 가능한 상태로 구조를 변경했지만 테이블이 추가되거나 할 때는 이문제는 또 발생할 것입니다.
저희는 데이터베이스 테이블을 관리할 때 이러한 문제를 고려하지 않기로 했습니다. 

이슈를 해결하는데 도움주신 @san0123, @kijin 님께 감사드립니다.  :)

**Comment by kijin** [comment]
@akasima 해결되었다니 다행입니다.

그런데

> 이 이슈를 처리하면서 생각한게 있는데요. 'MyISAM 공식적으로 지원하지 않는건데 이렇게까지 해야하나..' 였습니다.

질문이 틀린 게 아닐까요? 현실적으로 InnoDB를 사용할 수 있는 호스팅 환경이 극히 드문 상황에서 MyISAM을 지원하지 않는다면 스스로 시장점유율을 포기하는 결과를 낳지 않을까 걱정이 됩니다. 또한 지나치게 큰 인덱스는 성능에도 악영향을 주니, InnoDB에서 대용량 복합 인덱스를 지원한다는 이유만으로 마구 쓰는 것도 바람직해 보이지는 않습니다.

**Comment by san0123** [comment]
픽스된 부분을 적용하니 에러난 부분은 넘어 갔는데 아래와 같이 인스톨에서 에러가 나네요 'ㅅ'a

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `xe3_board_favorites` add index `board_favorites_targetid_userid_index`(`targetId`, `userId`))

PDOException in Connection.php line 390: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by akasima** [comment]
게시판 플러그인에서 발생하는 문제를 더 점검해야겠네요. slug 테이블에 문제가 좀 있을것 같습니다. 제목 길이를 어떻게 제한할지 더 고민히야겠네요.

**Comment by akasima** [comment]
@san0123 인스톨할 때 XE3 core 는 develop 브랜치로 하셨겠지만..
board 플러그인은 따로 설정안하고 인스톨 하셨죠??

이 이슈에서 처리하고 있는 인스톨 관련 문제에 대해서 처리한 board 플러그인 이슈가 아직 배포되지 않았습니다.

정확한 테스트를 하기 위해서는 board 플러그인을 develop 브랜치로 바꾸고 테스트해야합니다.
