### ISSUE TITLE
심플 페이지에서 img 태그가 안먹히는 문제

### ISSUE THREAD

**Issue by neoche** [xpressengine/xpressengine#360]
심플 페이지에서 페이지 작업 시 [파일첨부]가 아닌

호스팅에 있는 이미지를 <img src> 태그로 불러오면 이미지가 불러지지 않습니다.

확인 부탁 드립니다.

[https://xpressengine.io/qna/Simple-Pages](https://xpressengine.io/qna/Simple-Pages)

**Comment by akasima** [comment]
이미지 파일을 어느 경로에 놓고 링크를 걸었었는지 알 수 없으나 스크린샷 디렉토리에 넣고 할 경우 해결 되셨다고 합니다.
