### ISSUE TITLE
XE3을 하위 폴더에 설치시 사이트맵 링크 문제

### ISSUE THREAD

**Issue by wincomi** [xpressengine/xpressengine#361]
localhost/xe3 처럼 XE3을 하위 폴더에 설치시 아이템 링크(파란색 링크)가 /xe3/board1가 아닌 루트에 설치된 것처럼(/board1)로 걸려져있습니다.
![2016-12-01 11 59 48](https://cloud.githubusercontent.com/assets/1822540/20798465/456950fc-b822-11e6-80d6-1c04821a734b.png)

**Comment by jhyeon1010** [comment]
해당 링크가 '/' 를 고정으로 붙이도록 작성되어 있었습니다. 현재 서비스의 루트를 확인하여 링크에 적용되도록 수정해야 할것으로 보입니다.

**Comment by seungmanchoi** [comment]
사용자가 서브디렉토리를 사용할 경우 frontend에서의 처리가 누락되어 있는 상태로 
root를 기준으로 트리에 노출되도록 수정하였습니다.
