### ISSUE TITLE
아이폰6S+ 입니다. 사진업로드가 안됩니다.

### ISSUE THREAD

**Issue by oilugi** [xpressengine/xpressengine#362]
pc 에서는 잘됩니다.
아이폰에서는 사진선택까지는 잘되는데 
업로드 진행이 안됩니다.
xe3 qna 에 적었다가 
답변보고 여기 이슈로 남깁니다.

**Comment by seungmanchoi** [comment]
현재 개발되고 있는 버전에서는 해당 문제가 발생되지 않아 확인중에 있습니다.
이미 해결된 이슈로 보이긴 합니다만..
bootstrap/app.php 에 표시되어 있는 버전 정보를 코멘트로 남겨주시면 해당 이슈 확인이 빠를것 같습니다.

**Comment by khongchi** [comment]
과거 버전에서 발생한 오류로 판단하고 일단 이슈 닫도록 하겠습니다.
현재 버전(beta.9)에서 발생한 문제라면 커맨트 부탁드립니다.
