### ISSUE TITLE
관리자 페이지 메뉴 글자 튀어나옴 문제

### ISSUE THREAD

**Issue by wincomi** [xpressengine/xpressengine#365]
![2016-12-05 10 18 28](https://cloud.githubusercontent.com/assets/1822540/20886322/ded2671a-bb38-11e6-940a-d680ba002059.png)
**Multi-language settings**처럼 관리자 메뉴의 글자가 메뉴 너비를 초과할 경우 글자가 넘치는 문제가 있습니다. text-overflow 등의 처리가 필요해보입니다.

**Comment by khongchi** [comment]
글자가 공간을 벗어날 경우 말줄임 처리를 하고, `title`이나 `tooltip`을 이용하면 좋을 것 같습니다.

**Comment by khongchi** [comment]
https://github.com/xpressengine/xpressengine/commit/6e7160e661f10d0edc42bae5eb419c7f001a1889 에서 처리되었습니다.
