### ISSUE TITLE
멀티사이트를 지원할 계획은 없나요?

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#367]
XE1의 homepage 모듈은 의도는좋았지만 지속적으로 가상사이트를 염두한 모듈들이 나오지않아

문제가꽤많았던걸로 기억합니다.

하지만 웬만큼 수정해서 쓰기에는 좋았지요.

XE3에서는 좀더 완벽한 가상사이트기능이 나오지않을까 기대를했는데 지원할계획이 없는건지요?

**Comment by akasima** [comment]
멀티사이트 지원 계획은 있습니다.
menu 에서 siteKey 컬럼이나 config 에서 site 설정 값의 경우가 이를 대비한 것들입니다.

하지만 멀티사이트에 대한 처리는 하지 않고 있습니다.
멀티사이트 보다 더 기본적인 기능들을 더 처리한 후에 플러그인으로 지원할 수 있는지 해보게 될것 같고 멀티사이트 플러그인 개발 일정은 잡혀있지 않습니다.
