### ISSUE TITLE
사이트맵에서 메뉴 순서변경(이동) 문제

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#369]
아래 이미지와 같이 두개의 메뉴가 있을 때, 하단의 메뉴를 상단으로 이동시 메뉴가 정상적으로 이동처리가 되지만,
상단의 메뉴를 하단으로 이동시 메뉴가 정상적으로 이동되지 않습니다.

![image](https://cloud.githubusercontent.com/assets/1772843/21215423/84a9a722-c2e4-11e6-972b-2f617233a59b.png)

**Comment by jhyeon1010** [comment]
두가지 경우 모두 테스트 해보았으나 정상적으로 동작하는 것으로 보입니다. 테스트는 master 브랜치의 소스로 신규설치하여 실행하였습니다. 개인설정에 차이나 문제가 있는지 확인바랍니다.

**Comment by khongchi** [comment]
#370 이슈로 통합
