### ISSUE TITLE
사이트맵에서 메뉴 depth 변경시 설정 갱신이 잘 안 되는 문제

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#370]
![image](https://cloud.githubusercontent.com/assets/1772843/21216133/69318632-c2e8-11e6-9a5b-d85023147be4.png)

위 이미지에서 `게시판` 메뉴를 `홈` 메뉴의 자식으로 이동시킨 후, 다시 원위치로 원상복귀시킬 경우 문제가 발생하는데,
게시판에 적용되는 테마가 제대로 적용되지 않고, `홈`메뉴의 자식 메뉴로 설정돼 있는 상태에서의 테마가 적용되는 문제가 있습니다.

config 테이블을 살펴보니 아래와 같이 게시판 설정(`menu.318301e3.4105255f.3e18d5a5`)의 경로가 제대로 원상복귀(`menu.318301e3.3e18d5a5`) 되지 않는 문제를 발견하였습니다. 

![image](https://cloud.githubusercontent.com/assets/1772843/21216192/c5f952b4-c2e8-11e6-85ef-e6a6d9b9e247.png)

**Comment by jhyeon1010** [comment]
#369 이슈와 마찬가지로 정상동작하는 것으로 보입니다. 다시 확인 바랍니다.

**Comment by khongchi** [comment]
https://youtu.be/20YnUCrv54s

위 재현동영상을 보면,

1. `게시판` 메뉴아이템을 `홈` 메뉴아이템 자식depth로 이동 -> `게시판`의 테마가 `홈`의 테마 설정을 상속받음(정상)
2. `게시판` 메뉴아이템을 `홈` 메뉴아이템과 동일 레벨depth로 이동 -> `게시판`의 테마가 계속 `홈`의 테마 설정을 상속받음(오류)
3. `홈` 메뉴아이템을 `게시판` 메뉴아이템 하위로 이동 -> 순서변경됨(정상)
4. `게시판` 메뉴아이템을 `홈` 메뉴아이템 하위로 이동 -> 순서변경됐다고 출력되지만 새로고침 하면 변경되지 않았음.

**Comment by jhyeon1010** [comment]
재차 테스트 해보았으나 #369 에서 말한바와 같이 정상동작하는 것으로 보입니다. 설치한 xe 소스가 최신상태인지, 또는 최신 소스로 설치 후 같은 문제가 발생하는지 확인 바랍니다. 제가 테스트한 대상은 master 브랜치로 신규 설치한 소스입니다.
