### ISSUE TITLE
CKEDITOR 사용시 긴 글 등록 에러

### ISSUE THREAD

**Issue by iamkt79** [xpressengine/xpressengine#374]
ckeditor 에서 태그를 포함한 매우 긴 글을 등록할 경우 서버에 요청중입니다 메시지가 나오다 등록이 되지 않고 에디터 화면으로 돌아옵니다. 공홈 게시판에서도 같은 문제 발생 확인했습니다.
xpresseditor 에서는 문제 없이 등록이 되고 ckeditor 이용시에만 해당 문제가 발생합니다.

**Comment by akasima** [comment]
문제가 된 글을 developers@xpressengine.com 으로 전달해 주시면 테스트하는데 많은 도움되겟습니다.

**Comment by iamkt79** [comment]
xe저장소로 옮겨 등록하겠습니다.
