### ISSUE TITLE
artisan으로 인스톨시 데이터베이스 커넥트 에러

### ISSUE THREAD

**Issue by Canto** [xpressengine/xpressengine#376]
```cmd
artisan xe:install
```
커멘드로 인스톨을 진행시 데이터베이스 설정 입력 후 
```
[ERROR] Connection failed!! Check Your Database!
```
에러가 나옵니다.
혹시 설정입력을 잘못 했나 싶어서 
mysql로 해당 포트 / 아이디 / 패스워드 / 데이터베이스명 을 확인해본결과 특별이 문제는 없었습니다.
아마 로컬 환경(MAMP)에서 설치를 하다보니 정상적으로 Mysql을 접속 못해서 나타나는 문제인거 같은데 
artisan 으로 인스톨시 환경설정 체크를 진행하는 스크립트쪽 PATH를 알 수 있을까요?

**Comment by jhyeon1010** [comment]
로컬에 설치된 mysql 에 접근시 호스트를 `localhost` 로 사용시 설정에 따라 접근이 불가능할 수 있습니다.
만약 인스톨과정에서 mysql 호스트를 `localhost` 로 작성하셨다면 `127.0.0.1`로 작성하여 인스톨을 시도해보시기 바랍니다.

**Comment by Canto** [comment]
@jhyeon1010 감사합니다 아이피로 인스톨 시도해 봣더니 문제 없이 인스톨 되었습니다
