### ISSUE TITLE
댓글에서 등록한 글의 스타일 적용 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#393]
글을 굵게 표현하거나 소스 코드 작성을 위한 기능을 사용하더라도 생각하것처럼 표현되지 않습니다.
작성된 글을 표현할 때 에디터 스타일이 적용되지 않는 문제가 있는것 같습니다.

![2017-02-20 10 42 23](https://cloud.githubusercontent.com/assets/5836237/23109130/5d0309c6-f759-11e6-9719-d5431af84f39.png)

**Comment by akasima** [comment]
https://xpressengine.io/qna/%EC%BD%94%EB%93%9C-%EC%8A%A4%EB%8B%88%ED%8E%ABCode-Snippets-%EC%A0%81%EC%9A%A9-%EC%97%90%EB%9F%AC

이 문제도 같이 확인바랍니다.

**Comment by seungmanchoi** [comment]
@akasima css bold관련 내용 확인하였는데 맥OS chrome에서 보면 bold가 적용된 상태이나 육안으로 잘 확인이 안되는 상태인걸로 확인하였습니다. 다른 브라우저로 확인시 정상적으로 적용되는 상태입니다.

**Comment by seungmanchoi** [comment]
코드 스니펫 이슈 css셀렉터가 꼬여 있어서 수정함 

2e04231b208ea636beb86f87ed0bd4b25bbf2d81
