### ISSUE TITLE
procMemberDeleteSavedDocument 권한체크

### ISSUE THREAD

**Issue by kdps** [xpressengine/xpressengine#398]
if(!Context::get('is_logged')) return new Object(-1, 'msg_not_logged');
    $logged_info = Context::get('logged_info');
 
    $document_srl = (int)Context::get('document_srl');
    if(!$document_srl) return new Object(-1,'msg_invalid_request');
    // Variables
    $oDocumentController = getController('document');
    $oDocumentController->deleteDocument($document_srl, true);

권한체크없이 바로 글을 삭제함

**Comment by bnu** [comment]
https://github.com/xpressengine/xe-core/issues/2038
