### ISSUE TITLE
게시글 작성시 bold속성이 적용되지 않는 이슈

### ISSUE THREAD

**Issue by seungmanchoi** [xpressengine/xpressengine#407]
나눔고딕 관련 폰트 사용시 맥용 크롬 브라우저에서 font-weight가 적용되지 않는 문제가 있습니다.
font-family를 Ngothic-Bold로 적용하면 bold가 적용이 되는데 해당 내용으로 대체 될수 있는 내용인지 확인이 필요하고 개선이 되어야 할 것 같습니다.
게시판에서 글쓰기를 할 경우 strong태그를 사용한 후 확인하면 재현 가능합니다.

**Comment by akasima** [comment]
문제 되던 이슈가 Mac 크롬 브라우져에서 bold 처리가 안되는 것이었습니다.
타 사이트에서 bold 처리가 정상적으로 되는것을 확인하고 font-family 를 확인했을 때 `Apple SD Gothic Neo`를 앞에 둔것으로 보였습니다. 

font-family 제일 앞에 `Apple SD Gothic Neo`을 추가 할 경우 mac 에서는 `나눔고딕` 글꼴을 볼 수 없는 문제가 생기겠지만 `Apple SD Gothic Neo` 폰트로 보여주더라도 큰 이슈는 없을 거라고 생각됩니다.

**Comment by bnu** [comment]
맥용 크롬 56버전에서 해당 증상을 확인함.
57로 업데이트하니 해당 증상이 재현되지 않았습니다.
57.0.2987.98
canary 59.0.3037.0에서도 정상 표시되는 걸로 확인 함.
