### ISSUE TITLE
XE3에서 플러그인 설치할 때 필요한 파일 쓰기권한 및 COMPOSER_HOME 변수 체크

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#418]
./vendor, ./composer.lock 등 컴포저에서 사용하는 파일의 권한 체크 및 COMPOSER_HOME 환경변수 체크가 필요함.

**Comment by 1Sam** [comment]
저는 늘... 직접 다운 받아서 덮어쓰기하였는데...

**Comment by khongchi** [comment]
@1Sam 직접 다운받는 방법으로 하셨다면 다운받은 플러그인 디렉토리에 들어가서 수동으로 `composer update`를 반드시 실행해주셔야 합니다. ^^;
