### ISSUE TITLE
설치오류

### ISSUE THREAD

**Issue by DexterPark** [xpressengine/xpressengine#419]
메뉴얼대로 터미널에서 
"php -r "copy('http://start.xpressengine.io/download/installer', 'installer');" && php installer install"
로 실행하여 설치를 하려는데 오류가 나네요...

http://start.xpressengine.io/latest.zip 파일이 없는듯 합니다...

**Comment by jhyeon1010** [comment]
변경된 installer 파일 배포과정에 문제가 있었던것 같습니다.
현재 수정하여 배포처리 하였으니 재시도하시면 정상적으로 설치가 진행될것 입니다.
