### ISSUE TITLE
업데이트 때 표시되는 에러 메시지 'packages.json file could not be downloaded'

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#422]
<img src="http://i.imgur.com/L3SnjgV.png">
http://imgur.com/a/eTNjj

**Comment by khongchi** [comment]
beta.14부터 자료실 주소가 xpressengine.io에서 store.xpressengine.io로 변경되었습니다.
무슨 이유에서인지 변경된 사항이 제대로 적용되지 않은 것 같은데요.

`config/xe.php` 파일에 `plugin > packagist > url` 항목에 지정된 주소를 사용하도록 되어 있습니다.
이 주소는 어떻게 지정되어 있나요?

또, ``config/production/xe.php` 파일에 이 주소와 관련하여 별도로 지정한 값이 있나요?
