### ISSUE TITLE
에디터 버튼 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#425]
링크를 추가하려고 할 때나 이텔릭 글자 체를 사용하려고 할 때 오류가 있습니다. (다른 버튼은 테스트 하지 않음)

이텔렉 글자 체는 두꺼운 글씨로 처리되고 링크는 어떤 기능인지 모를 모달 박스가 출력됩니다.

![2017-03-20 1 47 24](https://cloud.githubusercontent.com/assets/5836237/24088944/ed22e2c6-0d73-11e7-88f9-e6abf2f6a441.png)

**Comment by seungmanchoi** [comment]
sprite이미지 변경 및 css 백그라운드 포지션 변경으로 이슈 수정
