### ISSUE TITLE
관리자 페이지에서 itemUrl 설정 관련

### ISSUE THREAD

**Issue by mintplo** [xpressengine/xpressengine#426]
itemUrl은 1-depth 밖에 설정 못하는건가요?

상-하위 구조로 메뉴를 설정해도 안되고
itemUrl 입력창에도 1-depth로 입력해도 안되는것 같아서요.

**Comment by akasima** [comment]
1-depth 메뉴라는게 아래와 같은 모양을 얘기하는 건가요?
![2017-03-23 9 58 13](https://cloud.githubusercontent.com/assets/5836237/24227257/431efb64-0faf-11e7-89e1-246b505b8094.png)

**Comment by mintplo** [comment]
@akasima 네 맞습니다. 메뉴 논리 구조가 상(A)-하위(B)로 구성하면 라우팅은 당연히 base_url/A/B 로 될거라 생각했는데 그렇게 되지 않아 단순 궁금증으로 이슈 남겨보았습니다.

**Comment by akasima** [comment]
라우팅 구성할 때 이슈가 있었던 것으로 기억됩니다.

**Comment by mintplo** [comment]
넵. 답변 감사합니다.
