### ISSUE TITLE
비밀번호 찾기 질문/답변 에서 답변이 보이는 이슈

### ISSUE THREAD

**Issue by clamo** [xpressengine/xpressengine#427]
어드민으로 회원정보를 볼 경우,

"비밀번호 찾기 질문/답변" 에서 회원님들이 남긴 "답변" 보이는 이슈가 있습니다.

어드민이 회원님들의 답변을 봐도 시스템상 이득은 없을 듯 싶습니다. 오히려 프라이버시 침해 문제가 되지 않나요?

시스템 제어에 꼭 필요한 기능이지 않는이상엔 암호화 처리 + 어떤 role 이라도 자신 이외에는 visibility 가 없었으면 합니다.

**Comment by khongchi** [comment]
이곳은 xe3 이슈게시판입니다.  xe1의 이슈라면 아래 링크로 이동해서 이슈를 등록해 주시기바랍니다
 https://github.com/xpressengine/xe-core/issues
