### ISSUE TITLE
관리자 페이지에서 메뉴 등록시 사라지는 현상

### ISSUE THREAD

**Issue by HanbitGaram** [xpressengine/xpressengine#428]
개발하시는데 고생 많습니다.

다름아니라, XE3로 제작 중인 사이트에서 해당 이슈가 발견되어 안내드립니다.
XE3 관리자 페이지 사이트맵 사이드메뉴 -> 사이트 메뉴 편집에 메뉴 등록시 다이렉트 링크 부분에 링크를 자바스크립트로 등록한 경우, 

http://imgur.com/9FcgvCi

위 링크와 같은 현상이 발생하고 있습니다.
이에 확인 부탁드립니다.

감사합니다.

**Comment by jhyeon1010** [comment]
저희는 메뉴의 링크부분에 자바스크립트를 사용하는 것을 허용하지 않고 있습니다.
링크에서 보이는 현상은 자바스크립트를 작성하실때 사용한 `'` 때문에 데이터가 정상적으로 전달되지 않아 
메뉴목록을 표현하지 못하는 것으로 보입니다. 메뉴페이지는 escape 처리를 통해 화면 표현은 되게
변경하도록 하겠습니다.
