### ISSUE TITLE
이미지 태그 포함시, 게시판 등록 에러

### ISSUE THREAD

**Issue by ibin79** [xpressengine/xpressengine#43]
이미지 업로드 등으로 인해, 본문내에 이미지 태그가 포함된 경우 에러가 발생합니다.

### 에러

```
[2015-11-27 13:02:19] local.ERROR: 
exception 'ErrorException' with message 
'Directory /home/xe3/public/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777'
 in /home/xe3/public/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php:278
```

### 임시 대응

HTMLPurifier 에서 사용할 캐시 디렉토리를 만들어주고,

```
mkdir -m 777 /home/xe3/public/storage/app/htmlpurifier
```

config/purifier.php 설정에서 캐시 경로를 직접 입력해주니, 등록됩니다.

```
    #'cachePath' => null,
    'cachePath' => '/home/xe3/public/storage/app/htmlpurifier',
```

따라서 HTMLPurifier 캐시 디렉토리 관련 정리가 필요해 보입니다.

**Comment by akasima** [comment]
게시판에서 에디터에 파일 첨부 후 글 등록할 때 에러가 발생하지 않아 확인하지 못했습니다.
어떤 경우에 에러가 발생하는지 더 확인해 봐야겠습니다.

**Comment by ibin79** [comment]
`이미지 첨부`를 해보시면 됩니다.

즉, `<img` 등의 이미지 태그가 포함되어, HTMLPurifier 가 실행되는 시점에서만 에러가 발생합니다.

**Comment by akasima** [comment]
@ibin79 :+1:  감사합니다. 문제되는 분분 확인해서 수정했습니다.
제 웹서버 설정이 문제가 있네요 ;;
