### ISSUE TITLE
페이스북 로그인 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#432]
페이스북 로그인을 사용하려고 하는데 안되네요.
공식사이트 로그인도 동작하지 않습니다.

페이스북 API가 업데이트 된것 같습니다. https://gs.saro.me/#!m=elec&jn=885

**Comment by khongchi** [comment]
아래 커밋에서 처리하였고, xpressengine/plugin-social_login 0.9.10 버전에 적용되었습니다.
https://github.com/xpressengine/plugin-social_login/commit/86a95c7a22a55db7a93502b07faa26037ec1e643
