### ISSUE TITLE
게시판 <title> 설정 기능

### ISSUE THREAD

**Issue by mintplo** [xpressengine/xpressengine#433]
게시판에 들어가면 SEO 관련 메타 태그는 올바르게 설정이 되어있는데
정작 <title>은 손대지 않는것 같습니다. <title>정보를 설정하고 싶은데 관리자 페이지에서는 제공하지 않는듯하고
코드로 처리하자니 defaultSkin을 손대야 하는 것 같아서 일단 이슈로 올려봅니다.

**Comment by mintplo** [comment]
XeFrontend::title을 중복으로 호출하여 사용하면 우선순위 처리가 어떻게 되는건가요?

**Comment by akasima** [comment]
현재의 타이틀에 상품 이름을 붙일 때 아래와 같은 코드로 처리했습니다.
```
XeFrontend::title(sprintf(
            '%s - %s',
            $data['product']->productName,
            xe_trans(XeFrontend::output('title'))
        ));
```

게시판에 제목을 설정할 경우 어떻게 처리되는게 좋을까요?
meta title 과 `<title> </title>`을 구성 할 때 어떻게 처리하는게 좋을지 고민해 봐야겠네요.

**Comment by mintplo** [comment]
@akasima 개발자님 빠른 반영 감사합니다! 목록 페이지에 접근하면 Title 설정이 안되는것 같은데 혹시 BoardName을 타이틀로 설정하도록 하는것은 어떨까요?

**Comment by akasima** [comment]
@mintplo 검토하겠습니다.

**Comment by akasima** [comment]
@mintplo 관리자 > 설정 > 기본 설정 페이지에(_/settings/setting_) 사이트 제목 입력하는 부분이 있는데요.
여기에서 사이트 타이틀을 관리합니다. 
여기 설정한 정보가 사이트 기본 Title 로 사용됩니다.

![2017-04-12 4 03 14](https://cloud.githubusercontent.com/assets/5836237/24945281/8ea85676-1f99-11e7-8153-1ee893c5f746.png)

만약에 이 부분에 대해서 이미 알고 있었고
**사이트 타이틀**을 설정하고 게시판 설정의 **BoardName** 을 설정할 경우 
Title 태그에 사용되는 것이 
사이트 타이틀 + BoardName 이라면 수정을 검토 해볼께요.

**Comment by mintplo** [comment]
@akasima 

네 모든 페이지에서 사이트 제목만 <title>로 설정되는것 보다

페이지, 게시판 별로 저장한 이름이 타이틀로 설정되면 좋을것 같습니다.

BoardName - 사이트 타이틀이 좋을것 같습니다.
