### ISSUE TITLE
validate 메시지 개선

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#437]
컨트롤러에서 validate 에서 문제가 있을 때 리턴하는 메시지 형식에 문제가 있습니다.
```
{"categoryItemId":["The category item id field is required."]}
```
과 같은 형식으로 반환되는데 다른 exception 메시지들과 형식을 맞출 필요가 있어 보입니다.

또한 메시지에 다국어가 처리되지 않는 문제도 개선되었으면 합니다.

![2017-03-30 2 46 11](https://cloud.githubusercontent.com/assets/5836237/24489327/a5730a64-1557-11e7-8e1b-f5e7b768f03e.png)

![2017-03-30 2 46 33](https://cloud.githubusercontent.com/assets/5836237/24489331/b0de32ac-1557-11e7-857b-60b6310167fa.png)

**Comment by jhyeon1010** [comment]
response text 형식은 laravel 의 validation 을 그대로 사용하므로 변경하지 않기로 결정하였습니다.
locale 이 ko 로 지정되어진 상태에서 영문으로 메시지가 나타나는 문제는 #444 에서 처리되었습니다.

추가적으로 validation 메시지가 사용자로 하여금 수정하여 사용할 수 있도록 core 의 translation 을 이용하도록 변경되었습니다.
