### ISSUE TITLE
페이지에서 이미지 첨부시, URL에서 /storage 사용하는 문제

### ISSUE THREAD

**Issue by ibin79** [xpressengine/xpressengine#44]
### 페이지 편집화면, 미리보기에서의 이미지 URL

/page/file/source/84c51fd0-75bf-4dd6-9d98-d2365ccb1f0f

### 실제 페이지에서의 이미지 URL

/storage/app/attached/b2/87/spill_800x800_979d4219120e985e06030ea355fc885b88b39417

보안상 웹서버에서 /storage 디렉토리 접근을 차단했으므로 페이지에서만 이미지가 보이지 않습니다.  (게시판은 문제없음)

참고) 제 nginx 설정 - https://gist.github.com/ibin79/c027285c8058e707fa95

**Comment by akasima** [comment]
nginx 설정할 때 배포에 포함된 htaccess 참고 바랍니다.

https://github.com/xpressengine/xpressengine/blob/master/.htaccess

storage 를 다 막으면 사용자 업로드 파일에대한 접근도 다 막기 때문에 문제가 됩니다.
htaccess 에서는 보안상 문제가 되는 storage/framework, logs, interception 별도로 설정하고 있습니다.

사용자가 업로드한 파일이 저장되는 storage/app 에 저장되는 파일의 보안문제는 업로드 시에 처리되야 할 사항이고 직접 접근은 가능해야합니다.

@ibin79 .. 이렇게 설정할 때 생길 보안상 문제가 있을까요?

**Comment by ibin79** [comment]
1. `페이지 보기` 게시판, 페이지 미리보기 등과 이미지 주소가 다릅니다.  즉 /storage 접근 제한 여부와 별도로 보더라도, 이미지 주소 단일화가 필요해 보입니다.

2. 사용자가 파일을 업로드하는 디렉토리가 웹에서 접근 가능한 경우, 오랜 시간 수많은 웹프로그램들에서 업로드 취약점 등이 발견 및 악용되어 왔습니다.  현실적으로 xe core 나 향후 나올 플러그인들에서 업로드 취약점이 100% 나오지 않는 다는 보장은 할 수 없다고 봅니다.

이러한 잠재적인 보안 취약성을 근본적으로 개선하기 위해, Laravel 에서도 웹에서 접근 가능한 public 과 나머지 디렉토리를 분리시켰는데, XE3에서는 웹호스팅을 고려한 탓인지 하나로 합쳤더군요.  따라서 그에 따른 storage 차단 등의 보안 정책이 필요하다고 생각됩니다.

**Comment by akasima** [comment]
사용자 업로드 파일 접근에 대해서 다른 CMS 들은 어떤 방식으로 처리했는지 살펴보고 결정하도록하겠습니다.

**Comment by akasima** [comment]
업로드되는 파일의 이름은 유추할 수 없는 수준으로 변경하여 사용하고 있습니다. 사용자가 임의 값을 입력해 파일에 접근하는 일은 발생하기 업렵다고 가정했습니다.

스토리지 접근의 경우 전체를 막아 놓는다면 이슈가 많이 발생할것으로 예상되고 PHP 를 이용해서 파일 access 후 다시 뿌려주는 형태는 성능에 많은 문제를 일으킬 수 있다고 결되었습니다.

보안에 취약점이 발생하는 storage 디렉토리에 대해서 웹서버에 보안설정을 개별적으로 하는게 좋겠다고 결론 냈습니다.
Storage 디렉토리를 웹에서 접근이 불가능한 위치로 옮기는 설정은 간단히 제공할 수 있지만 그로 인해 웹에서  storage 의 모든 리소스 접근할 때 php 파일에서 load 해서 다시 출력해 주는 형태는 제공할 수 없다는 결론입니다.

Storage 디렉토리 위치와 관련해서 구체적인 보안 취약점이 발생하면 다시 논의하도록 하겠습니다.

**Comment by ibin79** [comment]
@akasima 네.  XE는 기존 사용처를 보면, 업무용보단 커뮤니티 성격이 많으므로 말씀하신 성능에 우선을 두는 것이 적절한 방향이라고 생각됩니다.  자세히 검토해주셔서 감사합니다. :)
