### ISSUE TITLE
beta.15 업데이트 때 표시되는 에러 메시지 'packages.json file could not be downloaded'

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#445]
<img src="http://i.imgur.com/twxijTt.png">

beta.14 에서도 같은 문의를 했습니다. beta.15에서도 같은 에러 메시지가 표시되어 문의 드립니다.

> beta.14부터 자료실 주소가 xpressengine.io에서 store.xpressengine.io로 변경되었습니다.
> 무슨 이유에서인지 변경된 사항이 제대로 적용되지 않은 것 같은데요.
> 
> config/xe.php 파일의 plugin > packagist > url 항목에 지정된 주소를 사용하도록 되어 있습니다.
> 이 주소는 어떻게 지정되어 있나요?
> 
> 또, config/production/xe.php 파일에 이 주소와 관련하여 별도로 지정한 값이 있나요?

위 두 질문의 답을 달지 못 한채 이슈가 닫혔습니다. 
config/xe.php 에는 store.xpressengine.io 로 설정되어 있으며,
config/produnction/xe.php 에는 별도로 지정한 값이 없습니다.

**Comment by khongchi** [comment]
`storage/app/composer.plugins.json` 파일을 삭제하시면 됩니다.
코어 업데이트시 삭제되도록 코드를 추가해 두었는데 오류가 있어보입니다. 좀 더 손 보도록 하겠습니다.

**Comment by 1Sam** [comment]
storage/app/composer.plugins.json 파일을 직접 삭제하니  xe3 업데이트 시에 문제가 발생하지 않습니다. 고맙습니다.
