### ISSUE TITLE
laravel lts 버젼 확인좀 부탁드립니다. 

### ISSUE THREAD

**Issue by choiks14** [xpressengine/xpressengine#451]
[laravel 5.5 lts](https://laravel-news.com/laravel-5-5-lts)

문서에 보면 5.5가 lts로 바뀐다고 하는데 xe도 같이 5.5로 업데이트 해주시나요?

**Comment by akasima** [comment]
네 업데이트 합니다. 
XE3는 최신 LTS버전을 사용합니다.

**Comment by choiks14** [comment]
감사합니다. ^^
