### ISSUE TITLE
사이트맵 편집시 에러

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#471]
사이트맵을 하나 더 생성하고 아이템을 추가한 다음, 다른사이트맵으로 이동하면 그때부터 아이템편집도, 사이트접속도 되지않습니다. 500에러가 발생합니다.

**Comment by jhyeon1010** [comment]
메뉴를 추가하고 메뉴아이템을 새로 생성한 메뉴에 추가한 후 추가된 메뉴아이템의 편집 페이지로 이동하셨다는 말씀이신가요? `다른사이트맵으로 이동` 이 어떤것인지 잘 모르겠습니다. 좀 더 자세한 내용을 알려주셨으면 합니다.

**Comment by XisoDev** [comment]
다른사이트맵으로 이동 은 XE3 관리자화면에서의 "메뉴추가" 개념을 말합니다.

기본값으로 Main Menu 가 있고, 다른 "메뉴"를 추가한 다음 Main Menu 에있는 아이템을 추가한 메뉴로 옮기면 해당아이템의 수정화면에 접근이 불가하고 (따라서 삭제도 되지않습니다.) 사용자 화면은 500에러로 뒤덮입니다.

**Comment by XisoDev** [comment]
정확한 상황은 이렇습니다.

1. 새 "메뉴"추가
2. 새 "메뉴"에 "아이템1"추가
3. 새 "메뉴"에 "아이템1" 안에 "게시판1" 추가
4. "아이템1"을 "기본메뉴(mainmenu)"로 이동
(이단계에서 실패했지만 에러를 리턴하지않은 것 같습니다.)
5. "게시판1"을 "아이템1"과 동일한 레벨로 변경시도 실패

**Comment by jhyeon1010** [comment]
메뉴간 이동시 각 아이템의 설정링크 주소가 변경되지 않아 발생한 문제 였던것 같습니다. 
현재 상태에서는 브라우저에서 새로고침 하시면 수정페이지로 접근 가능할 것으로 보입니다.

**Comment by XisoDev** [comment]
브라우저에서의 새로고침도, 캐시제거도, DB에서의 관련 id를 모두찾아 메뉴제거도해보았지만 복원되지않았습니다.

**Comment by jhyeon1010** [comment]
아이템 이동 처리시에 하위의 자식 아이템들의 메뉴 id 값 변경문제가 있었습니다. 수정 사항은 다음 배포때 포함되어질 것입니다.

**Comment by seungmanchoi** [comment]
사이트맵 편집 오류 수정. 정상동작 확인
