### ISSUE TITLE
확장필드 추가 불가

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#473]
board 모듈의 확장필드 추가가 불가능합니다.

config/production/app.php 의 debug를 true로 변경했지만 관리자에게 문의하라는 내용 이외의 메세지는 없습니다.

**Comment by akasima** [comment]
어떤 확장필드를 추가했나요? 제 개발 환경에서는 Category, Number 확장필드는 오류 없이 추가 됐습니다.

**Comment by XisoDev** [comment]
text 와 cellphone, address 모두 불가능했습니다.

**Comment by akasima** [comment]
그것도 제 개발환경에서는 되네요.. 
설치된 서버 환경이나 웹사이트를 직접 보고 싶습니다. 
가능하다면 developers@xpressengine.com 으로 메일 주시면 좀더 확인하겠습니다.

**Comment by XisoDev** [comment]
확장변수의 에러증상입니다.
https://youtu.be/5yLfZr5u8qQ

메세지가 없을때도있고, text의경우는 대부분 에러메세지가 출력됩니다. (시스템 관리자에게 문의하라는..)

페이지가 열려있는상태에서 같은조건으로 add를 눌러 다시작성하기를 여러번 시도하면 등록이 되긴됩니다...

자세한건 영상을 보시면 알수있습니다.

**Comment by akasima** [comment]
라벨을 입력 안해서 그런가보네요 ;;

수정하겠습니다.

**Comment by XisoDev** [comment]
뒷부분을보시면.. 라벨을 입력해도 에러가납니다. 똑같은데이터로 여러번입력하면 어떨땐 되고 어떨땐 안됩니다...

안될때의 공통점을 찾지못했습니다.

**Comment by XisoDev** [comment]
settings/dynamicField/store 의 500에러가 나타나네요. 
사용할 수 없는 요청 방식입니다.
라는메세지가 나타납니다.

**Comment by XisoDev** [comment]
Whoops, looks like something went wrong.

1/1
HttpXpressengineException in Handler.php line 71:
사용할 수 없는 요청 방식입니다.
in Handler.php line 71
at Handler->filter(object(MethodNotAllowedHttpException)) in Handler.php line 124
at Handler->render(object(Request), object(MethodNotAllowedHttpException)) in compiled.php line 2327
at Kernel->renderException(object(Request), object(MethodNotAllowedHttpException)) in compiled.php line 2243
at Kernel->handle(object(Request)) in index.php line 55

**Comment by akasima** [comment]
이런 .. 없던 에러가 생겼네요.
오류 확인했습니다.

**Comment by XisoDev** [comment]
라벨을 두개 다 입력해도 오류가납니다..ㅠ 오류가 날때와 나지않을때의 조건차이를 아직찾지못했습니다.

사용할 수 없는 요청방식 에러는 생각해보니 POST로 보내야하는데 GET으로 접근해서 나는에러였네요; 콘솔에서 다시 에러찍어보았습니다. 참고해보세용

<img width="2070" alt="2017-05-26 8 08 23" src="https://cloud.githubusercontent.com/assets/10387955/26492454/2a4c41aa-424f-11e7-981e-35d28e83d3e3.png">
<img width="1324" alt="2017-05-26 8 08 32" src="https://cloud.githubusercontent.com/assets/10387955/26492453/2a4ab01a-424f-11e7-84aa-7683e851d6ee.png">

**Comment by XisoDev** [comment]
애타게 기다리고있는데 ㅠㅠ 이번패치에는 포함되지 않았네요.

제쪽에서 원인을 찾아보고 해결이 가능하다면 PR을 보내도록 하겠습니다.

**Comment by XisoDev** [comment]
DynamicFieldHandler.php 에 create 함수내에 group 또는 id가 없을때 에러를 발생시키는부분을 주석처리했더니 정상적으로 동작합니다.

참고하시면좋겠습니다. 우선저는이상태로 사용하겠습니다.
` if ($group == null || $id == null) {
//            throw new Exceptions\InvalidConfigException;
        }`

**Comment by akasima** [comment]
네. 감사합니다. 

제가 해당 파트 담당인데.. 전혀 손대지 못하고 있네요.
7월 초에나.. 코드를 볼 수 있을것 같습니다. ;; 최대한 빠른 시간 내에 확인해볼께요;

**Comment by akasima** [comment]
메뉴에서 게시판 생성하거나 메뉴에서 게시판 관련 인스턴스의 정보를 수정할 경우 Config 데이터에 문제가 있었습니다. 
이미 만들어졌던 게시판의 경우 메뉴 수정에 가서 업데이트를 클릭해야 정상 동장 됩니다.

확장필드 생성 수정할 때 폼 입력 값 체크 관련한 오류는 다른 이슈에서 다룹니다.
