### ISSUE TITLE
artisan serve 불가

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#475]
public 디렉토리를 사용하지않아 artisan serve 커맨드의 사용이 불가합니다.

bootstrap/app.php 의 public 경로를 변경하여 해당문제를 해결했습니다.

`$app->bind(
    'path.public',
    function () {
        return base_path();
    }
);`

다음과같이 수정하였습니다.
`$app->bind(
    'path.public',
    function () {
        return __DIR__;
//        return base_path();
    }
);`

**Comment by XisoDev** [comment]
rewrite 문제를 비롯해 여러가지 문제가 계속발생합니다.

homestead를 구성하는게 차라리낫겠습니다.. close해주시면 감사하겠습니다.

**Comment by jhyeon1010** [comment]
뒤늦게라도 관련내용 답변드립니다.
저희는 국내에서 웹호스팅 서비스를 사용하는 많은 사용자들을 지원하기 위해 public 디렉토리를 제거 하고 프로젝트 루트 위치에 index 파일을 위치 시켰습니다. 그리고 이에 따라 public 경로를 새로 지정하였습니다. 이것은 웹호스팅 서비스가 httpd  서비스의 document root 를 변경할 수 없는 형태의 서비스이기에 불가피한 선택이였습니다. 
이후 말씀해주신 serve 커맨드등의 이슈를 발견하고 라라벨 Application 에서 정의된 `publicPath` 메서드를 변경할 수 있는 코드를 작성해  라라벨 프로젝트에 PR 을 던졌으나 받아들여지지 않았습니다. 그래서 현재는 serve  커맨드는 사용할 수 없는 상태가 된것입니다.
다른 사용자분들 중에도 public 디렉토리를 가지는 것에 대한 의견을 종종 주시고 있지만, 저희는 웹 호스팅 사용자분들을 지원하는 방향으로 진행하고 있기에 지금의 구조로 계속 진행하고 있는 것입니다.
연관되서 rewrite 의 문제도 public 경로를 루트 경로로 마추어서 작성되어지기 때문에 임의로 pubilc 경로를 변경하시는 경우 정상작동하지 않게 됩니다.
