### ISSUE TITLE
favicon 등록불가

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#476]
파비콘에 114x114 png 와 16x16 ico 파일모두 업로드를시도해보았지만 업로드가되지않습니다. (시스템관리자에게 문의 오류발생)

**Comment by khongchi** [comment]
자세한 오류 내용을 알았으면 합니다. 디버그모드를 `on`으로 설정하신 후, 발생하는 오류 내역을 알려주시면 감사하겠습니다.

**Comment by khongchi** [comment]
차후 문제가 재발하면 그때 다시 이슈화하도록 하겠습니다.
