### ISSUE TITLE
토글메뉴의 전체해제 불가

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#479]
게시판설정에서 토글메뉴를 전체 해제시 값이안들어가서 그런지 저장이되질않습니다.

하나를 해제하고 저장하면 저장이되나, 그상태에서 하나를 더 해제하고 저장하면 전체가 켜진상태로 돌아옵니다.

**Comment by jhyeon1010** [comment]
모든 메뉴를 비활성하는 경우 게시판에 전역 설정으로 잡힌 토글메뉴가 표시되는 문제로 파악되었습니다. 
토글메뉴쪽에 설정 상속을 구분할 수 있는 기능을 추가하였습니다.

전역 설정의 처리는 각 플러그인 별로 지원되어야 할것으로 보입니다.
