### ISSUE TITLE
cascading config 지원

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#48]
xe 사용자들이 xe의 기본설정을 변경할 수 있도록 지원하려면 .env 파일을 사용하는 것만으로는 역부족임. 그래서 라라벨 4.2에서 사용되었던 cascading config 기능을 사용할 수 있도록 적용하면 좋을듯.

.env 파일의 APP_ENV 변수값과 동일한 이름을 가진 디렉토리가 /config 디렉토리에 존재할 경우, 기본 config를 덮어 씌우는 기능(cascading config)을 제공하려 함.

**Comment by bnu** [comment]
:+1:
