### ISSUE TITLE
xe beta.18 에서 플러그인 업데이트 실패 콘솔 내용

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#480]
> command: Xpressengine\Plugin\Composer\Composer::command
xpressengine-installer: running in update mode
xpressengine-installer: Plugin composer file[storage/app/composer.plugins.json] is written
[merge-plugin] Loading storage/app/composer.plugins.json...
[merge-plugin] Merging xpressengine-plugin/alice
[merge-plugin] Merging xpressengine-plugin/board
[merge-plugin] Merging xpressengine-plugin/ckeditor
[merge-plugin] Merging xpressengine-plugin/claim
[merge-plugin] Merging xpressengine-plugin/comment
[merge-plugin] Merging xpressengine-plugin/emoticon
[merge-plugin] Merging xpressengine-plugin/external_page
[merge-plugin] Merging xpressengine-plugin/google_analytics
[merge-plugin] Merging xpressengine-plugin/news_client
[merge-plugin] Merging xpressengine-plugin/orientator
[merge-plugin] Merging xpressengine-plugin/page
[merge-plugin] Merging xpressengine-plugin/social_login
[merge-plugin] Merging xpressengine-plugin/widget_page
> pre-update-cmd: Xpressengine\Plugin\Composer\Composer::preUpdateOrInstall
Dependency "xpressengine-plugin/ckeditor" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "xpressengine-plugin/comment" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.195 seconds
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package xpressengine-plugin/alice (locked at 0.9.8, required as >=0.9.9) is satisfiable by xpressengine-plugin/alice[0.9.8] but these conflict with your requirements or minimum-stability.
Problem 2
- The requested package xpressengine-plugin/ckeditor (locked at 0.9.11, required as >=0.9.12) is satisfiable by xpressengine-plugin/ckeditor[0.9.11] but these conflict with your requirements or minimum-stability.
Problem 3
- The requested package xpressengine-plugin/comment (locked at 0.9.8, required as >=0.9.10) is satisfiable by xpressengine-plugin/comment[0.9.8] but these conflict with your requirements or minimum-stability.
Problem 4
- The requested package xpressengine-plugin/emoticon (locked at 0.9.0, required as >=0.9.1) is satisfiable by xpressengine-plugin/emoticon[0.9.0] but these conflict with your requirements or minimum-stability.
Problem 5
- The requested package xpressengine-plugin/page (locked at 0.9.2, required as >=0.9.3) is satisfiable by xpressengine-plugin/page[0.9.2] but these conflict with your requirements or minimum-stability.
Problem 6
- The requested package xpressengine-plugin/social_login (locked at 0.9.9, required as >=0.9.11) is satisfiable by xpressengine-plugin/social_login[0.9.9] but these conflict with your requirements or minimum-stability.

**Comment by khongchi** [comment]
사이트관리 페이지 > 플러그인 목록에서 업데이트하신거죠? 
위 콘솔내용이 어떤 플러그인을 업데이트하는 과정에서 발생했는지 궁금합니다.

**Comment by 1Sam** [comment]
boad 였던 것 같습니다.

**Comment by khongchi** [comment]
현재 alice, ckeditor, comment, emoticon, page, social_login 들의 설치된 버전을 알고싶습니다. ;;
그리고 가능하시다면 `composer.lock` 파일 내용을 좀 적어주시면 감사하겠습니다.

**Comment by 1Sam** [comment]
http://sendanywhe.re/3800SXVT

프러그인은 이미 직접 다운로드해서 압축풀어서 업데이트 해버렸습니다.

**Comment by khongchi** [comment]
올려주신 두 파일도 오류가 발생한 당시와 차이가 있어서 파악이 어렵네요..

계속 여쭤봐서 죄송합니다.

beta.18로 업데이트는 어떤 과정으로 하셨는지 궁금합니다.

- git으로 업데이트를 가져오셨는지, 아니면 어떤 링크를 통해 코어의 소스코드를 다운로드 받고 어떤 방법으로  덮어씌운건지
- 소스코드를 갱신한 후, core 업데이트 과정을 거치신건지(`php artisan xe:update ..` or `사이트관리자 > XE3업데이트`) 

자세한 상황을 알려주시면 감사하겠습니다.

**Comment by 1Sam** [comment]
https://github.com/xpressengine/xpressengine/archive/3.0.0-beta.18.zip

위의 파일을 17버전에 그대로 덮어 쓰기한 후에
php artisan xe:uptae ... 를 실행했습니다.

제가 사용중인 서버에 하나 특이한 점은, 서버 운영자가 composer 구버전을 전체 사용자가 사용할 수 있도록  설정해 놓았다는 것입니다. 그래서 플러그인을 업데이트 할 때 소스 파일을 각각 플러그인 폴더에 압축을 해제한 후에, php composer.phar update 이런식으로 xe3 기본 볼더에 있는 것을 사용하도록 직접 타이핑을 하여 업데이트를 실행합니다.

**Comment by khongchi** [comment]
플러그인 업데이트 관련하여 많은 수정이 있었기 때문에 이 문제는 해결 되었거나, 더이상 문제가 되지 않을것 같습니다.
차후 문제가 발생하면 다시 이슈화해서 처리하도록 하겠습니다.
