### ISSUE TITLE
DirectLink 생성시 URL 입력문제.

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#483]
의도적인건지 버그인지 알수는없으나,,

다이렉트 링크 컴포넌트를 메뉴로 등록할 때에, FULL URL을 입력하지않으면 저장이되질않습니다.

**Comment by jhyeon1010** [comment]
다이렉트 링크의 경우 프로토콜을 포함한 url 이 입력되어야 정상적으로 등록되도록 만들어졌습니다.

**Comment by XisoDev** [comment]
그렇게처리하는데 이유가 있습니까?

그렇게되면, 해시링크를 걸고싶을때 수동으로걸어야합니다. XE1에선 그게 가능했는데말이죠...

바라는게있다면 조건부 해시링크를 작성할 수 있게하면 좋겠습니다.

특정 인스턴스에서는 해시링크로 동작하고 나머지에서는 링크이동 + 해시로 동작하게끔이요.

스크롤링,해시링크가 많이 쓰이는요즘 필요한방법이아닐까싶어요

**Comment by XisoDev** [comment]
예를들어 입력값이

/#contactus 일때

url이 / 일땐 해시만출력하고 /board 등 다른 url일땐 /#contactus 로 동작해주면 좋겠네요.

**Comment by jhyeon1010** [comment]
다이렉트 링크에서 url 검사를 하는 이유는 사용자분들이 예상치 못하게 사용하는 경우들이 있기 때문입니다.
말씀해주신 해시링크는 다이렉트 링크에서 지원하기보다 별도의 컴포넌트로 구성하는것이 좋을 것 같습니다. 해시 링크 기능은 코어에서 제공할 것인지 3rd party 에서 추가하도록 할 것인지는 내부 협의 후 결정하도록 하겠습니다.

**Comment by jhyeon1010** [comment]
#443 에서 적용된 url 필터링이 #526 이슈로 인해 제거 되었습니다. 그로인해 기존에 사용하시던것처럼 directLink 타입의 메뉴를 자유롭게 사용할 수 있게 되었습니다.
이는 해시링크 메뉴타입을 구성하는 과정에서 발생한 문제와 한글 도메인의 문제가 복합적으로 결합되어, 필터링 적용이전 상태로 돌리는것이 좋을것 같다는 결론에 도달하여 결정된 사항입니다.
