### ISSUE TITLE
XE3 IIS10 설치오류

### ISSUE THREAD

**Issue by Kimbyeoungjang** [xpressengine/xpressengine#485]
IIS10, 윈도우 서버 2016 데이터센터 환경입니다. Web_Installer로 설치할경우 install/post로 넘어가는 과정에서, 500에러 납니다. 아무래도 rewrite문제인거 같은데, 모 회원분이 web.config의 DefaultDocumunt항목이 문제가 된다고는 하는데 어떻게 수정해야될지는 모르겠습니다....

**Comment by akasima** [comment]
제가 테스트 했던 환경에 문제가 있었는지도 모르겠습니다.

IIS 개발환경을 만드는데 어려움이 있어 테스트하는데 시간이 많이 걸립니다. 
우선 저희쪽에서 동일한 개발환경을 만들 수있는지 확인해볼께요.

**Comment by Kimbyeoungjang** [comment]
설치 시도 해보니까, db까지는 만들어지는데 메인화면 가면 내부서버 500에러 뜹니다

**Comment by khongchi** [comment]
IIS 환경에서 테스트 해 본 결과 xe의 rewrite rule과, 서버 설정에서 퍼미션 지정이 제대로 되지 않은 문제가 발생하네요.

rewrite rule을 정비해서 커밋해놓았습니다.

`web.config` 파일을 아래 내용으로 덮어 씌우시고 해보시기 바랍니다.
https://github.com/xpressengine/xpressengine/blob/a9b97f88b5bcfb669e83bd2d46abb0b848ead0c2/web.config

그래도 안 된다면 서버 퍼미션 문제일 가능성이 큽니다.
아래 링크를 참고하여 확인해보시기 바랍니다.

http://studyforus.tistory.com/219

감사합니다.

**Comment by Kimbyeoungjang** [comment]
Web.config 주신걸로 교체하니 정상작동합니다. 감사합니다. Iis 설치이슈는 이걸로 끝이네요 감사합니다^^
