### ISSUE TITLE
게시글 복사,이동시 대상을 선택할 수 없는 문제

### ISSUE THREAD

**Issue by XisoDev** [xpressengine/xpressengine#488]
게시글 복사,이동시 대상이 나타나지않습니다.
루프를 돌다가 멈추는지 하나의선택지가 나오긴합니다만, 타이틀이 표시되지않고 다른게시판은 보이지않습니다.

![image](https://user-images.githubusercontent.com/10387955/26976586-61d56410-4d5f-11e7-91de-ab4fdace9647.png)

**Comment by XisoDev** [comment]
영문라벨을 모두 입력해야 나타나네요.

하지만 여전히 모든 게시판이 나오진않습니다. ( 자기자신은 원래안나오는건지요? )

**Comment by akasima** [comment]
자기 자신은 나오지 않도록 설계해습니다.

다국어 처리할 때 출력 결과물이 빈 문자열일 때 어떻게 처리할 지 고민해 보겠습니다.

**Comment by akasima** [comment]
이름 표시해주는 코드에 오류가 있었네요. 수정해서 커밋했습니다.

https://github.com/xpressengine/plugin-board/commit/a164fbc6f2bfd84972d05664631871aac245bbd0
