### ISSUE TITLE
에디터에서 엔터 입력 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#489]
공식사이트 댓글 작성할 때 엔터 입력하면 두칸이 입력되는 오류가 있어 보입니다.

**Comment by seungmanchoi** [comment]
테스트 여러차례 시도시 재현이 안되는 상태로 우선적으로 재현안됨으로 이슈를 정리하고 추후 같은 문제가 발생시 재검토하기로 함.
