### ISSUE TITLE
서브 디렉토리에 설치 시 레이아웃 설정의 이미지 업로드 문제

### ISSUE THREAD

**Issue by wincomi** [xpressengine/xpressengine#506]
XE3을 서브 디렉토리에 설치할 경우, 레이아웃 설정에서 이미지를 업로드하여도 이미지가 나타나지 않습니다.

**Comment by khongchi** [comment]
좀 더 자세한 정보가 필요할 것 같은데요..
혹시 사이트 주소를 알 수 있을까요?

아니면 도메인과 브라우저에서 업로드한 이미지의 경로가 어떻게 되는지 알려주시면 감사하겠습니다.

**Comment by wincomi** [comment]
자세한 정보를 추가해봅니다.

XE3을 다음과 같이 하위 폴더에 설치합니다: _http://localhost/xe3_

레이아웃 설정에서 이미지를 업로드합니다.

![2017-07-10 10 58 12](https://user-images.githubusercontent.com/1822540/28021607-645633e6-65c3-11e7-8d45-c10c31cefdfc.png)

이미지 경로가 올바르지 않아서 제대로 나타나지 않습니다. 아래 경로를 `/xe3/storage/app/public/theme/theme/...`로 변경할 경우 이미지가 나타납니다.

![2017-07-10 10 58 47](https://user-images.githubusercontent.com/1822540/28021606-6404c22c-65c3-11e7-9e90-fd23e1de5e40.png)

**Comment by wincomi** [comment]
이 이슈와 관련된 문제인 것 같아 추가합니다.

![2017-07-10 11 06 46](https://user-images.githubusercontent.com/1822540/28021921-82dd9830-65c4-11e7-8c10-c88447c47115.png)

**Comment by khongchi** [comment]
https://github.com/xpressengine/plugin-alice/issues/9
`asset()`함수로 감싸서 출력해야하는데 이미지 경로를 그냥 써서 문제가 된 것으로보입니다. 위 이슈에서 처리했고 다음 배포때 적용될 예정입니다.

직접 코드를 수정해서 일단 사용하시려면
https://github.com/xpressengine/plugin-alice/commit/31972a0da08078042719340e1cdbcf21caa785e4 에서 변경된 사항을 코드에 적용하시면 됩니다.

감사합니다^^

**Comment by khongchi** [comment]
게시판도 처리했습니다.
https://github.com/xpressengine/plugin-board/issues/118
