### ISSUE TITLE
현재 코드에서.. 보면 간간히 보이는게..

### ISSUE THREAD

**Issue by qw5414** [xpressengine/xpressengine#52]
`$message = 'ID 형식이 잘못되었습니다.';`
이러한 코드들이 눈에 보입니다.
이건 가입시나 뭐 아이디 관련 액션이 취해졋을때 뜨도록 하는것 같은데 이렇게 한다는건, 어느정도 다국어에 대응이 안이루어지는 것인가요?

**Comment by khongchi** [comment]
에러의 메시지를 포함하여 XE 전반적으로 다국어에 대한 정리가 아직 미흡한 상태입니다.
조만간 정리할 계획입니다..
