### ISSUE TITLE
관리화면 플러그인의 태그 디자인 부분

### ISSUE THREAD

**Issue by lamir0star** [xpressengine/xpressengine#521]
플러그인 아래의 태그 표시가 마우스오버 이후에는 태그간 간격이 좁아집니다.

이미지 첨부드립니다.

> 마우스오버 이전
![_](https://user-images.githubusercontent.com/20913606/28709604-ed22dea8-73bb-11e7-9916-774c884616cb.jpeg)

> 마우스오버 이후
![_](https://user-images.githubusercontent.com/20913606/28709623-078a94f2-73bc-11e7-9a49-97c6d8b0303b.jpeg)

**Comment by khongchi** [comment]
@panach 각 태그에 마우스를 한번씩 올렸다 내리면 발생합니다.

**Comment by jhyeon1010** [comment]
#835
