### ISSUE TITLE
플러그인 개발시 plugin cache 에 의한 /settings/plugins 오류 문제

### ISSUE THREAD

**Issue by findstar** [xpressengine/xpressengine#522]
플러그인을 새롭게 생성하기 위해서
console 에서 php artisan make:plugin <name> <namespace> <title> 명령어를 입력후에
DOMAIN/setting/plugins 에서 정상적으로 플러그인 목록이 나오는지 확인이 가능. 
but 이 상태에서
plugin 의 composer.json 파일을 일부 수정하면 /setting/plugins 에서 오류 발생. 

1. plugin 을 새롭게 생성할 때에는 plugin cache 를 비활성화 하거나, 
2. setting/plugins url 접근시에 composer.json 파일 변경사항에 대한 체크를 보다 구분되게 하여야 
플러그인 개발자가 문제를 정확히 인지할 수 있을듯 합니다.

**Comment by khongchi** [comment]
기본적으로 플러그인 개발 작업은 디버깅모드에서 한다는 가정하에 구현했기 때문에 디버깅모드가 아니라면 composer.json를 수정해도 캐시를 갱신하지 않도록 되어 있습니다. 물론 디버깅모드에서는 모든 요청마다 캐시를 갱신하도록 되어 있구요.

디버깅 모드가 아니라도 /setting/plugins로 접근하면 담당 컨트롤러에서 캐시를 갱신하지만, 컨트롤러에 도달하기 전 부팅 과정에서 이미 오류가 날 수 있겠네요.

디버깅 모드가 아니더라도 플러그인 캐시를 좀 더 똑똑하게 갱신하는 방법을 찾아보거나, 오류 발생시 제안해 주신대로 더 친절하게 안내해야겠네요.

`composer.json`의 어떤 부분을 수정했는데 오류가 났는지 궁금합니다. json syntax 오류인지 xe컴포넌트쪽을 수정해서 발생한 오류인지 알려주세요.

**Comment by findstar** [comment]
@khongchi 그냥 plugin 의 composer.json 파일에서 author 이름만 바꿨었어요.

**Comment by khongchi** [comment]
@findstar 음... 단순히 이름을 바꾼게 오류의 원인은 아닐텐데..

**Comment by findstar** [comment]
@khongchi 웹 인스톨러로 설치하고 php artisan command 를 테스트 하던 중이라서 
production mode 인것 같아요.

**Comment by khongchi** [comment]
일단 플러그인의 composer.json에서 XE가 실행될 때, 문제가 될만한 부분은 component 등록 부분인데, component를 찾지 못하더라도 skip하고 넘어가도록 하였고 settings/plugins에서 skip된 component를 안내 하도록 변경(#525
)하였습니다.
또, 모든 콘솔접근시에는 플러그인 캐시(composer.json 캐시)를 다시 한번 갱신하도록 처리(#520) 해두었습니다.
