### ISSUE TITLE
다이렉트 링크 url 형식오류

### ISSUE THREAD

**Issue by ydevl4b** [xpressengine/xpressengine#526]
한글 도메인 사용시 url 형식이 유효하지 않아 링크 설정이 불가합니다.

아울러 메뉴 혹은 아이템 순서 이동편집이 불가합니다.

프로그레스는 돌아가는데 반영이 되질 않습니다..

**Comment by jhyeon1010** [comment]
php 내장함수 `filter_var` 필터링이 한글 도메인을 처리하지 못하네요. 수정해야할 것 같네요.
메뉴이동도 문제를 파악하는데로 수정하도록 하겠습니다.
