### ISSUE TITLE
git pull hook 추가 의견

### ISSUE THREAD

**Issue by findstar** [xpressengine/xpressengine#530]
git 으로 최신 버전을 유지하기 위해서. pull 을 하면서 사이트를 유지하고 있습니다.

storage/app/interception 디렉토리를 날리는 문제가 계속 날 수도 있고 그런데요.

git hook 을 제공해서 git pull을 받으면 local cache 를날리는 git hook 파일을 제공해주시면 좋겠습니다.

**Comment by khongchi** [comment]
일단 debug 모드를 켜놓으면 항상 갱신되도록 되어 있습니다. 참고하시구요.^^

git hook을 제공하는 것도 검토해 보겠습니다.

요즘 interception proxy 갱신 문제 때문에 계속 고민인데, 좀 더 근본적인 대책이 일단 필요해 보입니다. 디버그모드 외에 개발모드 내지는 캐시사용 설정을 별도로 추가하는것도 방법일거 같구요.

조만간 조치를 취하도록 하겠습니다

**Comment by khongchi** [comment]
일단 debug 모드를 켜놓으면 항상 갱신되도록 되어 있다고 했었는데, 콘솔환경에서만 갱신되도록 되어 있었네요. 바로 잡았고,
git hook 샘플 파일 추가해 놓았습니다. interception proxy만 갱신되도록 일단 해놓았습니다.

감사합니다.

**Comment by findstar** [comment]
👍

**Comment by akasima** [comment]
debug를 켠 상태(debug=true)에서 동시에 여러개의 요청이 발생할 경우(한 페이지에서 동시에 여러개의 ajax요청) intercept proxy 파일을 다시 만드는 과정에서 새로운 요청이 들어가 intercept proxy 파일을 찾지 못해 오류가 발생합니다. 이 문제로 이전 커밋을 되돌립니다.

**Comment by khongchi** [comment]
현재 debug 모드일 경우, 무조건 갱신되지 않고 파일타임을 체크하여 proxy 클래스가 오래됐을 경우 갱신되도록 구현되어 있습니다.(이미 예전부터 구현돼 있던 상태)

debug 모드에서 동일한 문제가 발생한다면 다시 알려주시기 바랍니다.
