### ISSUE TITLE
plugin 을 삭제할때 register 가 실행 되지 않는 문제

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#534]
plugin 삭제시 `uninstall` 메서드를 통해 디비등에 기록되었던 정보를 삭제하려고 합니다. 그런데 이 삭제 과정에서는 plugin.php 의 `register` 를 호출하지 않아 플러그인 내부 클래스를 사용할 수 없습니다.
```
public function uninstall()
{
    app(Handler::class)->removeConfig();
}
```
예를들어, 어떤 핸들러 클래스에서 config 키를 관리하여 동작하고 삭제 기능을 제공할때 위 코드와 같이 uninstall 내용을 구성할 수 있습니다. 하지만 `Handler` 인스턴스를 등록하는 `register` 가 호출되지 않아 `Handler` 클래스의 생성자에 정의된 의존대상들을 찾지 못하는 상황이 발생합니다.

플러그인 삭제 처리 이전에 해당 플러그인의 `register` 함수호출이 필요해 보입니다.

**Comment by khongchi** [comment]
추가해두었습니다. 테스트해보시고 문제있으면 이슈 다시 열어주세요.
