### ISSUE TITLE
댓글 작성시 삭제된 내용입니다로 표시되는 문제

### ISSUE THREAD

**Issue by aeun** [xpressengine/xpressengine#54]
댓글 작성시 DB에는 정상적으로 들어가나 실제 표시는 '삭제된 내용입니다'라고 나옵니다.
서버환경
Ubuntu 14.04 LTS 64bit
Nginx 1.4.6
php 5.5.9-1ubuntu4.14

**Comment by jhyeon1010** [comment]
알려주신 환경과 같은 환경구성후 테스트를 시도해도 해당 문제가 재현되지 않습니다.
문제가 발생한 환경의 데이터베이스 종류와 버전을 알려주시기 바랍니다.

**Comment by aeun** [comment]
DB서버
Ubuntu 14.04 LTS 64bit
mysql --version 입력시 하단과 같이 출력 (MariaDB사용)
mysql  Ver 15.1 Distrib 5.5.46-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

기타 참고할 사항으로는 두 서버는 별개로 구성되어 있고 스위치를 통해 서로 연결되어 있습니다.
웹서버측의 php는 php5-fpm로 연결되었습니다.

**Comment by jhyeon1010** [comment]
확인 결과 apt-get 으로 php 설치시 mysqlnd 가 아닌  mysql 설치시 integer 값이 string 으로 반환되는 것으로 파악되었습니다. 위 환경에서는 `php5-mysqlnd` 를 설치하면 정상적으로 표시되는것을 확인하실 수 있으실것으로 보입니다.
