### ISSUE TITLE
플러그인을 설치할때 plugin.php 의 install 메서드를 실행하지 않음

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#540]
플러그인을 새로 설치할때 `install()` 메서드가 실행되지 않아 메서드내에 작성된 플러그인의 기초 데이터 설정작업이 처리되지 않습니다.

**Comment by khongchi** [comment]
@jhyeon1010
플러그인을 활성화할 때 install()이 실행됩니다. 활성화했는데 실행이 안 된건가요?

**Comment by jhyeon1010** [comment]
플러그인 설치때 install 이 실행되는것이 아니고 활성화때 실행이 되는 것인가요? 그러면 활성화시에 `activate` 와 `install` 두개 메서드가 실행되는 것인가요? 

만약 그렇다면 왜 그렇게 처리된건지 알려주시기 바랍니다.

**Comment by khongchi** [comment]
사이트 관리자 입장에서보면, '활성화' 버튼이 제공하고, '활성화'버튼을 클릭했을 때, 플러그인을 사용하기 위한 과정에서 `install`, `activate` 모두 실행되므로 두 메소드를 구분할 필요가 없습니다.

XE입장에서도 플러그인에게 `activate` 구현만 요구하고, `install`에서 실행될 코드는  `activate`시 알아서 실행하도록 한다면, 두 메소드를 구분할 필요가 없습니다.

다만, 이렇게 `install` 메소드를 스펙으로 구분해 놓은 이유는, 플러그인 개발자나 사이트관리자가 어떤 플러그인의 초기 셋팅 사항을 한눈에 파악할 수 있도록 좀 더 명시적으로 구분해 놓기 위함입니다.
