### ISSUE TITLE
앨리스 테마에서 기본 이외의 추가한 테마 설정은 제거할 수 없나요?

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#544]
<img src="http://i.imgur.com/ivox7PS.png">

데스크탑 // 모바일  테마 설정을 추가한 후 제거할 수 있는 방법이 없는 것 같습니다.

테스트한다고 이리저리 많이 추가해 놓은 상태라 제거 기능이 필요합니다.....

확인해 주시기 바랍니다.

**Comment by khongchi** [comment]
각 설정의 수정페이지에 들어가시면 삭제 버튼이 있습니다.
수정 페이지 하단에 `삭제`,`저장` 버튼이 나란히 있습니다 ^^

눈에 잘 띄지 않는 문제가 있는데요.. 차후 UI 개선 작업을 할 때 같이 진행될 예정입니다.
