### ISSUE TITLE
회원가입폼의 순서지정

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#545]
회원가입폼에 입력항목을 추가하는 경우 약관 동의 밑으로 추가됩니다.
순서를 지정할 수 있어야 할 것 같습니다.

**Comment by khongchi** [comment]
사이트 관리자가 회원가입폼의 순서를 변경하는 기능은 없습니다.

플러그인에서 자체적으로 순서를 변경하려면 `XeUser@getRegisterForms`에 interception을 추가하여 처리할 수 있습니다.
https://github.com/xpressengine/plugin-mailing/blob/master/plugin.php#L79

고민해보니 사이트 관리자가 직접 순서를 변경하는 방법을 제공하는게 좋을것 같네요.
토글메뉴 설정 UI처럼 (on/off 기능은 빼고) 순서변경 기능을 추가하는 것도 좋은 방법으로 보입니다.
한번 논의하면 좋겠네요.

**Comment by jhyeon1010** [comment]
네. 언급한 기능 제공하도록 해주시기 바랍니다.
