### ISSUE TITLE
웹 관리자에서 플러그인을 업데이트 할때 버전 지정

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#546]
현재 xe3는 업데이트시 처리되는 코드들의 충돌 문제로 버전을 순차적으로 올려야 합니다.
그러나 웹에서 업데이트를 하는경우 최신버전을 업데이트 하도록 처리되고 있습니다. 버전을 지정할 수 있거나 최신버전이 아닌 다음 버전을 업데이트 할 수 있도록 해야할 것으로 보입니다.

**Comment by khongchi** [comment]
우선 버전을 지정하여 플러그인을 업데이트하는 방법은 콘솔명령으로 제공되고 있습니다.

```
php artisan plugin:update board 1.0.0
```

웹 플러그인 업데이트시 버전 지정 기능은 플러그인 관리페이지 리뉴얼 적용 후에 추가하도록 하겠습니다.
