### ISSUE TITLE
게시물에 댓글 수 표시 안됨

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#551]
댓글 작성후 게시물에 댓글 수가 표시되지 않습니다.

**Comment by akasima** [comment]
BoardModule 에서 지정한 intercept 가 동작하지 않아 발생한 문제로 보입니다.

Comment 에서 `$proxyClass = $app['xe.interception']->proxy(Handler::class, 'XeComment');`로 지정한 proxy가 정상적으로 호출되지 않아 발생한 문제입니다.

interception의 pointCut 지정에서 class 이름과, alias 두가지를 모두 사용할 수 있도록 했으나 class 이름을 사용할 경우 발생한 오류 입니다.

**Comment by khongchi** [comment]
alias와 class명으로 모두 등록한 intercept가 있을 경우, 이를 통합하는 과정에서 오류가 있었습니다.
