### ISSUE TITLE
데이터베이스 컬럼 이름 변경

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#552]
데이터베이스 테이블 컬럼 이름을 변경하고 이에 따른 core 및 번들 plugin 코드를 수정합니다.
현재 XE3의 데이터베이스 테이블 컬럼 이름은 camelCase로 작명되어 사용중입니다. PHP 에서 변수 이름등에 camelCase를 사용했었고 이 경험을 그대로 가져오기 위해 결정했던 사항입니다.
하지만 MySQL외에 다른 DBMS 지원를 사용할 경우 컬럼 이름에 대소문자 구분을 지원하지 않는 경우도 있을 수 있다는 지적이 있어 이와 같은 결정을 했습니다.

코드 변경의 범위는 코어, 번들 플러그인, View Blade 파일, Html의 name attribute 등 많은 부분에 수정이 진행 되겠습니다. 

User 테이블을 예로 들면 displayName, createdAt 등의 컬럼 이름을 display_name, created_at 으로 변경하고 
Model, Controller 에서 관련 코드를 수정할 예정입니다.
또한 HTML 에서 사용하는 관련 코드와 input 태그의 name attribute 또한 수정합니다.

**Comment by findstar** [comment]
👍
