### ISSUE TITLE
env example 파일 제공좀 부탁드립니다. 

### ISSUE THREAD

**Issue by choiks14** [xpressengine/xpressengine#557]
env 파일이 없어서 새로운 laravel을 설치해서 붙여넣기 했습니다. ㅠㅠ
default로 env 파일좀 부탁드립니다

**Comment by jhyeon1010** [comment]
env 파일은 laravel 을 굳이 설치하실 필요없이 https://github.com/laravel/laravel/blob/master/.env.example 에서 확인하실 수 있습니다. 그러나 `.env.example` 파일에 사용가능한 모든 항목이 명시되어 있지는 않습니다. 필요시 프로젝트 루트 위치에 `.env` 파일을 생성하시고 사용하고자하는 항목은 config 디렉토리에 있는 파일내용을 참고하셔서 지원되는 항목이 어떤것이 있는지 확인 후 작성하시는게 좋을듯 싶습니다.

XE 는 현재 환경 값(`.env` 에서 `APP_ENV` 에 해당하는 값)에 매칭되는 `config` 디렉토리의 하위 디렉토리 설정을 적용하도록 되어있습니다. APP_ENV 항목이 작성되지 않은 경우 `APP_ENV=production` 과 같은 환경으로 취급되며, XE 최초 설치시 `production` 으로 환경이 설정됩니다.
만약 `.env` 를 생성하고 `APP_ENV` 를 다른값으로 설정한 경우 `config/production` 디렉토리의 설정이 적용되지 않으므로 주의하시기 바랍니다.

저희는 `.env` 를 통한 설정보다 `config` 디렉토리 하위에 개별 환경 설정디렉토리를 생성하여 사용하시는것을 추천드립니다. 그 이유는 설정이 `.env`를 통해 모두 지원되지 않고 일부 설정이 closure 로 되어있기 때문에 `.env`를 이용한 방법은 한계가 있습니다. 

`.env` 파일에서는 `APP_ENV`만 사용하시고 나머지 설정은 `config` 디렉토리내에 `APP_ENV` 값과 동일한 이름의 하위 디렉토리를 생성해서 사용하시기를 바랍니다.
