### ISSUE TITLE
게시판 - 다이나믹필드 등록 과정에서 항상 실행되는 intercept 코드의 문제

### ISSUE THREAD

**Issue by khongchi** [xpressengine/xpressengine#558]
`\Xpressengine\Plugins\Board\Components\Skins\Board\Common\CommonSkin::interceptDynamicField`를 보면 다이나믹 필드가 생성될 때 실행되도록 intercept 코드를 등록하고 있는데요.

이 코드가 게시판의 다이나믹 필드가 생성될 때만 실행되도록 한정해야 될 것 같습니다. 
이 코드가 회원의 확장필드를 등록하는 과정에서도 실행되어 오류가 발생하네요 ^^

**Comment by akasima** [comment]
https://github.com/xpressengine/plugin-board/issues/126 에서 처리되었습니다. 
수정된 코드는 다음주에 배포될 예정입니다.
