### ISSUE TITLE
글 등록시 current_url에 변경된 포트가 안들어 있습니다.

### ISSUE THREAD

**Issue by littleanti** [xpressengine/xpressengine#562]
글 등록시 current_url에 변경한 포트값이 안 들어 있는지.

80 포트로 자꾸 리다이렉트 하네요.

current_url 위치를 알려주시거나 수정 부탁드립니다.

**Comment by jhyeon1010** [comment]
알려주신 내용으로는 어떤 문제인지 확인이 어렵습니다.
문제가 발생한것에 대해 좀 더 자세한 내용을 알려주셨으면 합니다.

**Comment by littleanti** [comment]
아파치의 포트를 8080으로 변경한 상태에서 XE를 설치하고 게시판에 글 등록을 해보시면 글 등록후 리다이렉트 되는 과정에서 127.0.0.1:80/...로 리다이렉팅이 되는 문제입니다.

**Comment by bnu** [comment]
@littleanti XE3이 아니라 XE 1 버전 이시죠?

**Comment by littleanti** [comment]
네 1.8.44 버전입니다. deprecated 되었나보네요?

**Comment by littleanti** [comment]
글 내리겠습니다. 3.0 버전 git이였네요
