### ISSUE TITLE
글작성시에 내용을 입력할 수 없는 버그

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#563]
<img src="https://i.imgur.com/UJIx8d1.png">

0.1초정도 내용입력 창이 보였다가 내용입력 창이 사라집니다.
속성에서 hidden이라고 표시됩니다.

수차례 xe3 latest 버전으로 서버에서 파일과 DB를 삭제한 후에 설치해봐도 같은 증상이 발생합니다.
특별히 옵션을 수정해야하는 것인가요?

WebServer : Apache
PHP Version : 7.1.9
Debug Mode : No
Cache Driver : file
Maintenance : Off
TimeZone : Asia/Seoul

Copyright ©2015 XpressEngine. All rights reserved. Version 3.0.0-beta.23

Alice Theme
versionVersion 0.9.13작성자By @xpressengine installPathplugins/alice
This Package is Xpressengine Plugin - Alice Theme.
theme
자세히보기
게시판
versionVersion 0.9.21작성자By @XE Developers installPathplugins/board
XpressEngine's plugin for bundle (XE)
skin skin skin skin skin settingsSkin widget module uiobject uiobject uiobject uiobject
자세히보기
CkEditor
versionVersion 0.9.19작성자By @XE Developers installPathplugins/ckeditor
XpressEngine's plugin for bundle (XE)
자세히보기
신고
versionVersion 0.9.4작성자By @XE Developers installPathplugins/claim
XpressEngine's plugin for bundle (XE)
settingsSkin
자세히보기
댓글
versionVersion 0.9.15작성자By @XE Developers installPathplugins/comment
XpressEngine's plugin for bundle (XE)
skin settingsSkin uiobject
설정 자세히보기
News Client
versionVersion 0.9.5작성자By @XE Team installPathplugins/news_client
This Package is Xpressengine Plugin - News_Client.
skin settingsSkin widget
설정 자세히보기
Image Orientator
versionVersion 0.9.1작성자By @XE Developers installPathplugins/orientator
Image orientate plugin
자세히보기
Page
versionVersion 0.9.5작성자By @XE Developers installPathplugins/page
XpressEngine's page plugin for bundle (XE)
skin settingsSkin module
자세히보기
Widget page
versionVersion 0.9.0작성자By @XE Developers installPathplugins/widget_page
This Package is Xpressengine Plugin - Widget page.
module

HP Directive | 정보 | Setting
-- | -- | --
allow_url_fopen | This option enables the URL-aware fopen wrappers that enable accessing URL object like files. Default wrappers are provided for the access of remote files using the ftp or http protocol, some extensions like zlib may register additional wrappers. | 활성화됨PHP Default: 활성화됨
allow_url_include | This option allows the use of URL-aware fopen wrappers with the following functions: include(), include_once(), require(), require_once(). | 활성화됨PHP Default: 비활성화됨
display_errors | This determines whether errors should be printed to the screen as part of the output or if they should be hidden from the user. | 비활성화됨PHP Default: 활성화됨
enable_dl | This directive is really only useful in the Apache module version of PHP. You can turn dynamic loading of PHP extensions with dl() on and off per virtual server or per directory. The main reason for turning dynamic loading off is security. With dynamic loading, it is possible to ignore all open_basedir restrictions. The default is to allow dynamic loading, except when using safe mode. This feature is deprecated, and will be removed at a future time. | 비활성화됨PHP Default: 활성화됨
file_uploads | Whether or not to allow HTTP file uploads. | 활성화됨PHP Default: 활성화됨
max_execution_time | This sets the maximum time in seconds a script is allowed to run before it is terminated by the parser. This helps prevent poorly written scripts from tying up the server. The default setting is 90. | PHP Default: 90
max_input_time | This sets the maximum time in seconds a script is allowed to parse input data, like POST, GET and file uploads. | PHP Default: -1
max_input_vars | This sets the maximum number of input variables allowed per request and can be used to deter denial of service attacks involving hash collisions on the input variable names. | PHP Default: 1000
memory_limit | This sets the maximum amount of memory in bytes that a script is allowed to allocate. This helps prevent poorly written scripts for eating up all available memory on a server. Note that to have no memory limit, set this directive to -1. | PHP Default: 128M
session.gc_maxlifetime | This specifies the number of seconds after which data will be seen as "garbage" and potentially cleaned up. | PHP Default: 1440
session.save_path | session.save_path defines the argument which is passed to the save handler. If you choose the default files handler, this is the path where the files are created. | PHP Default: /var/cpanel/php/sessions/ea-php71
upload_max_filesize | The maximum size of an uploaded file. | PHP Default: 2M

**Comment by jhyeon1010** [comment]
브라우저에 따른 스크립트 오동작을 보이는것 같네요
브라우저 종류와 버전을 알려주시면 확인해보도록 하겠습니다.

**Comment by 1Sam** [comment]
윈10의 크롬입니다.
