### ISSUE TITLE
$config->get 에 asset()처럼 secure 여부 처리

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#564]
큰건 아닌듯한데..

\URL::forceSchema('https');

boot시 위를 부르면

{{ $theme::asset("images/main_bg_01.jpg") }}

코드는 무조건 https 가 붙는데

<img src="{{ $config->get('logo_image.path') }}" style="width:100px;">
위의 경우에는
영향을 받지 않는것 같습니다.

저장된 config값이 path라면, path를 뿌려줄때 https여부를 작동해야하지는 않을지요?

**Comment by jhyeon1010** [comment]
config 에 저장된 값은 숫자, 문자, boolean 등 다양한 값이 등록될 수 있습니다. 말씀하신 링크나 파일경로와 같은 값도 config 의 입장에서는 문자열이고 별도로 다르게 분류하여 제공하지는 않습니다. 
설정된 값이 링크나 파일경로인경우 사용하는 쪽에서 `asset` 헬퍼 함수를 사용하여 처리하시는 것이 좋을것 같습니다.
```
{{ asset($config->get('some.path') }}
```
https://laravel.com/docs/5.5/helpers#method-asset

**Comment by sangemi** [comment]
alice 테마에는 이미 적용되어 있네요.
                    <div class="item-slide" style="background-image:url({{asset($config->get('slide3Image.path'))}})">

제가 매우 옛날 alice테마에서 보고 질의드린듯합니다. 이 이슈를 어떻게 닫지요? ㅎ 처음이라..
