### ISSUE TITLE
ckeditor  플러그인 추가 방법

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#565]
https://ckeditor.com/addon/youtube

위 사이트의 유튜브 애드온을 ckeditor에 추가하려고 합니다.

xe3/plugins/ckeditor/assets/ckeditor/plugins/youtube

위 폴더에 파일을 추가했습니다.

xe3/plugins/ckeditor/assets/ckeditor/config.js 

위 파일에 

config.extraPlugins = 'youtube';

위의 옵션을 추가했습니다.

글 작성할 때 에디터에 유튜브 컴포턴트 아이콘이 표시되지 않습니다.

특별한 설정이 필요한지 궁금합니다.

**Comment by seungmanchoi** [comment]
xe3/plugins/ckeditor/assets/ckeditor/plugins/youtube
위 경로에 플러그인 파일을 추가하신 뒤에
xe.ckeditor.define.js 파일을 열어보시면 구조중 config 부분이 있고 config 안에 extraPlugins이 있습니다.
'resize,justify,tableresize,codesnippet,panelbutton,colorbutton ..... ' 이런식으로 플러그인들이 추가 되어 있는데 이부분에 youtube를 추가해서 넣으시면 됩니다.

**Comment by brian-sj** [comment]
그런데 저장을 하면 iframe 테그를 필터링 해버려서 저장이 않됩니다. 
이거 어떻게 해야 합니까?
