### ISSUE TITLE
filesystem 에서 default를 s3으로 했을 경우 fstat오류

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#567]
https://stackoverflow.com/questions/30738520/league-flysystem-fstat-expects-parameter-1-to-be-resource-object-given

디폴트로 s3로 설정했을 경우 

메뉴를 클릭해서 페이지를 이동할때마다 
위 링크의 증상(fstat() ... 오류)이 나타납니다.

확인부탁드립니다.

**Comment by jhyeon1010** [comment]
beta.24 이전에는 laravel 5.1 을 사용하고 있었는데, 이때는 파일 컨텐츠가 resource 인지만 확인했었습니다.
5.5 에서는 전달받은 파일 컨텐츠가 파일 객체인지를 추가로 확인하고 있습니다. 
업데이트 이후에는 같은 문제가 발생하지 않을것으로 예상되는데, 혹시 계속 문제가 발생하신다면 다시 알려주시기 바랍니다.
