### ISSUE TITLE
app\Exceptions\Handler 개선

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#568]
HttpXpressengineException 이 아닌 오류가 발생할 경우 개선이 필요합니다.
TokenMismatchException 등이 발생할 경우 메시지 처리를 위해서 Exception을 새로 만들어서 처리하는 과정을 개선해야할 필요가 있습니다. 
Exception을 새로 만드는 과정에서 문제가된 Exception 정보를 찾을 수 없게 되거는 등 디버깅할 때 문제를 야기할 수 있다고 생각됩니다.

Exception 페이지를 출력할 때 error 페이지 출력 여부만 처리할 수 있도록 수정하고 메시징 처리는 blade 파일 등에서 처리할 수 있도록 하는게 좋을것 같습니다.

**Comment by findstar** [comment]
라라벨 5.5에서 개선된 exception 기능을 활용해보는 것도 방법일것 같습니다.

**Comment by jhyeon1010** [comment]
@findstar 네 기능검토하여 활용해보도록 하겠습니다. 
의견 감사합니다.
