### ISSUE TITLE
.env에 내용을 넣었을 경우 오류

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#573]
http://52.78.156.195:52555/

위 링크 확인해주시면
xe_site 가 아니라 그냥 site 테이블을 부르려 합니다.
설치할때 prefix로 xe를 입력했구요.

이 상태는
.env 파일을 작성한 상태인데
DB_HOST=db-sk-v1.cbzrzb85ecy2.ap-northeast-2.rds.amazonaws.com
DB_USERNAME=********
DB_PASSWORD=*********
DB_DATABASE=kstar
DB_PORT=3306

이 .env파일을 없애면 정상작동됩니다. 

현재 .env파일이 있을때 prefix "xe"를 붙이지 않는듯합니다.

**Comment by jhyeon1010** [comment]
.env 에 작성된 `APP_ENV` 값이 `production` 이 아닌 다른 값이 설정되신건 아닌가요?

**Comment by sangemi** [comment]
네 우선 해결은 했습니다.
local로 해놓으면 오류나고 production 해놓으면 잘 되서 살펴보니..

config/databse.php 의
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            **'prefix' => '',**
            'strict' => true,
            'engine' => null,
        ],
위 prefix 부분이 비어있었습니다.
production 디렉토리 내의 database.php 에는 xe_가 적혀있구요.

(제가 실수로 지웠을 가능성도 있으나..)
prefix 가 production 디렉토리에만 적용되는것은 아닌지
혹시 모르니 체크해 주세요

확인 후 닫아주시면 될듯합니다. 감사합니다~~

**Comment by sangemi** [comment]
아, 혹시 기획하신건가요??
처음 설치시 production 설정을 사용하게 하고,
혹시나 개발용을 위해서 .env에 local이라고 설정하려면

prefix 등 설정 개별적으로 해서 개발 db연결해서 쓰라...

**Comment by jhyeon1010** [comment]
xe 에서는 환경변수에 따라 다른 설정파일을 사용하도록 설계 되었습니다.
config 디렉토리내에 환경변수와 같은 이름의 디렉토리가 있는 경우 해당 디렉토리내 설정이 적용됩니다. 최초 설치시에는 production 으로 설정되므로 config/production 이라는 디렉토리의 설정정보가 적용되는 것입니다. 
.env 에서 local 로 지정하신 경우 동일하게 config/local 디렉토리를 생성하여 설정파일을 위치시키시면 해당 내용이  적용되고, 디렉토리가 없는경우 기본 설정이 적용됩니다. 

.env 파일이 없거나 APP_ENV 값이 없는경우 default 는 production 입니다.
