### ISSUE TITLE
page 생성할 때 기본 언어 사용 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#575]
page 플러그인으로 메뉴 아이템을 생성할 때 document table 에 locale 정보가 입력되지 않아 페이지에 접근하거나 상세정보를 수정할 수 없습니다.

`app('xe.translator')->getLocale()` 에서 빈 문자열 반환하는 문제로 보입니다.

**Comment by jhyeon1010** [comment]
xpressengine/plugin-page#13 에서 처리되므로 현재 이슈는 닫겠습니다.
