### ISSUE TITLE
allow_url_fopen 우회하는 방법은?

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#576]
cpanel 에서 allow_url_fopen 옵션을 아무리 on 으로 해도 실제 사이트에는 적용되지 않는 것으로 보아
제가 사용하는 웹서버 서비스 환경에서는 막혀 있는 것 같습니다.

앞으로도 xe3 사용자가 수동 업데이트(#553)를 해야하는 것인지
아니면 개발진께서 우회하는 방법을 따로 계획하고 계시는지 궁금합니다.

**Comment by akasima** [comment]
컴포저를 사용할 수 없는 환경이라고 봐야할까요?
컴포저 사용을 기본 컨셉으로 잡고 있어서 정확히 어떻게 대처해 나가겠다는 확답을 드리긴 어렵겠습니다.

업데이트 관련하여 계획하고 있는 부부은 beta.24에서 추가된 안전모드(safe mode)를 이용한 업데이트 처리하는 계획을 갖고 있습니다. composer 를 사용안하고 우회하는 방법에 대해서 확정된 바는 없습니다.
