### ISSUE TITLE
24버전 오류 (macro관련)

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#577]
User모델을 확장에 대한 내용입니다.

플러그인의 boot()에

        \Xpressengine\User\Models\User::macro('ccMailWork', function() {
            return $this->belongsTo( CcMailWork::class, 'id', 'user_id');
        });

해놓고 다른 컨트롤러에서

auth()->user()->ccMailWork()
이걸 부르면 실행이 잘 되었습니다.ㅣ (beta24 이전)

24버전 업글 후,

**[로그인을 안한 상태에서의 오류 로그]**
local.ERROR: Undefined property: Xpressengine\User\Models\Guest::$ccMailWork {"exception":"[object] (ErrorException(code: 0): Undefined property: Xpressengine\\User\\Models\\Guest::$ccMailWork at /var/www/vhosts/boonzero/www/plugins/Boon/src/Ccmail/CcMailWorkController.php:61)
[stacktrace]
#0 /var/www/vhosts/boonzero/www/plugins/Boon/src/Ccmail/CcMailWorkController.php(61): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/vhosts...', 61, Array)
#1 [internal function]: Kenny\\Boon\\Ccmail\\CcMailWorkController->index()
#2 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#4 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Kenny\\Boon\\Ccmail\\CcMailWorkController), 'index')
#5 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#6 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Route->run()
#7 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#8 /var/www/vhosts/boonzero/www/app/Http/Middleware/LogMiddleware.php(64): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Xpressengine\\Http\\Request))
#9 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Pi
...

**[로그인을 한 상태에서의 오류 로그]**
Database [user] not configured. {"userId":"d418f2aa-c18a-4547-8497-fd76955449df","email":"sangemi@daum.net","exception":"[object] (InvalidArgumentException(code: 0): Database [user] not configured. at /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:140)
[stacktrace]
#0 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(103): Illuminate\\Database\\DatabaseManager->configuration('user')
#1 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(74): Illuminate\\Database\\DatabaseManager->makeConnection('user')
#2 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1079): Illuminate\\Database\\DatabaseManager->connection('user')
#3 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1045): Illuminate\\Database\\Eloquent\\Model::resolveConnection('user')
#4 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(879): Illuminate\\Database\\Eloquent\\Model->getConnection()
#5 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(838): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#6 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(822): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#7 /var/www/vhosts/boonzero/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php(121): Illuminate\\Database\\Eloquent\\Model->newQuery()
#8 /var/www/vhosts/boonzero/www/plugins/Boon/plugin.php(44): Illuminate\\Database\\Eloquent\\Model->belongsTo('Kenny\\\\Boon\\\\Ccma...', 'id', 'user_id')
#9 [internal function]: Xpressengine\\User\\Models\\User->Kenny\\Boon\\{closure}()
#10 /var/www/vhosts/boonzero/www/core/src/Xpressengine/Database/Eloqu

위와같은 오류가 나오고 있습니다. (로그파일)

debug = true로 하나 false로 하나 동일한 오류가 나오기 때문에
24에서 추가된 디버그기능 관련은 아닌것 같습니다.

**Comment by akasima** [comment]
24 이전 버전에서 로그인 안한 상태에서 테스트 안된게 아닐까요?
로그인 사용자는 `\Xpressengine\User\Models\User` 모델을 사용하고
로그인 안한 상태에서 `Xpressengine\User\Models\Guest` 모델을 사용하는데요.

```
    \Xpressengine\User\Models\User::macro('ccMailWork', function() {
        return $this->belongsTo( CcMailWork::class, 'id', 'user_id');
    });
```

**Comment by sangemi** [comment]
위 코드는 라우터에서
auth 미들웨어로 감싸고 있었기 때문에 로그인하지 않은 상태에서 실행될일이 없었습니다.
현재 문제가 2가지인듯합니다.

1. route에서 auth middleware가 작동하지 않습니다.
(깨끗한 beta24를 깔아도 그런듯합니다)

2. 위 macro가 로그인한 상태에서는 정상작동해야할텐데 
Database [user] not configured.
관련 에러가 나오고 있습니다.

**Comment by jhyeon1010** [comment]
1. #578 에서 auth middleware 문제가 수정되었습니다.
2. 1번과 연관된 문제였는지 정확히 알수는 없으나, 테스트 결과 현재 정상적으로 동작하고 있습니다.

문제가 있으신 경우 다시 알려주시기 바랍니다.
