### ISSUE TITLE
beta24 깨끗한버전에서 middleware auth

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#578]
git으로 새로 설치한 후
alice 플러그인의 boot()에

Route::get('a', function(){
                return "a";
});
이렇게 넣고
domain.com/a
접속을 하면 a 가 나옵니다.

그런데

Route::group(['middleware' => ['web', 'auth']], function () {
            Route::get('a', function(){
                return "a";
            });
});

위 코드럴 넣고
domain.com/a
로 접속을 해도
a가 나옵니다. 
auth/login 으로 리다이렉팅 되어야할것같은데.

auth 미들웨어가 작동하지 않는지요??

**Comment by jhyeon1010** [comment]
미들웨어에서 사용된 `authenticate` 메서드를 구현하여 XE에 맞게 처리되도록 수정하였습니다.
