### ISSUE TITLE
Uncaught TypeError: undefined is not a valid argument for URI

### ISSUE THREAD

**Issue by ppleo** [xpressengine/xpressengine#580]
Your version: 1.8.43 까지는 괜찮더니 Your version: 1.8.45 으로 업하니.

전체 파일을 업해서..

아래 와 같은 에러가 나면서 슬라이더가 무한로딩만 되네요..^^

같은 슬라이드을 쓰는데 다른샘플 사이트는 괜찮은데요.. 혹시 무슨 문제가 있을까요?

![image](https://user-images.githubusercontent.com/5974818/31418177-65c4397c-ae6f-11e7-91dc-184a57f97dc3.png)

같은 슬라이드 문제가 생기는 것입니다.
http://www.2sisstore.com/mercury

정상인곳....하하하..^^

http://www.2sisstore.com/cronos_rx

**Comment by akasima** [comment]
XE 1.x 버전 이슈로 보입니다. 
https://github.com/xpressengine/xe-core 저장소에 다시 등록해 주세요.

**Comment by ppleo** [comment]
^^ 죄송합니다. 그렇군요. 다르군요..

**Comment by akasima** [comment]
아닙니다. :)
