### ISSUE TITLE
24버전, 확장필드 생성 후

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#584]
use : true
require : false 
로 한 이후에
회원가입을 하면 

The given data was invalid.

에러가 나옵니다.

확장필드 삭제후 가입하면 잘 됩니다. 
테스트시
확장필드는 휴대폰,
id값은 phone 으로 했습니다.

ps)) id 값에는 주로 무엇을 넣도록 기획되었을까요?
table에는 id값_cell_phone_number 이라는 컬럼이 만들어지던데.......
id값을 user로 하면 뭔가 에러가 나고..
현재 id값을 phone으로 해서 컬럼명이
phone_cell_phone_number로 되어있습니다ㅋ

**Comment by akasima** [comment]
https://github.com/xpressengine/xpressengine/issues/606 여기 이슈에서 처리되었을것 같습니다.
확장필드 입력에 대해선 입력폼에 설명을 추가하는 방법으로 가이드 될 수 있게 개선했습니다.

![2017-11-22 5 19 45](https://user-images.githubusercontent.com/5836237/33116774-5be4a1f2-cfa9-11e7-8155-3727eeeed311.png)
