### ISSUE TITLE
24버전 새 설치 후 page 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#585]
24버전 설치 후 page 플러그인으로 메뉴 생성한 경우 해당 페이지 접근시 에러 발생합니다.

documents 테이블에 locale 정보가 입력되지 않아 발생한 문제로 보입니다.
page 메뉴 생성할 때 사용하는 locale 은 사이트 기본 언어로 보이며 이 정보가 없어 발생한 문제 같습니다.

**Comment by jhyeon1010** [comment]
xpressengine/plugin-page#13 에서 수정되었습니다.
