### ISSUE TITLE
XE3 설치 오류

### ISSUE THREAD

**Issue by study4u** [xpressengine/xpressengine#589]
XE3 설치과정중에 아래와 같은 오류로 설치가 안됩니다.
$ php -r "copy('http://start.xpressengine.io/download/installer', 'installer');" && php installer install

PHP Parse error:  syntax error, unexpected '?' in /xe3/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

**Comment by jhyeon1010** [comment]
`??` operation 때문에 오류가 발생한것 같습니다. 해당 구문은 php 7 버전 이상에서 지원됩니다. 설치하시는 환경의 php 버전이 7버전 이상인지 확인 부탁드립니다.
