### ISSUE TITLE
정상적으로 설치되었지만, 그 어떤 메뉴도 출력되지 않음.

### ISSUE THREAD

**Issue by haegyung** [xpressengine/xpressengine#59]
# 동작  
1. 권장하고 있는 설치 방법, 최신 버전을 다운 받아 설치하는 방법, git clone 을 이용한 설치 방법을 따라 설치합니다.
2. 정상적으로 설치 됩니다.

# 발생 문제  
1. 정상 설치후 첫 접속 화면에서, **어떠한 메뉴**도 출력되지 않습니다.

# 설치환경  
WebServer : nginx/1.4.6
PHP Version : 5.5.9-1ubuntu4.14
Debug Mode :
Cache Driver : file
Document Root : /var/www/xelab
Maintenance : Off
TimeZone : Asia/Seoul

**Comment by 1Sam** [comment]
저도 같은 문제를 겪고 있으며, 게시판 글 작성이 안됨.

**Comment by YJSoft** [comment]
https://yjsoft.me/
역시 메뉴가 전혀 출력되지 않습니다. 설치 과정중 누락된 것이 있는 것으로 보입니다.

**Comment by 1Sam** [comment]
https://github.com/1Sam/xpressengine/commit/72ba40dad0e17514ee6e9343e03cd0e7f14f756e

일단 이렇게 수정해 보세요...

**Comment by khongchi** [comment]
dev3에서 처리되었습니다.

**Comment by haegyung** [comment]
수고하셨습니다.

**Comment by haegyung** [comment]
@khongchi dev3 설치해 봤는데 동일한 현상이 나타납니다. ㅠㅠ

**Comment by akasima** [comment]
@haegyung 어려울 수 있겠지만 가능하다면 해당 서버에 직접 설치하면서 문제를 확인하고 싶은데요.
설정이 가능하다면 developers@xpressengine.com 으로 정보를 받았으면 합니다.

현재 window 7 + XAMPP, Cafe24 가상 서버 정도에서 설치 테스트는 문제 없었는데요.
당장은 가능하지 않더라도 세팅 환경 내용등 메일로 주시면 해결점을 찾아 보도록 하겠습니다.

**Comment by haegyung** [comment]
@akasima 방금 보냈습니다. 더 필요한거 있으시면 알려주세요~

**Comment by 1Sam** [comment]
저는 @else 문을 넣어서 메뉴를 억지로 나타나게 하고 있습니다.
xe/plugins/alice/views/theme.blade.php

39번째줄에
                                @foreach($mainMenu->getTree()->getTreeNodes() as $menuItem)
                                @can('visible', [$menuItem, $mainMenu])
                                
                                
                                @else

이렇게 처리했습니다. ㅡ.ㅡ

**Comment by akasima** [comment]
확인했습니다.

php 에서 사용하는 mysql 드라이버 버전 문제입니다. 

https://github.com/xpressengine/xpressengine/blob/master/core/src/Xpressengine/Menu/MenuItemPolicy.php#L60 에서 `$item->activated === 1` 을 비교하는 구문에서 `$item->activated` 가 문자열 1 을 반환해서 생기는 문제 입니다.

php5-mysqlnd 이 설치 되어 PHP 가 구동 되어야 하는데 php5-mysql 이 설치되어 발생된 문제 입니다.

http://php.net/manual/en/mysqlnd.install.php PHP 5.4.0 부터 mysqlnd 가 설치 되는것으로 되어 있지만 간혹 PHP 에 php5-mysql 이 설치되네요.

core 에서 대응 가능한 방법을 찾아보겠습니다.

**Comment by haegyung** [comment]
@akasima 감사합니다. 수고하셨습니다.
저는 어서 mysqlnd 를 설치하도록 하겠습니다.

**Comment by akasima** [comment]
이 문제에 대해서 인스톨러에 언급을 해야겠네요. 

관련 문제는 코드를 수정해서 처리했습니다.
협조에 감사드립니다.
