### ISSUE TITLE
관리자가 게시판에서 게시물을 복사시

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#599]
게시물 하나를 선택한 후

관리 버튼을 누르고 게시물 복사를 실행하면

jquery-1.11.3.js:9664 POST https://xn--z92bxyh5hlbx19c56ak97a.kr/settings/module/board@board/copy 403 ()

오류가 뜹니다.

확인부탁드립니다

**Comment by akasima** [comment]
음.. 제가 테스트할 땐 정상동작 됐는데요. 남겨주신 url로 이동해 봤지만 접근할 수 없어 확인이 추가로 확인할 수 없네요.

오류를 확인하기  위해선 javascript 의 jquery 내용 보다는 `storage/logs/laravel- * .log` 파일의 오류 정보를 주시는게 더 좋을것 같습니다.
