### ISSUE TITLE
관리페이지 권한 설정에서 그룹 등록시 오류발생.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#600]
한글이름을 가진 그룹을 
관리페이지 권한 설정시 아래와 같은 오류가 발생하여 등록이되지 않습니다.

기본 오류는 아래와 같습니다.
`ErrorException (E_NOTICE) Undefined index: accessRating`

디버그 모드에서 출력되는 ERROR 는 아래와 같습니다.
`[02:01:39] LOG.error: Undefined index: accessRating {"userId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","email":"xe3_admin_account@email.address","exception":{}}`

디버그 모드에서 출력되는 Exceptions 는 아래와 같습니다.
`/home/public_home/app/Http/Controllers/SettingsController.php#176`

날씨 무척춥습니다!
건강조심하세요/

**Comment by jhyeon1010** [comment]
확인해본 결과 권한의 등급부분에 선택된 값이 아무것도 없을때 문제를 발생시키는것으로 확인되었습니다.
해당 문제의 수정은 간단한데, 권한을 처리하는 부분에 문제가 있어보여 관련된 부분을 함께 수정해야할것 같습니다.

**Comment by jhyeon1010** [comment]
추가된 관리권한 정보 처리도 등록시에는 `settings_permission` 를 사용하고, 사용시에는 `permission` 을 사용하도록 되어 있는것으로 보입니다.

**Comment by mintplo** [comment]
@jhyeon1010 혹시 permission 관련 내용은 beta.26 또는 beta.27 버전 업그레이드를 하지 않아도 해결할 수 있는 문제일까요?

**Comment by jhyeon1010** [comment]
@mintplo 버전 업그레이드 없이 해결하긴 어렵지 않을까 생각됩니다.

**Comment by jhyeon1010** [comment]
@mintplo 수정된 내용은 `/home/public_home/app/Http/Controllers/SettingsController.php` 176 line 에 `$rating = array_get($inputs, 'accessRating', Rating::SUPER);` 입니다.
버전업 전에는 해당 코드를 직접 수정하여 사용하시면 될거 같습니다.
기타 문제가 있어보였던 요소들은 정책적인 요소로 판단되어 유지하기로 하였습니다.
