### ISSUE TITLE
gulp, webpack 정리

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#603]
- [x] 미사용 패키지 제거
- [x] gulp task를 webpack으로 변경
- [x] eslint standard 적용 https://standardjs.com
- [x] `window.$` 제거
- [x] 플러그인에서 webpack 사용 시 코어의 코드와 중복 제거 #686
- [x] 모듈 포맷 정리

**Comment by findstar** [comment]
gulp 를 없애고 webpack을 최신에 맞게 잘 정리해주세요!

**Comment by bnu** [comment]
@findstar webpack의 장점은 충분한데, 별도의 빌드 과정을 거치지 않고도 systemjs 등이 지원하는 dynamic load가 그립네요.
우선은 불필요한 것들만 정리했습니다.

JS 파일들의 모듈화를 정리하고 webpack을 버리거나(또는 선택적으로 사용할 수 있는 여지만 남겨두거나) webpack으로 완전히 전환할 계획입니다.

**Comment by bnu** [comment]
- webpack import 사용 시 공통 모듈이 중복으로 번들되어 인스턴스가 분리되는 문제 있음(validator)
- DynamicLoadManager와 연계 불가
- DynamicLoadManager에서 대상 로드 후 로드한 모듈/파일의 인스턴스 등을 받을 수 없음
- DynamicLoadManager에서 로드한 대상이 global에 노출 될 수 있음
- DynamicLoadManager가 의존성 관리가 불가능
- Utils가 global에 노출 됨 -> XE.Utils
- ui component 등에서 사용하는 특정 기능이 동작하는데 사용하는 CSS class/id 이름 규칙이 뒤섞여 있음
  - `__xe-selector-name`으로 통일해야 함
- commonjs, amd, es6 등 모듈 정의가 뒤섞여 있음

**Comment by bnu** [comment]
- webpack 유지
- `DynamicLoadManager`를 제거하고 SystemJS로 대체
  - webpack으로 번들된 모듈은 `SystemJS.set()`으로 SystemJS가 인식할 수 있도록 함

todo (개별 이슈로 분리)
- gulp task를 webpack으로 변경
- 모듈 정리 : 모듈 포맷, chunk
- global에 노출된 Utils 이동

**Comment by bnu** [comment]
- ui-component를 현재 정리할 수 없어 SASS 변환을 gulp에서 처리하는 것으로 유지 함.
- systemjs 및 ui-component 정리가 되어야 나머지 부분의 처리를 마무리 지을 수 있을 것.
- 'assets/vendor/*'는 제거하거나 일부를 dll 전환
- 충분히 webpack을 활용 않거나 구조적 문제가 있으나, 현재 단계에서는 현재 수준에서 마무리하고 다음 단계들을 거치면서 정리해나가야 함

**Comment by bnu** [comment]
현재 상태에서 기능 동작 및 오류 체크 후 1차 마무리하고 이슈 종료 예정

**Comment by bnu** [comment]
webpack 사용 여부를 결정하면서 남기는 글 입니다.

webpack의 장점은 충분합니다.

의존성을 해결해주는데 있어서는 런타임에서 결정하는 것보다 신뢰성이 높고, 다른 툴을 이용하는 것보다 webpack 프로젝트의 신뢰성이 높다고 봅니다. 무엇보다도 이미 webpack이 적용되어 있어서 입니다.

webpack의 단점은 명확합니다.
rollup 등 다른 툴도 마찬가지 입니다.

소스가 알아볼 수 없게 바뀌고, 어디에 있던 소스인지도 알 수 조차 없습니다.
sourcemap을 사용하면 파악 가능하지만 production 모드로 sourcemap 없이 배포될 것이며,
자신의 사이트에서 글자 하나 바꾸고 싶은 비개발자에게는 접근이 불가능한 영역이죠.

webpack의 명확한 단점에도 불구하고 유지합니다.
webpack을 거친 코드의 수정에 대한 요구가 크지 않은 부분이거나 확장할 수 있도록 개선할 수 있을 거라 판단했습니다.

webpack이 정말 필요한가에 대한 의문과 webpack을 모두가 사용할 수 없다는 것은 너무나도 큰 걸림돌이었습니다. '이 좋은 webpack을 빼야할까?'에 대한 고민이 아니라 'webpack 이걸 정말 써야하나?'에 대한 고민이었고, 이득은 취하고 dynamic loading을 위해 SystemJS(또는 RequireJS 등)을 사용할 수 있도록하고, 접근이 쉽지 않은 문제는 해당 부분의 코드 수정 필요성을 낮추고 확장성을 제공해나가는 방향으로 결정했습니다.

서비스였다면 고민 없이 webpack을 사용했겠지만, 그렇지 않기 때문에 앞서 말한 단점은 매우 큰 부분이라 생각했습니다.
