### ISSUE TITLE
Alice 테마에서 컬러셋을 Default로 변경할 수 없는 버그가 있습니다.

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#604]
- Default
- Blue
- Red

Blue나 Red 컬러셋으로 변경 후 Default 컬러셋으로 변경하려고 하면 변경이 되지 않습니다.

**Comment by jhyeon1010** [comment]
laravel 5.5 가 적용되면서 폼에서 전달된 값이 공백('') 일 경우 null 로 변경되게 되었습니다.
그런데 설정값 저장시 null 인 경우는 변경사항에서 제외처리 하도록 되어있어 해당 문제가 발생하게 된것입니다.
설정 저장 과정에서 null 값을 공백값으로 재변환하여 저장되도록 변경하였습니다.
