### ISSUE TITLE
대시보드에서의 대시보드편집시 새창과 팝업창

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#609]
대시보드에서 대시보드 편집시 XE위젯 박스 페이지가 동시에 새창과 팝업창으로 열립니다.
XE위젯박스 페이지가 팝업창으로만 열리게되면, 매번 팝업차단 해제를 해야하므로 새창으로만 열렸으면 좋겠습니다!

**Comment by jhyeon1010** [comment]
혹시 어떤 브라우저를 사용하시는지 종류와 버전을 알려주시면 감사하겠습니다.

**Comment by Laeng** [comment]
@jhyeon1010 

Chrome | 62.0.3202.89 (공식 빌드) (64비트) (cohort: 62_89_win) 입니다!

**Comment by jhyeon1010** [comment]
`a` 태그에 링크속성과 `onclick` 이벤트가 동시에 적용되어 창이 두개가 열리는 현상이 있었습니다.
클릭 이벤트를 통한 팝업만 열리도록 수정되었습니다. 우려하시던 팝업차단 해제문제는 없을것으로 보입니다.

**Comment by Laeng** [comment]
고생하셨습니다!
