### ISSUE TITLE
gitignore가 적용되지 않아야 할 부분이 추가되어야할것같습니다.

### ISSUE THREAD

**Issue by haneu89** [xpressengine/xpressengine#610]
xe3설치 이후
예를들어
`config/production`
부분에 설정정보가 저장되어 이부분 자료들은 .gitignore가 제가되어야
다른곳에서 pull받아도 정상 동작할것 같은데

문제는 이부문 말고도 한 100개가 생성되던데 어느부분을 해지하여야
git으로 코드를 공유할 수 있을지 모르겠네요.

**Comment by jhyeon1010** [comment]
`config/production` 의 경우 환경에 따라 다른 설정정보를 사용하기 위한 요소입니다.
예를 들어 어떤 웹어플리케이션이 서비스중에 있는데 개발/수정 작업을 위해 로컬pc 에 코드를 복제하여
작업을 진행하는 경우, 로컬의 데이터베이스 연결정보와 서비스상의 데이터베이스의 연결정보가 다를것입니다.
또한 로컬에서는 개발을 위해 `debug` 모드를 `true` 로 설정하고 서비스 사이트는 `false` 로 설정할것입니다.
이런 경우 git 등을 통해 소스코드가 업데이트 되면 문제가 발생하므로 `.gitignore` 에 적용한 것입니다.

**Comment by haneu89** [comment]
그렇다면 git 을 통하여 하나의 웹 어플리케이션을 협업 하려면
어떤 부분까지 공유해야 하는지 명시가 되어 있으면 좋겠습니다.

답변해주신 내용은 이해 했습니다만. 같은 설정정보를 가지고 여러대의 pc또는
여러명이랑 함께 git을통하여 협업할때 필요한 부분이 어디인지
알려주시면 좋겠습니다.

**Comment by akasima** [comment]
XE3 로 별도의 git 저장소를 사용해 개발할 경우 config/production 디렉토리에서 설정 파일을 강제로 밀어 넣는 방법을 시도해 보시는것도 좋겠습니다.

```bash
cd config/procuntion
git add -f *
```

파일 추가할 때 -f 옵션을 사용하면 .gitignore 와 상관없이 커밋 가능할 것 같습니다.
```
       -f, --force
           Allow adding otherwise ignored files.
```
