### ISSUE TITLE
완료)XE3 매뉴얼 테마 부분 수정이 필요합니다.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#611]
https://xpressengine.gitbooks.io/xpressengine-manual/content/ko/component-theme.html

## 빈 테마생성
```
$ php artisan make:theme my_plugin/theme 'First Theme'
```
테마 생성 예제가 잘못되었습니다!
`<path>` 에 `plugins/` 을 추가해야만 생성할 수 있습니다!!!

```
$ php artisan make:theme plugins/my_plugin/theme 'First Theme'
```

**Comment by findstar** [comment]
👍

**Comment by findstar** [comment]
https://github.com/xpressengine/xpressengine-manual/pull/1 PR 올렸습니다.
