### ISSUE TITLE
설치시 diplayname 길이 검사 필요합니다.

### ISSUE THREAD

**Issue by haegyung** [xpressengine/xpressengine#613]
설치시 displayname 을 한글자만 입력하면 설치 동작은 가능한데, 최종적으로 설치가 되지 않습니다. (DB는 생성됩니다.)

다음 1) 또는 2) 중 하나의 조치가 필요할 것 같습니다.

1) displayname 을 한글자만 해도 좋게 함.
2) displayname 을 설치전에 검사해서 몇글자 이상 입력하도록 해서 설치가 정상적으로 진행되도록 함.

**Comment by akasima** [comment]
display_name을 검사하지 않도록 수정했습니다.
install controller 에서 display_name validator 를 적용할 방법이 없어 부득이 검사하지 않는 방법으로 처리했습니다.

더 문제는 Handler 에서 validator 처리하는 것으로 보이는데.. 이 부분은 후에 Controller 에서 확인하는 방식으로 수정할 계획입니다.
