### ISSUE TITLE
파일시스템 기본으로 s3 설정시 (재업)

### ISSUE THREAD

**Issue by sangemi** [xpressengine/xpressengine#617]
디폴트로 s3로 설정했을 경우
메뉴를 클릭해서 페이지를 이동할때마다
아래 링크의 증상(fstat() ... 오류)이 나타납니다.
https://stackoverflow.com/questions/30738520/league-flysystem-fstat-expects-parameter-1-to-be-resource-object-given

25버전으로 실행했습니다.

(boonzero.com 사이트 내에서 이동하면 오류를 볼 수 있는데)

Xpressengine\Menu\Repositories\MenuRepository findWith
…/core/src/Xpressengine/Support/helpers.php

Xpressengine\Menu\Repositories\MenuRepository cacheCall
…/core/src/Xpressengine/Menu/Repositories/MenuRepository.php

Xpressengine\Menu\Repositories\MenuRepository storeCacheKey
…/core/src/Xpressengine/Support/CacheableEloquentRepositoryTrait.php54

Xpressengine\Menu\Repositories\MenuRepository getCacheKeys
…/core/src/Xpressengine/Support/CacheableEloquentRepositoryTrait.php69

Illuminate\Filesystem\FilesystemAdapter put
…/core/src/Xpressengine/Support/CacheableEloquentRepositoryTrait.php138

즉 마지막
core/src/Xpressengine/Support/CacheableEloquentRepositoryTrait.php
파일의
```
 protected function getCacheKeys()
    {
        $filesystem = $this->resolveContainer('filesystem.disk');
        if (!$filesystem->exists($this->getKeyfile())) {
            $filesystem->put($this->getKeyfile(), null);
        }
 
        return json_decode($filesystem->get($this->getKeyfile()), true) ?: [];
    }
```

이부분이 최종입니다.

$filesystem->put($this->getKeyfile(), null);
널값이 아니라 string? 이 들어가야할것 같은데...확인부탁드립니다.

참고 // https://stackoverflow.com/questions/30738520/league-flysystem-fstat-expects-parameter-1-to-be-resource-object-given

**Comment by jhyeon1010** [comment]
null 이 들어가던 부분을 공백 문자로 변경하였습니다.
