### ISSUE TITLE
created_at on update CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#619]
이것은 데이터베이스 extra 옵션으로 적용되어 레코드 변경시 created_at 이 갱신되는 문제를 
일으킵니다.
timestamp 타입 컬럼이 nullable 로 지정되지 않은 경우 발생하는 문제로
`->timestamps()` 를 사용하거나 
```
->timestamp('created_at')->nullable(); 
->timestamp('updated_at')->nullable(); 
```
처럼 작성해야 합니다.

기존 사용자분들은 데이터베이스에서 해당 옵션을 제거하셔야 합니다.

**Comment by sangemi** [comment]
기존 테이블들에 대해서,
![image](https://user-images.githubusercontent.com/8413799/32824987-7f36e47c-ca26-11e7-85dc-61039d2a2f2f.png)
널갑 입력가능토록 & 기본값은 0000-00-.. 그대로.

**Comment by sangemi** [comment]
위 커밋한것처럼 모든 테이블의 모든 create_at null값 체크 한 상태에서도 계속 create_at 이 갱신되었는데,

테이블 속성 중
![image](https://user-images.githubusercontent.com/8413799/32826410-9b84f88a-ca2b-11e7-9feb-27d30e006a06.png)
위 current_times 를 (ON UPDATE)로 변경하니 이제 갱신되지 않습니다.

참고바랄게요!!

**Comment by jhyeon1010** [comment]
@sangemi 타임존이 `UTC` 로 설정되지 않았는지 확인 바랍니다.
