### ISSUE TITLE
설정 파일을 이용한 설치 매뉴얼 갱신 요청 및 버그 신고

### ISSUE THREAD

**Issue by mintplo** [xpressengine/xpressengine#620]
Xpressengine 매뉴얼

설치하기 페이지에 '설정 파일을 이용한 설치'

XE Beta 버전 25에서 php installer make로 config을 생성해서 이용하면

database 섹션에 driver를 누락한 것으로 오류가 발생합니다.

이에 관련된 매뉴얼 갱신 요청합니다.

또한

php installer install --config=.xe_install_config.yaml --no-interact --skip-download

위와 같은 명령으로 설치를 진행하면

<img width="226" alt="kakaotalk_2017-11-20-14-22-10_photo_51" src="https://user-images.githubusercontent.com/5382029/33003463-400b38bc-cdfe-11e7-9ff4-254f6de991da.png">
<img width="856" alt="kakaotalk_2017-11-20-14-22-11_photo_51" src="https://user-images.githubusercontent.com/5382029/33003464-4030bd94-cdfe-11e7-9980-7a7d0b584347.png">

위와 같은 오류가 발생합니다.

Admin 계정 관련 설정 이후 실제로 설치를 진행할 때 문제가 발생하는 것으로 보입니다.

php artisan xe:install 명령으로 정보를 직접 입력해 설치를 진행할 때는 문제가 없었습니다.

**Comment by jhyeon1010** [comment]
installer 쪽에 미반영된 코드가 있었네요. 수정 적용 하였습니다.
감사합니다.

**Comment by jhyeon1010** [comment]
변경된 항목은 `driver` 항목 추가와 `displayName` -> `display_name` 입니다
