### ISSUE TITLE
다국어를 한글만 지원하도록 설정하는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#624]
config/xe.php 의 `lang` -> `locales` 설정을 변경해서 다국어 처리를 한국어만 지원하는 사이트로 설정하려고 할 때 설정이 적용되지 않습니다.

메뉴 만들 때 메뉴 이름 넣는 기능을 기준으로 테스트 했습니다.

config/xe.php 에서 설정을 변경할 때는 잘 되지만 config/production/xe.php 에서 변경할 때는 적용되지 않습니다.

**Comment by jhyeon1010** [comment]
언급된 현상은 환경에 따른 설정 배열이 기본 설정 배열에 병합하는 과정에서 키값을 기준으로 처리되기 때문에 나타나는 현상입니다. 이와 같은 현상을 회피하기 위해서는 키가없는 배열형태의 값이 아닌 scalar 타입의 값을 사용해야 합니다.
하지만 위와 같은 설정 처리가 필요한지는 의문입니다. 한글만 등록해서 사용하면 될 것으로 생각됩니다.
