### ISSUE TITLE
javascript valiator 에서 체크 후 focus 처리

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#629]
validator 에서 체크 후 문제가 있는 경우 griper 를 통해 toast/form 함수를 사용해 메시지를 출력해주는데요.
toast 를 사용할 경우 사용자가 출력된 메시지를 보고 시스템 에러로 생각하는 경우가 많은 습니다.

사용자가 입력 데이터에 문제가 있다는걸 명확히 확인할 수 있도록 메시지 개선이 필요해 보이며 문제가된 입력요소에 focus 처리가 되면 좋겠습니다.

![2017-11-24 12 17 33](https://user-images.githubusercontent.com/5836237/33194192-7a87f546-d111-11e7-9e2e-e01bc6a9b071.png)

**Comment by jhyeon1010** [comment]
메시지를 사용자가 원하는 방식으로 처리할 수 있도록 확장기능을 추가했습니다.
```
XE.validator.extendAlertType("alert", function ($el, message) {
   alert(message);
});
```
