### ISSUE TITLE
언어 설정에 따른 html lang 정의 필요

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#635]
웹급근성 진단하면서 <html lang="kr">, <html lang="en"> 같이 html 태그에 언어설정을 추가해야 한다는 지적이 있습니다. 사용하는 언어 설정을 lang 에 추가하려고 했지만 xe에서 사용하는 locale 정보는 한글이 ko 로 표기되어 있어 바로 사용할 수 없었습니다. lang 설정과 locale 정보를 매핑할 수 있는 방법이 필요할 것 같습니다.

**Comment by jhyeon1010** [comment]
html 태그에서 사용되는 한글언어 코드는 `ko` 로 시스템에서 사용하는 locale 과 같습니다.
