### ISSUE TITLE
Alice테마 변경 버튼 클릭해도 동작하지 않습니다.

### ISSUE THREAD

**Issue by sdkim** [xpressengine/xpressengine#639]
Alice테마 메인 이미지 변경하려고 변경 버튼 클릭해도 동작하지 않습니다.

**Comment by sdkim** [comment]
로고 변경도 안됩니다.

**Comment by jhyeon1010** [comment]
메인이미지와 로고변경은 테스트해 본 바로는 정상적인 것으로 보입니다.
변경하신 테마 설정이 메인페이지용 테마 설정인지 확인이 필요할것 같습니다.
