### ISSUE TITLE
첨부파일에서 첨부파일 구분 기능

### ISSUE THREAD

**Issue by wizone** [xpressengine/xpressengine#64]
파일첨부를 통해서 이미지나 , 한글파일, 엑셀파일등을 첨부할 수 있습니다.
문제는 게시글을 작성할때 내용중에 이미지가 들어가게 되는 경우들이 많습니다.
그리고 해당 내용에 사용자들이 다운받아야 할 첨부파일이 같이 첨부가 된다고 하면
현재로선 이미지와 함께 첨부파일들이 같이 노출이 되는 상황입니다.
사용자들은 첨부파일외에 불필요한 이미지들까지 다운을 받게 되는 상황이 발생하기도 하지요.
물론 방법이 없진 않습니다. 내용설명에 사용되는 이미지를 서버에 올려 놓고 해당 이미지 경로를 사용해서 내용작성시 활용을 하면 되니까요.
하지만 이건 html이나 기본전 홈페이지 사용법을 알고 있는 사람들에 국한되는 부분인지라..

파일첨부시 체크박스 하나 더 둬서 해당 파일을 첨부파일목록에 노출시킬지를 선택하게 하면 어떨까 합니다.
선택된 첨부파일만 첨부파일 목록에 노출이 된다면 좋지 않을까 생각을 해봅니다.

**Comment by akasima** [comment]
에디터 이슈인것 같습니다. 에디터 관련 이슈 처리할 때 참고하겠습니다.

**Comment by akasima** [comment]
업로드한 파일에 대해서 파일별로 다운로드 설정을 하는것에 대해서 처리할 수 없다고 결론 지었습니다.
업로드 파일 다운로드 가능 여부 기능 제공은 에디터나 게시판이 아닌 좀더 다른 방식으로 처리해야할 것 같으며 코어 개발에서는 제공 안하는것으로 하고 이슈 닫겠습니다.
