### ISSUE TITLE
Alice 테마 모바일 다국어 클릭 안됩니다.

### ISSUE THREAD

**Issue by sdkim** [xpressengine/xpressengine#640]
Alice 테마 모바일에서 볼때 하단의 다국어 클릭 하면 한국어,영어가 선택할 수 있게 나와야 되는데 안됩니다.

**Comment by jhyeon1010** [comment]
사용하시는 디바이스의 종류와 버전을 알 수 있을까요?

**Comment by sdkim** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
노트4입니다
Daum 메일앱에서 보냈습니다.


--------- 원본 메일 ---------
보낸사람: jhyeon1010 <notifications@github.com>
받는사람: xpressengine/xpressengine <xpressengine@noreply.github.com>
참조: sdkim <jung945@hanmail.net>,Author <author@noreply.github.com>
날짜: Fri Dec 15 17:00:01 GMT+09:00 2017
제목: Re: [xpressengine/xpressengine] Alice 테마 모바일 다국어 클릭 안됩니다. (#640)



	사용하시는 디바이스의 종류와 버전을 알 수 있을까요?
