### ISSUE TITLE
xe3 홈페이지 가입이 안됩니다.

### ISSUE THREAD

**Issue by sdkim** [xpressengine/xpressengine#641]
xe3 홈페이지 로그인 하려고 가입하려고 하면  system error  라고만 뜨고 가입이 안됩니다.

**Comment by akasima** [comment]
신규 설치 환경에서 테스트 해봐야겠네요. 
테스트 후에 말씀드리겠습니다.

**Comment by jhyeon1010** [comment]
갱신되지 않은 플러그인이 있었네요. 처리되었습니다.
