### ISSUE TITLE
이메일 발송할 때 스킨 사용

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#642]
사이트에서 발송되는 이메일 디자인을 플러그인에서 변경할 수 있도록 처리
skin 이나 디렉토리를 지정할 수 있도록 수정

**Comment by jhyeon1010** [comment]
코어에서 발송처리하는 회원 메일(ex. 비밀번호 변경)을 변경하려면 `setView` 메서드에 사용할 view 지정으로 해결 할 수 있습니다.
```
Xpressengine\User\Notifications\ResetPassword::setView('custom::your.view');
```
메시지 객체 변경등 좀 더 많은 변경을 원하는 경우 `setMessageResolver` 메서드에 호출가능한 함수등을 등록하여 처리할 수 있습니다. 이때 전달되는 인자는 `MailMessage` 객체와 메시지에 사용되는 데이터들 입니다.
