### ISSUE TITLE
댓글달 때 ckediter 대신 textarea 를 사용할 수 있었으면 좋겠습니다. 

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#644]
ckediter 는 정말 무궁무진하지만, 
댓글을 달때에는 사용하지 않는 여러 기능들이 많고 지저분해 보입니다.

댓글 창에서 ckediter 를 비활성화 할 수 있는 기능이 추가되었으면 좋겠습니다.

**Comment by jhyeon1010** [comment]
설정을 통해 ckeditor 대신 textarea 를 사용할 수 있습니다.
`관리자 > 사이트 맵(게시판 선택) > 상세설정` 으로 이동하면 게시판 상세 설정에서 `댓글` 항목이 있고 같은 위치에 댓글 설정으로 이동 할 수 있는 버튼이 있습니다.
댓글 설정에서 `에디터` 탭으로 이동 후 편집 버튼을 통해 textarea 를 선택할 수 있습니다.

**Comment by Laeng** [comment]
오예!!!
고맙습니다!!
