### ISSUE TITLE
지금 배포중인 것이 정식버전인지요?

### ISSUE THREAD

**Issue by wcmskorea** [xpressengine/xpressengine#65]
아님 아직 베타버전인가요?

**Comment by qw5414** [comment]
아직 베타도 아닌, 개발자 버전입니다.

**Comment by bnu** [comment]
개발자 프리뷰 버전이며, 이 버전에서는 일반적인 사용이 어려울 수 있는 큰 변경사항이 많은 버전입니다.

**Comment by xharpenParksuhyeon** [comment]
확인 결과, #65는 코드 변경 이슈가 아니라 배포 버전 문의입니다. 따라서 3.1.x / 3.0.x에 백포트하거나 추가 배포할 변경사항은 없습니다. 현재 건은 릴리스 브랜치로의 코드 반영 대상이라기보다 배포 상태 안내로 답변하는 것이 맞습니다.
