### ISSUE TITLE
회원 토글메뉴 활성화

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#650]
설치할 때 회원 토글메뉴가 활성화되어 있지 않습니다.
기능을 모르는 사용자는 사용할 수 없을 것 같네요.
설치할 때 기본으로 제공되는 토글메뉴가 활성화 되었으면 좋겠습니다.

<img width="1338" alt="2017-12-22 3 21 02" src="https://user-images.githubusercontent.com/5836237/34287642-dde2fa98-e72b-11e7-8abc-29d6e30fdcd3.png">

그리고 회원 토글메뉴가 화면 전체에 나오게 되어 있는데요. 
게시판 처럼 팝업으로 보여지도록 개선이 필요해 보입니다.

<img width="1226" alt="2017-12-22 3 22 35" src="https://user-images.githubusercontent.com/5836237/34287663-0a7189a8-e72c-11e7-8daf-c7f933074b2e.png">

**Comment by jhyeon1010** [comment]
#660
