### ISSUE TITLE
CkEditor 플러그인 이미지 편집 툴 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#652]
이미지 편집 툴을 "사용함"으로 설정하고 그 기능을 사용하려고 할 때 
plugins/ckeditor/components/EditorTools/ImageResizeTool/assets/vendor/jquery-ui.js 가 없다는 오류가 발생합니다.

  
![2018-01-03 10 39 34](https://user-images.githubusercontent.com/5836237/34506701-77e04c96-f072-11e7-9670-3c6091379105.png)

**Comment by bnu** [comment]
fixed https://github.com/xpressengine/plugin-ckeditor/commit/dfeb37ba0a2154b97d7c2087073e2d45cf7fa2d1  https://github.com/xpressengine/plugin-ckeditor/commit/498ce44e65940b58e2a48de6e5e3cc1396f5d82e
