### ISSUE TITLE
플러그인 세팅중 자꾸 500 애러가 발생합니다.

### ISSUE THREAD

**Issue by kjy0922** [xpressengine/xpressengine#653]
simplestrap 플러그 인이 문제인지...

플러그인 전체 다 설치 하고 하나 하나 활성화 하면서 세팅 하고 있는데

자꾸 500 애러가 발생합니다.

http://www.sangsanghair.com

**Comment by jhyeon1010** [comment]
문제를 확인하기 위해서 에러 정보를 확인해야 할것 같습니다.
storage/logs/laravel-{날짜}.log 파일에서 오류내용을 확인하여 알려주시기 바랍니다.
