### ISSUE TITLE
게시판 주소(slug) 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#654]
* 게시판 플러그인 기본 설정과 해당 게시판 설정의 주소 방식을 문서 아이디로 변경하였지만 문서 아이디 방식과 같이 Slug 방식이 계속 반영되고 있습니다.
> https://www.xpressengine.io/qna/%EA%B2%8C%EC%8B%9C%ED%8C%90-%EC%A3%BC%EC%86%8C-%EB%B0%A9%EC%8B%9D?title_pure_content=slug

* 게시글의 URL은 문서 아이디 주소로 표현되지만 Slug 주소와 문서 아이디 주소가 둘다 유효한 상황입니다.
> https://www.xpressengine.io/qna/%EA%B2%8C%EC%8B%9C%EA%B8%80-%EC%A3%BC%EC%86%8C

**Comment by woongbin** [comment]
https://github.com/xpressengine/plugin-board/issues/199 issue에서 처리 예정
