### ISSUE TITLE
회원 목록 페이지에서 회원 토글 메뉴가 안 보이는 이슈

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#659]
![default](https://user-images.githubusercontent.com/1732040/34636624-5131fe86-f2e9-11e7-8c1a-79369e0c8d96.PNG)

크롬, 엣지, IE11 환경에서 테스트 해봤습니다. 이외의 브라우저에서는 잘 보이는지 확인 못해봤습니다.

**Comment by bnu** [comment]
이 문제는 TSBS의 `.table-responsive`의 영향이며, 테이블을 제대로(?) 표기하기 위한 부분이나, 회원 토글 메뉴를 우선으로 생각하여 임시 조치로 `.table-responsive`를 제거했습니다.
데이터 표시 방법의 개선이 필요 함.
