### ISSUE TITLE
회원 관리메뉴 일부 접속 불가.

### ISSUE THREAD

**Issue by Intrainos** [xpressengine/xpressengine#66]
curl installer, 730ebe5 에서 둘다 발생합니다.
____
`관리> 회원 > 회원목록` 접근시 빈 화면이 나옴. 에러 로그 `\nFatal error: An iterator cannot be used with foreach by reference in /var/www/xe3/core/src/Xpressengine/Member/Repositories/DatabaseRepositoryTrait.php on line 536`발생

`관리> 회원 > 그룹` 접근시 빈 화면이 나옴. 에러 로그 `\nFatal error: An iterator cannot be used with foreach by reference in /var/www/xe3/core/src/Xpressengine/Member/Repositories/DatabaseRepositoryTrait.php on line 487`

-----
WebServer : nginx/1.9.10
PHP Version : 5.6.99-hhvm
Debug Mode :
Cache Driver : file
Document Root : /var/www/xe3
Maintenance : Off
TimeZone : Asia/Seoul

**Comment by khongchi** [comment]
검토해보겠습니다. 감사합니다.

**Comment by khongchi** [comment]
dev3에서 수정되었습니다.
