### ISSUE TITLE
회원 토글 메뉴 표시 문제

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#660]
![2018-01-09 4 28 00](https://user-images.githubusercontent.com/6971375/34709331-2a2a5310-f55a-11e7-9069-d18ca3ed0c86.png)

회원 토글메뉴가 가로로 길게(100%?) 로 표시 되고 있습니다.

**Comment by bnu** [comment]
게시판 이슈
https://github.com/xpressengine/plugin-board/issues/154 이슈에서 함께 처리 함
