### ISSUE TITLE
filesystem이 s3이고 업로드 된 파일이 s3에서 삭제되었을 경우 에러메시지 대신 html을 다운로드 하는 문제

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xpressengine#67]
s3에 업로드 되었던 파일이 삭제되었을 경우 파일이 존재하지 않는다는 에러 메시지가 표시되는 대신 에러 메시지를 표시하는 HTML이 file id명으로 다운로드 되는 문제가 있습니다.

**Comment by jhyeon1010** [comment]
업로드된 파일을 표시하는 등의 처리는 각각의 페이지를 담당하는
패키지, 또는 플러그인이 담당합니다.
이는 각각의 페이지마다 권한등의 요소들이 다를 수 있으므로 코어는 기본적인 파일 업, 다운로드만 제공하고
이를 위한 부수적인 동작들은 모두 위임하는 형태로 구성되어 있습니다.
같은 문제가 여전히 지속되는 경우 문제가 발생하는 페이지와 상황등을
상세히 남겨주시면 감사하겠습니다.
