### ISSUE TITLE
git bash + composer + Xampp (Windows 10) 환경에서 객체없는 문제.

### ISSUE THREAD

**Issue by bjrambo** [xpressengine/xpressengine#676]
정상적으로 절차에 따라 설치를 완료하고 DB도 생성이 되었지만 XAMPP환경에서 객체가 없는 등 문제가 보입니다.

해당 문제는 비디오로 @akasima 님의 slack DM으로 보내드렸습니다.

비디오에서 나타나는 객체없음 오류는 일반적으로 해당 디렉토리를 읽어들이지 못할때 문제되는 .htaccess 문제로 보여집니다.

xampp가 업데이트 하면서 생겨난 문제일지.. 아니면 컴포저에서 htaccess 의 문제일지 감이 안잡히고, 로그인도 불가능한 상황이라 이렇게 도움을 요청드렸습니다.

읽어주셔서 감사합니다 :) 오늘도 좋은 하루 되세요

**Comment by akasima** [comment]
오늘 오전에 window7 에서 PHP 7.2 로 배포되는 XAMPP 설치해서 테스트 했을 땐 문제 없었는데요.
배포 중인 zip 파일 압축풀어서 테스트한게 다르긴 하지만.. 좀더 확인해 봐야겠네요.

**Comment by bjrambo** [comment]
배포중인 zip파일은 웹인스트롤 설치방법인가요?

**Comment by bjrambo** [comment]
htaccess 을 아파치가 재대로 읽어들이지 못한 결과였습니다.

@akasima 님께서 알려주신 `AllowOverride All`을 해당 아파치 옵션에 추가 해보니 정상적으로 작동을 했습니다.
