### ISSUE TITLE
ui component checkbox에 키보드 포커스 상태를 구분할 수 없음

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#682]
<img width="365" alt="2018-02-04 7 10 41" src="https://user-images.githubusercontent.com/53764/35776413-4505d328-09df-11e8-953f-866f9b553068.png">

체크박스로 포커스가 이동할 수 있으나 시각적으로 구분할 수 없음
스크린 리더도 확인해봐야 함
radio 등 다른 컴포넌트도 확인

**Comment by bi-kim** [comment]
스크린리더 확인 완료
