### ISSUE TITLE
에디터 소스보기 상태에서 글 등록 안되는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#683]
게시판 글 쓰기할 때 에디터의 소스보기 모드에서 글 등록 버튼을 클릭하면 동작하지 않습니다.
 
https://www.xpressengine.io/qna/%EA%B2%8C%EC%8B%9C%ED%8C%90-%EA%B8%80%EC%93%B0%EA%B8%B0-%EC%98%A4%EB%A5%98

**Comment by bnu** [comment]
https://github.com/xpressengine/plugin-ckeditor/issues/30
에디터와 에디터 툴 등과의 연계에서 CKEditor 전용으로 동작하는 위 이슈처럼
위지윅 모드에서만 툴이 동작하거나(소스 모드에서 오류) 이 이슈와 같이 저장하지 못하는 문제.

**Comment by bnu** [comment]
이슈 이동 함 https://github.com/xpressengine/plugin-ckeditor/issues/34
