### ISSUE TITLE
다국어 입력란에 double quote 사용 시 문제

### ISSUE THREAD

**Issue by bnu** [xpressengine/xpressengine#688]
![2018-02-08 4 55 39](https://user-images.githubusercontent.com/53764/35961429-040ce8b0-0cf1-11e8-815b-2eb941924967.png)

**Comment by jhyeon1010** [comment]
js에서 ajax 를 통해 받아온 값을 이용해 단순 문자열 연결방식으로 input 을 생성하기 때문에 발생하는 문제로 보입니다.
`createElement`, jQuery 의 경우 `$('<input>')` 으로 생성하여 사용하면 해결될 것으로 보입니다.
