### ISSUE TITLE
파비콘 등록 문제

### ISSUE THREAD

**Issue by dorajjang** [xpressengine/xpressengine#689]
파비콘 등록이 안되요.
.ico으로하면 이미지가 안뜨고 다른 확장자명으로 하면 이미지는 뜨는데 파비콘으로는 안되요

**Comment by akasima** [comment]
관리자 > 설정 > 기본 설정 (/settings/setting) 에서 ico 확장자로 등록한 경우 정상동작 되는걸로 확인되는데요.

xe 버전이 어떻게 되나요?

**Comment by dorajjang** [comment]
xe버전은 3.0.0-beta.27 이에요

**Comment by akasima** [comment]
제가 테스트할 때 파비콘 등록은 정상적으로 처리되고 있습니다. 
단순히 관리자 파비콘 등록 폼에서 이미지가 나오지 않는 문제인가요?
아니면 등록한 파비콘 ico 파일이 정상적으로 업로드 되지 않거나 사용 되지 않는 문제인가요?

**Comment by dorajjang** [comment]
등록폼에서 이미지가 나오지않고 업로드도 안되요

**Comment by akasima** [comment]
음.. 이미지가 나오지 않는건 정상이고.. 업로드가 되지 않는건 문제가 있는건데요. 저희쪽 4개 시스템에서 테스트 할 때 기능에 문제가 없어서 문제점을 찾는게 쉽지 않네요.

우선.. 파비콘 문제 일 수 있으니 NAVER 파비콘으로 테스트 해보면 좋겠습니다.
[favicon_naver.ico.zip](https://github.com/xpressengine/xpressengine/files/1750582/favicon_naver.ico.zip)

favicon_naver.ico.zip 파일 압축을 해제하고 favicon_naver.ico 파일을 업로드 해서 테스트 바랍니다.
제 개발환경에서 테스트할 때 아래와 같이 처리됩니다. 
![xpressengine3_favicon](https://user-images.githubusercontent.com/5836237/36579869-cc69f79a-18a8-11e8-9e14-2a2df1f2a960.png)

**Comment by dorajjang** [comment]
저장됐다고 하는데 안밖꿔요

**Comment by akasima** [comment]
Database 사용 가능하다면 아래 사항 확인 부탁드립니다.

1. 설정 확인
`select * from xe_confg  where name='site.default';`

여기에서 결과에 `vars` 를 보면 아래와 비슷할겁니다.
```json
{"defaultMenu":"a86091d9","homeInstance":"89b8aac0","site_title":"user::333a461e-e19f-497e-a525-32d1ad4ae89b","favicon":{"id":"0d099a9b-1874-4e62-9d8f-d0e3ee665ccf","filename":"favicon_naver.ico","path":"http:\/\/newxe.xedev.vm\/storage\/app\/public\/favicon\/default\/0d\/09\/local"}}
```

2. 데이터 확인
위 vars 데이터에서 `path`의 이미지가 정상인지 확인 바랍니다.
path 에 있는 이미지를 다운로드 받아서 이미지가 보이는지 확인 하면 될것 같습니다.

3. 사용 확인
웹사이트에서 소스보기 했을 때 아래 태그의 경로가 정상적으로 설정 되었는지 확인 해야 합니다.

``` html
<!-- ICON -->
<link rel="shortcut icon" type="image/x-icon" href="http://newxe.xedev.vm/storage/app/public/favicon/default/0d/09/local">
```

4. 파일 데이터 확인
`select * from xe_files where id = '0d099a9b-1874-4e62-9d8f-d0e3ee665ccf' `
`0d099a9b-1874-4e62-9d8f-d0e3ee665ccf` (파일 아이디)는 vars 에 있는 데이터를 입력해야합니다.

이 결과가 없는 경우. 또는 이 결과에 있는 path 등 정보가 1번의 설정 정보와 다른 경우엔 파일 업로드 과정에 문제로 볼 수 있겠습니다.

**Comment by dorajjang** [comment]
site.default vars 값이 없네요

**Comment by akasima** [comment]
@dorajjang 아.. 제가 query에 table 이름을 잘못 썼네요. ;; 쿼리 다시 확인 부탁드립니다.

**Comment by dorajjang** [comment]
@akasima
`select * from xe_config where name='site.default';`
`{"defaultMenu":"0cd7024e","homeInstance":"19d74539","site_title":"user::22f90335-2d4c-423e-b857-5fc0bd587cc2","favicon":{"id":"246e6422-ad3b-4ce0-897e-05912cf738da","filename":"favicon_naver.ico","path":"https:\/\/cubecm.com\/storage\/app\/public\/favicon\/default\/24\/6e\/local"}}`

`<link rel="shortcut icon" type="image/x-icon" href="https://cubecm.com/storage/app/public/favicon/default/24/6e/local">`

`246e6422-ad3b-4ce0-897e-05912cf738da | NULL      | e375c6df-d016-4eae-9fde-546cdea08939 | local | public/favicon/default/24/6e | local    | favicon_naver.ico | image/x-icon | 5430 |         0 |              0 | 2018-02-23 15:00:12 | 2018-02-23 15:00:12`

값은 잘 들어가있는거 같아요

**Comment by akasima** [comment]
@dorajjang

파미콘 이미지 경로에 404가 뜹니다. 
`https://도메인/storage/app/public/favicon/default/24/6e/local` 가 웹 브라우저로 접근할 때 파일에 접근할 수 없습니다.
웹서버 설정에 문제가 있는걸로 보입니다. 사용하는 웹서버전이 어떻게 되시나요?

**Comment by dorajjang** [comment]
@akasima 
웹서버 버전은 iis 10 입니다.

**Comment by akasima** [comment]
`storage/app/public/seo/e5/95/2018021612535132c516bb34930c063cde3e65be6f1809d6f0d7d0.png`  여기 파일에 접근이 되는걸로 봐서 `storage/app/public/favicon/default/24/6e/local` 파일이 확장자가 없어서 발생한 문제 일 수 있겠네요.

favicon 업로드할 때 확장자를 그대로 사용하는 방법에 대해서 확인해 보겠습니다.
