### ISSUE TITLE
사이트 메뉴 편집에서 만든 메뉴에서 CSRF 코드 삽입

### ISSUE THREAD

**Issue by Hann** [xpressengine/xpressengine#691]
[이 부분](https://xpressengine.gitbooks.io/xpressengine-manual/content/ko/routing.html)을 참고해서 사이트 메뉴 편집에서 만든 메뉴에서 CSRF 코드 삽입을 시도하고있습니다.

`form`에 아래 두 코드 다 넣어서 테스트 해보았는데 안됩니다.

       <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
       <input type="hidden" name="_token" value="{{ csrf_token() }}">

Alice theme에서 수정해서 작업 중입니다. `설정대쉬보드`->`사이트 메뉴 편집` -> `메뉴추가`로 url를 등록하고 그 창에서 제공하는 에디터에 `form`을 집어넣는 식으로 작업을 진행했는데요.

1. 이렇게 접근해서 작업하는게 맞는지 (아니라면 어떻게 접근해야하는지)
1. csrf는 코드는 어떻게 삽입해야하는지 궁금합니다.

**Comment by Hann** [comment]
@akasima 예 메뉴 추가 후 페이지 구성에 대한 문의입니다. 제 경우 그 안에 `<form>`이 들어가있습니다. 
말씀해주신대로 아래와 같이 표현됩니다. 제가 value안에 값이 들어가있어야 한다고 예상했습니다.

     <input type="hidden" name="_token" value="{{ csrf_token() }}">

**Comment by akasima** [comment]
`<form>`이 포함된 출력을 위해 만든 파일이 어떻게 실행 되고 있는지 궁급합니다.

메뉴에 폼함시키고 controller 를 만들고 Presenter(View) 를 통해 `form` 이 있는 blade 파일을 불러와 처리하고 있는건가요?

웹 브라우저에서 `<input type="hidden" name="_token" value="{{ csrf_token() }}">` 이 출력 된다면 Presenter(View)를 사용하지 않았기 때문으로 생각됩니다.

**Comment by Hann** [comment]
네 말씀하신대로 Dashboard 에서 맨 위 처음 질문의 스텝대로 만들었기 때문에 Controller를 만들어서 표현하지 않았습니다. 
그리고 제가 작성한 html elements는 전부 DB에 저장된 것 또한 확인했습니다.

이렇게 한 이유는 아래와 같습니다.
1. 상단에 메뉴&대쉬보드에 리스팅되어야함
1. 비개발자가 GUI로 일부 내용을 수정할 수 있어야함

blade template로 작성하지 않아서 안나오는 것은 이해하고있었나, 제가 접근한 방법으로는 아예 불가능한것인지 궁금합니다.

**Comment by akasima** [comment]
@Hann 네. html 이 DB 에 있다면 blade 문법은 사용할 없을 것 같습니다. 따라서 `{{csrf_token()}}` 이 처리되지 못하구요.
form submit 을 바로 하지 말고 ajax 통해서 하는게 좋겠습니다.

```javascript
var data = {};
window.XE.ajax({
        url: 'url',
        type: 'post',
        dataType: 'json',
        data: data,
        success: function (data) {
          // 결과 처리
        }
      });
```

**Comment by Hann** [comment]
넵 그렇게 진행해보겠습니다. 답변 감사드립니다. 😁
