### ISSUE TITLE
글/댓글을 쓰고 난 뒤 시간이 음수로 표기됨

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#7]
<img width="368" alt="2015-11-15 11 30 07" src="https://cloud.githubusercontent.com/assets/5893514/11166845/417f725a-8b8c-11e5-972b-05763dc97a7c.png">
시간 계산시 음수인 경우 방금 전과 같이 표시하는 것이 어색하지 않습니다.

**Comment by findstar** [comment]
서버와 클라이언트 PC 의 시간대가 달라서 나는 문제일 수도 있을것 같습니다. 
설치한 서버와, 브라우저 PC 의 시간대가 문제가 다르지 않는지 확인 부탁드립니다.

**Comment by YJSoft** [comment]
@findstar 시간대는 Asia/Seoul로 같습니다. 
시간이 차이나는 것은 어쩔 수 없겠지만, 시간을 계산해서 보여줄 때 음수로 계산되는 경우 방금 전 이라고만 표시하는 정도면 괜찮을 것 같다는 것입니다.

**Comment by findstar** [comment]
네 확인감사합니다. 반영하여 처리하겠습니다.
