### ISSUE TITLE
인스톨할 때 Log/AbstractLogger.php 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#706]
인스톨할 때 AbstractLogger 로 인한 오류 발생하며 install 할 수 없습니다.
![2018-03-14 11 28 42](https://user-images.githubusercontent.com/5836237/37380219-f9b75856-277a-11e8-9f85-c127c80f3842.png)

**Comment by woongbin** [comment]
[commit](https://github.com/xpressengine/xpressengine/commit/1eb13c2ca341c4729e4095f3bebe8e10a7465e1e)에서 수정되었습니다.
