### ISSUE TITLE
SocialLogin 언어표시 및 연결이슈

### ISSUE THREAD

**Issue by nogcha234** [xpressengine/xpressengine#715]
v.0.9.18 플러그인을 설치하면 /lang.php에 포함된 언어가 나타나지 않고
socialLogin / msgDisconnected 과 같은 호출언어만 표시됩니다.

로그인 후 개인설정의 socialLoginSetting(소셜 로그인 설정) 에서 소셜을 Connect(연결)을 누르면 각 소셜의 로그인창이 뜨는것이 아닌 사이트 메인페이지로 이동됩니다.

**Comment by jhyeon1010** [comment]
문제는 해당 플러그인 저장소에서 수정처리 하였습니다.
다국어 부분도 install, update 시 처리되도록 하였습니다. 현재 사용중인 상태에서 다국어 등록 명령 (`php artisan translation:import social_login`) 을 실행하시면 정상적으로 표시될 것입니다.
