### ISSUE TITLE
제가 사용하는 사이트는 allow_url_fopen 막혀있어서 이런 방법을 사용합니다.

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#721]
정확하게 왜 작동되는지는 알지 못하지만
xe3 최신버전으로 업그레이드할 때는 xe3가 설치된 폴더에서 아래의 명령을 사용합니다.

# php -d allow_url_fopen=on composer.phar  update

플러그인의 경우에는 직접 다운로드하여 플러그인의 해당 폴더에 압축을 푼 뒤
아래와 같은 명령어를 사용합니다. (컴포저의 위치가 플러그인의 하부에 있기에 ../../ 을 추가한 것입니다.)

# php -d allow_url_fopen=on ../../composer.phar  update

**Comment by akasima** [comment]
좋은 팁인것 같습니다. 


사용자 서버 환경에 대한 문제는 컨트롤이 불가능하네요 ;;
동일 서버환경을 구성해 보지 않아서 테스트를 하진 않았지만
전에 install 할 때 문제가 있어서 XE3 설치 문서에 추가한 내용도 있었네요.

`php -d display_errors=1 -d error_reporting=-1 -d allow_url_fopen=1 -r "copy('http://start.xpressengine.io/download/installer', 'installer');" && php installer install`

이 명령어 역시 allow_url_fopen 을 사용할 수 없는 환경에서 사용하는 방법이었습니다.

**Comment by 1Sam** [comment]
위 명령어를 활용하면 xe3도 웹페이상에서도 업데이트를 할 수 있게 해되는 건가요?
아니면 계속 쉘명령어로 수동 업데이트를 해야하는 건가요?

**Comment by akasima** [comment]
설정이 바뀌는건 아니니.. 계속 명령어로 해야할거에요.
