### ISSUE TITLE
[Page 모듈] page 의 스킨을 설정하고 싶습니다!

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#723]
아무리 찾아봐도 Page의 스킨을 바꿀 수 있는 곳이 보이지 않습니다. ㅠㅠ 
회원관리 스킨 변경처럼 Page 스킨을 따로 설정할 수 있었으면 좋겠습니다!

**Comment by jhyeon1010** [comment]
xpressengine/plugin-page#14 에서 처리하였습니다.
