### ISSUE TITLE
소셜로그인, 같은 닉네임

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#724]
`서버환경: XE3 공식페이지` 

소셜로그인을 사용하여... 
네이버 아이디로 가입을 한 다음,
깃허브 아이디로 가입을 하였습니다. 

네이버 닉네임과 깃허브 닉네임이 동일하며,
XE3 에서는 나중에 로그인한 깃허브 닉네임에 숫자를 붙혀 닉네임 중복을 회피하였습니다.
이때 깃허브로 로그인한 상태에서 네이버 아이디로 가입했을 때 등록된 닉네임과 동일하게 변경하면,
 `시스템에 오류가 있습니다. 관리자에게 문의하세요.` 메세지가 출력됩니다!

확인부탁드립니다!

**Comment by jhyeon1010** [comment]
확인해보니 코어의 버그는 아니고 공홈의 버그였네요. 
제보 감사합니다. :)
