### ISSUE TITLE
migrations/UserMigration.php, migrations/MemberMigration.php 중복 테이블?

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#73]
migrations/UserMigration.php, migrations/MemberMigration.php

        Schema::create('password_resets', function (Blueprint $table) {
            $table->engine = "InnoDB";
            $table->increments('id');
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at');
        });

두 파일에 같은 테이블명을 생성하게 해도 되는가요?

**Comment by khongchi** [comment]
개발단계에 있는 브랜치의 코드를 보셨나 봅니다.

차후에 통합될 예정입니다.
