### ISSUE TITLE
회원가입 문제

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#736]
`Valet for Windows, PHP_FPM 7.1.15, XE3 beta 28 환경을 사용중입니다.`

문제 1
1. `대쉬보드` -> `회원` -> `가입설정` 에서 이메일 인증 안함 으로 설정 및 `약관설정` 에는 아무 약관도 등록하지않습니다.
2. 회원가입 완료 후 `이메일이 전송되었습니다.` 라고 토스트 메시지가 올라오며 가입페이지에서 메인페이지로 이동하지 않습니다.

문제 2
1. `대쉬보드` -> `회원` -> `가입설정` 에서 이메일 인증 으로 설정 및 `약관설정` 에는 아무 약관도 등록하지않습니다.
2. 회원가입 완료 후 이메일 전송알림 토스트 메세지가 출력되며, 이메일 인증코드 입력 필드 아래에 기본 정보 입력 필드가 나타납니다.
3. 가입인증 메일이 새로 가입한 회원의 이메일로 전송되지 않으며 `회원목록`에 등록되지 않습니다.

**Comment by jhyeon1010** [comment]
이메일 인증 사용시 처리 절차는 `이메일 주소 입력` -> `인증메일 발송` -> `인증코드 및 기본정보 입력` -> `회원가입 완료 및 로그인` 입니다.  가입완료 후 이메일 전송메시지는 확인이 되지 않아서 어떤 문제인지 추측하기가 어렵네요..
이메일 전송이 되지 않는것은 서버 환경에 따라 차이가 있을 수 있습니다. 반송처리가 되었는지, 스팸함으로 수신되었는지, 서버설정에 문제는 없는지 확인이 필요할것 같습니다.
