### ISSUE TITLE
메뉴 활성화 정보가 편집시 불러와지지 않음

### ISSUE THREAD

**Issue by YJSoft** [xpressengine/xpressengine#74]
메뉴 활성화 정보가 편집시 불러와지지 않아 비활성화로 체크되어, 아무 생각없이 편집후 저장하면 비활성화 상태로 바뀝니다.

**Comment by jhyeon1010** [comment]
말씀하신 현상이 확인 되지 않습니다.
혹시 dev3 버전에서도 같은 문제가 발생하는지 확인 부탁드립니다.

**Comment by YJSoft** [comment]
`dev4` 기준 정상 동작합니다.
