### ISSUE TITLE
www 와 @ 간의 세션유지가 되지 않습니다.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#741]
`xetown.com` 으로 예를 들자면,
`xetown.com` 으로 로그인하여 `www.xetown.com` 으로 접속하면 세션이 유지됩니다.

XE3 에서는 세션이 유지되지 않고 새로 로그인을 해야합니다!
확인부탁드립니다!

**Comment by akasima** [comment]
`production/session.php` 파일을 만들고 아래와 같이 설정을 추가해 주세요

```php
<?php

return [
    'domain' => '.xetown.com',
];
``
