### ISSUE TITLE
설정 > 사이트맵  렌더링 오류

### ISSUE THREAD

**Issue by leeyoonwoo** [xpressengine/xpressengine#748]
### 최종 정렬 상태
![sitemap_before](https://user-images.githubusercontent.com/6457000/38920098-704fb92c-432d-11e8-942c-e25ca80249c7.png)

### 새로고침 후 정렬 상태
![sitemap_after](https://user-images.githubusercontent.com/6457000/38920150-8f006290-432d-11e8-92af-dedcdcb03a53.png)

**Comment by bnu** [comment]
fixed #748
