### ISSUE TITLE
관리자에서 플러그인 관련 변경할 때 route:cache 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#759]
route:cache 를 사용하는 경우 플러그인을 껏을 때 
관련 plugin:boot()  가 실행되지 않으면서 route 등록이 안되고 
이로 인해 관련 메뉴와 연관된 route 를 찾지 못해 오류가 발생하는 문제가 있습니다.

관련해서 개선이 필요해 보입니다.

**Comment by jhyeon1010** [comment]
플러그인을 끈 경우에는 route cache 를 사용함과 무관하게 등록된 메뉴에 지정된 주소로 이동할 수 없게 됩니다.
따라서 특정 플러그인을 끄기 전에 해당 플러그인이 사용된 메뉴등을 삭제하는 행위가 선행되어야만 합니다.
