### ISSUE TITLE
\Menu 클래스와 getAllMenu() 함수 버그(ver 3.0.0-dev)

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#77]
관리자 메뉴에서 앨리스 설정하기에 들어가면 아래와 같은 오류 메시지가 표시됩니다.
http://xe3.1sam.kr/settings/alice/options

Whoops, looks like something went wrong.

1/1
FatalErrorException in /home/kmdb/public_html/xe3/resources/UIObjects/Menu/MenuSelector.php line 41:
Class 'Menu' not found
in MenuSelector.php line 41

41번 줄을 보면
       $menus = \Menu::getAllMenu(\Site::getCurrentSiteKey());
getAllMenu() 함수가 있습니다만,

http://api.xpressengine.io/master/Xpressengine/Menu/MenuRetrieveHandler.html#method_getAllMenu

위의 API 설명서와는 달리 이번 v3 패키지에는 해당 파일이 포함되지 않았습니다.

https://github.com/xpressengine/xpressengine/search?utf8=%E2%9C%93&q=getAllMenu

위와 같이 Git Repository 에서 getAllMenu 함수를 검색하면 호출하는

resources/UIObjects/Menu/MenuSelector.php 파일에만 보입니다.

버그를 수정해 주시기 바랍니다.

**Comment by akasima** [comment]
Dev3에서 변경된 사항이 적용되지 않았었네요 ;;
