### ISSUE TITLE
Emoji(모바일 이모티콘) 위한 utf8mb4 지원 건의합니다.

### ISSUE THREAD

**Issue by gooooooood** [xpressengine/xpressengine#776]
혹시 기능 건의도 가능하다면 

😎 같은 Emoji 이모티콘을 기본 코어에서 지원했으면 합니다

**Comment by smaker** [comment]
@bnu 이 이슈도 관심가져주세요^^

**Comment by akasima** [comment]
@smaker https://github.com/xpressengine/plugin-emoticon 플러그인과 관련 잇을까요? 에디터에 붙여서 사용할 수 있는 이모티콘 입니다만. 지금도 동작하는 플러그인인지는 확인이 필요하지만.요.

**Comment by jdssem** [comment]
@gooooooood 님과 @smaker 님이 말씀하신 것은 이미지 형태의 이모티콘이 아니라 utf8mb4 형태의 이모지 지원을 위해 DB를 설계할때부터 고려해 달라는 말씀 같습니다.

https://blog.lael.be/post/917 이 글을 참고하시면 될듯 하네요.

**Comment by bnu** [comment]
여기있네요.
https://github.com/xpressengine/xpressengine/blob/master/app/Console/Commands/XeInstall.php#L501-L502
