### ISSUE TITLE
xe.ajax, 언제까지 지원되나요?

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#789]
#763 이 베타 30에 올라왔습니다.
개발 중인 제 플러그인에서 아직은 코어에서 지원이 되는 xe.ajax 를  xe.Request 로 대체하려고 합니다. 
axios 가 제가 처음 본 넘이라 공부가 필요한데요! 혹시 언제까지 지원이 되나요? ㅜㅜ
 xe 에서 어떻게 xe.Request 를 활용하여 구현할 수 있는지 프론트 엔드 가이드의 xe.ajax 부분을 갱신해주실 수 있나요?

**Comment by bnu** [comment]
@Laeng 안녕하세요.

`XE.ajax()`는 beta 버전이지만 호환성 유지를 위해 3.1 버전까지는 유지할 계획이며,
근시일에 되지 않으니 당분간은 천천히 대체하셔도 될 것 같습니다.
제거 된다면 3.1 beta 또는 RC 버전을 릴리즈하며 충분히 알려지도록 하겠습니다.
가이드도 마련하겠습니다.

우선은, 간단한 대체 방법은 아래와 같습니다.

```js
XE.ajax('http://URL', {
  method: 'get',
  type: 'json',
  data: requestData,
  success: function (data) { console.log(data) }
})
```

이런 식이었다면 아래와 같이 대체할 수 있습니다.
요청을 보내던 method에 따라 XE.get() 또는 XE.post() 등을 사용할 수 있습니다.

```js
XE.get('http://URL', requestData).then(function success (response) { console.log(response.data) })

...
XE.post()
XE.put()
```

**Comment by Laeng** [comment]
오오! ajax 보다 더 단순해져서 쓰기 편리해졌어요!!
고맙습니다!!
