### ISSUE TITLE
앨리스 테마 설정>메뉴>메인메뉴, 셀렉트 박스 텅 빈 상태 버그

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#79]
https://github.com/xpressengine/xpressengine/commit/5269b692eda19ebbda6b31dda350cc5045424fad

위와 같이 새로운 코드로 수정한 후 에러 메시지는 사라졌지만,
메인메뉴를 선택하는 리스트 박스에 아무 것도 채워져 있지 않습니다. 다수의 메뉴 그룹을 만들어 봤지만 리스트 박스는 비어있습니다.

그리고
http://xe3.1sam.kr/home
이런 에러 메시지도 뜹니다.

**Comment by akasima** [comment]
plugins/alice 수정사항 또한 적용해야 합니다.
https://github.com/xpressengine/plugin-alice/commit/51b4127542cdad698208d94b0a9670cc834bc617

**Comment by akasima** [comment]
http://xe3.1sam.kr/home 에러는 직접확인하지 못했습니다.

Alice 테마에서 메뉴 출력할 때 발생한 오류로 짐작됩니다. alice 플러그인 적용하고 문제 발생하면 다시 알려주세요.
