### ISSUE TITLE
timeago locale 적용문제

### ISSUE THREAD

**Issue by jhyeon1010** [xpressengine/xpressengine#795]
게시글등의 작성시간을 표시할때 사용되는 timeago 가 locale 이  `ko` 인 상태에서도 영문으로 표시되고 있습니다.

**Comment by bnu** [comment]
cookie 암호화 제거 후 증상으로 보입니다.

cookie 암호화 제거 후 cookie를 참고하고 있는데, 암호화된 cookie가 남아 있어 기본 언어인 영문으로 출력되고 있습니다. cookie를 우선하기 때문에 사용자 브라우저에서 cookie를 제거 또는 언어 변경으로 해결될 수 있습니다.
