### ISSUE TITLE
메뉴 설정시, 'Page 의 기본적인 설정을 입력합니다.' 에서 comment 를 use로 설정하면 페이지 깨짐 버그

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#80]
https://www.youtube.com/watch?v=IwjF5HbpsjU&feature=youtu.be

2가지의 버그입니다.

1- 페이지에 comment 사용하면 페이지가 깨집니다.

2- 메뉴가 나타나지 않는 것이 각 메뉴의 활성화 상태가 저장되지 않기 때문인지 궁금합니다.

**Comment by akasima** [comment]
동영상 감사힙니다. :)  문제 파악하는데 많은 도움 되네요!!

**Comment by jhyeon1010** [comment]
page plugin 에서 comment 사용하는 코드에 문제가 있었네요.
메뉴 표시관련 부분은 #79 와 같은 문제 인것 같습니다.
업데이트 하시면 정상동작 할것으로 보입니다.
