### ISSUE TITLE
정말 대단하십니다. 개발진의 노고에 경의를 표합니다.

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#809]
플러그인이 자동으로 업데이되네요. ㅠ.ㅠ
눈물이 납니다. ㅠ.ㅠ
너무 좋은데요. ㅠ.ㅠ

어떤 방식으로 우회하여 파일을 다운로드하도록 했는지 간략하게 설명을 부탁드려도 되겠습니까?

다들 더운 날씨에 엉덩이 땀띠 안 나게 짬짬이 아이스 아메리카노 하나 들고 산책도 하시기 바랍니다~
후후

**Comment by jhyeon1010** [comment]
플러그인의 다운로드는 php 의존성 관리도구인 composer 를 이용하고 있습니다.
composer 에 대한 상세한 정보는 https://getcomposer.org/ 또는 http://xpressengine.github.io/Composer-korean-docs/ 에서 확인할 수 있습니다.
