### ISSUE TITLE
validator 개선

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#818]
## validator checked 
`resources/assets/core/validator/index.js`
validator 에 `checked` 가 있는데 사용할 때 에러 납니다.
오류 보다 문제는 validator 에 checked 를 어떻게 사용할것인가 입니다.
checkbox, radio 등에 checked 를 사용해서 validator 할 경우는 없을 것 같습니다.

checked 가 있어서 어떻게 사용할지 한참 생각했는데 사용할 방법이 없을 것 같습니다.

개선을 하자면 checked 는 frontend 에서 checkbox, radio, select 등에 required 일 때 선택된 것이 있는지를 판단하는 방식을 것 같습니다.
checked 는 없애고 required 를 개선해서 checkbox, radio, select 에 대해서 지원 됐으면 합니다.

**Comment by bnu** [comment]
해당 기능은 스크린샷과 같이 checkbox 그룹의 항목이 선택되어야 할 갯수를 검사하는데 사용합니다.
required로 select, radio, checkbox에 대해서 해당 동작을 수행하고 있습니다.

```
XE.Validator.validate($(form), 'group_id[]', 'checked:1-2')
```
<img width="502" alt="2018-07-19 10 33 04" src="https://user-images.githubusercontent.com/53764/42916239-2afd11a8-8b3f-11e8-9dcf-6839d9e9d05c.png">
