### ISSUE TITLE
validator가 radio 타입의 required를 검사하지 못하는 문제

### ISSUE THREAD

**Issue by fwang-laralabs** [xpressengine/xpressengine#819]
validator 개선 #818

해당 이슈에 "required로 select, radio, checkbox에 대해서 해당 동작을 수행하고 있습니다."  라고 되어 있습니다만,
확인해 본 결과 radio button , checkbox 에서는 required 가 동작 하지 않고 pass 하는 것으로 확인 됩니다.

**Comment by bnu** [comment]
문제가 발생하는 페이지나 브라우저 정보 등을 주시면 다시 확인해보겠습니다.

<img width="503" alt="2018-07-19 11 23 09" src="https://user-images.githubusercontent.com/53764/42917803-261749ae-8b46-11e8-932c-adf05bfa5296.png">

**Comment by fwang-laralabs** [comment]
http://d1www.homespace.co.kr/consult/basic
해당 페이지 입니다. ( 비회원 접속 가능 )

소스보기에는 

var ruleSet = { ruleName: "consult_basic", rules: {"name":"required","phone":"required|numeric","hty_cd":"required","square":"required|numeric","n_zip":"required|numeric","addr_detail":"required","budget":"required|numeric","email":"required|email"} }

로 확인 됩니다만 ,
라디오 버튼인 hty_cd 부분이 동작 하지 않습니다.

그래서 별도 submit 이벤트를 제어하여 validate 처리 하였습니다.

                if( $("[name=hty_cd]:checked").length < 1 ) {
                    XE.Validator.error( $("[name=hty_cd]") , "공간 형태를 선택하세요." );
                    return false;
                }

부분 삭제 후 확인해 보면 동작하지 않습니다.
맨 하단 동의 부분 체크박스도 동일하게 동작하지 않습니다.

**Comment by bnu** [comment]
radio 타입에서 동작하지 않는 것을 확인했습니다.
해당 페이지에서 임의로 룰을 추가하여 확인한 결과 checkbox는 정상동작했습니다.

**Comment by fwang-laralabs** [comment]
혹시 이후 작업이 있었는지, 잘 날라가던 submit 이 안날라 갑니다.
잘 동작하고 있었습니다만,
validate 에 모두 통과한 상황에서 submit 이 안날라 가네요.
기존 URL 에서 확인 가능합니다.
http://d1www.homespace.co.kr/consult/basic

**Comment by bnu** [comment]
@fwang-laralabs develop 브랜치 최신으로 업데이트 해주세요.
