### ISSUE TITLE
회원의 추가필드 버그, 설정의 관리페이지 권한 설정 버그

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#82]
https://youtu.be/j-DYL8lj04I

관리자 페이지에서 발생하는 2가지 버그 관련입니다.

첫번째는 추가필드 아이템을 선택할 때 뜨는 오류 메시지입니다.
두번째는 관리페이지 권한 설정 페이지가 깨지는 오류입니다.

**Comment by khongchi** [comment]
두번째 오류는 #94에서 처리하겠습니다.

**Comment by khongchi** [comment]
첫번째 오류는 다이나믹 필드 관련 오류로 담당자 변경해놓겠습니다.

**Comment by akasima** [comment]
첫번째 오류 수정했습니다. 관리페이지 권한 설정 오류는 #94 에서 다룹니다. 이슈 닫습니다.
