### ISSUE TITLE
ckeditor 에서 이미지 가운데 정렬 안되는 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#829]
에디터 사용할 때 이미지가 가운데 정렬되지 않습니다.
아래 사진에 보면 이미지 추가하고 정렬방법이 왼쪽, 오른쪽 정렬만 활성되어 있습니다.

![2018-07-27 2 07 18](https://user-images.githubusercontent.com/5836237/43302603-765a43e2-91a6-11e8-9856-fbbf6596fa39.png)

**Comment by bnu** [comment]
이미지 정렬은 float, text-align 두 속성으로 정렬 기능이 다르게 동작합니다.

1) 이미지를 선택하여 정렬 시 float 속성으로 정렬되어 이미지 옆 공간이 있을 때 주변으로 뒤에 있던 텍스트 등이 배치되며(흔히 이미지 옆으로 흐른다고 하죠)

2) 이미지 옆 공간(같은 문단)을 선택하면 text-align으로 문단의 text-align 속성으로 정렬됩니다.

1의 경우 float의 옵션과 같이 left, right 정렬만이 선택할 수 있으며
2의 경우는 text-align의 left, right, center 옵션이 선택할 수 있습니다.

다소 혼돈이 있을 수 있으나 에디터에서의 의도 및 해당 속성 값이 가질 수 있는 정상적인 정렬 방법으로 제공되고 있습니다.

다음과 같이 이미지 옆 공간에 커서를 두고 text-align으로 정렬 기능이 동작합니다.
![xe3_bnu-2](https://user-images.githubusercontent.com/53764/43303316-2a78e196-91aa-11e8-9157-487ee6d11406.png)
