### ISSUE TITLE
다국어 수정할 때 오류

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#832]
XE에서 사용하는 다국어 메시지를 수정하려는데 오류가 있습니다.

/settings/lang 에서 다국어 수정할 때 문제

![2018-07-31 1 11 40](https://user-images.githubusercontent.com/5836237/43437318-657041e2-94c3-11e8-9e3b-1e77da3307cd.png)

**Comment by bnu** [comment]
버그가 있어 수정했습니다.

**Comment by akasima** [comment]
`laravel::validation.required` 를 수정하는데 적용되지 않습니다. DB에 등록되지 않는 것 같습니다.
한국어 메시지 `:attribute 필드는 필수입니다.` 를  `:attribute 을(를) 입력해주세요.` 로 변경하려는데 저장되지 않습니다.
저장 버튼 눌렀을 때 ajax 는 정상 처리되었다고 표시되지만 데이터는 저장되지 않는 것 같습니다.

**Comment by bnu** [comment]
@akasima 추가 수정된 것이 있습니다. 다시 확인해주세요.
