### ISSUE TITLE
allow_url_fopen 설정이 꺼져있습니다. 플러그인을 업데이트하려면 php.ini 파일에서 설정을 켜야 합니다.

### ISSUE THREAD

**Issue by nogcha234** [xpressengine/xpressengine#838]
RC2/
allow_url_fopen 설정이 꺼져있습니다. 플러그인을 업데이트하려면 php.ini 파일에서 설정을 켜야 합니다.
라는 문제로 대부분의 웹호스팅 서비스에서 XE3 이용이 불가능한 문제가 있습니다.

CAFE 24 10G 광호스팅도 같은문제로 플러그인 업데이트/설치가 불가합니다.

**Comment by jhyeon1010** [comment]
웹서버가 아파치이고 `.htaccess` 사용이 가능하다면 다음 내용을 `.htaccess` 에 작성하고 시도해보시기 바랍니다.
```
php_value allow_url_fopen On
```

**Comment by brian-sj** [comment]
그래도 않되네요. 포기 해야 하는건가요?

**Comment by jhyeon1010** [comment]
cafe 24 의 10G 광호스팅 상품중에 PHP 7.0 / mariadb 상품에서 확인했을때 allow_url_fopen 문제 없이
플러그인 설치가 가능했었습니다.
apache 버전이 호스팅마다 조금 상이할 가능성으로 생각해본다면
`php_flag allow_url_fopen On` 로 변경해서 시도해보시고
그래도 해결되지 않는다면 cafe24에 문의를 해보시는게 좋을것 같습니다.
