### ISSUE TITLE
에디터에서 글 등록할 때 테이블 사용 문제

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#839]
에디터에 table 추가하고 글 작성할 때 내용에 따라 테이블 크기기 자동으로 바뀌는 문제가 있습니다.

테이블 이용해서 표현하는데 어려움이 있습니다.

![2018-08-06 4 46 32](https://user-images.githubusercontent.com/5836237/43703654-69cf4358-9998-11e8-86a1-6ff725c335d1.png)
![2018-08-06 4 46 40](https://user-images.githubusercontent.com/5836237/43703658-6c186266-9998-11e8-8f6d-5e131db245e2.png)

**Comment by akasima** [comment]
에디터에서 엔터(줄바꿈) 입력할 때 높이가 조금씩 다른 문제가 있습니다.
어떤 경우에 발생한 문제인지 확인이 필요합니다.

**Comment by bnu** [comment]
table은 cell 등의 크기를 지정하지 않으면 내용에 맞게 폭이 자동으로 조절됩니다.

폭을 조절할 수 있는 CKEditor의 자체 애드온(https://ckeditor.com/cke4/addon/tableresize)이 있으니 이를 추가해보겠으나, iOS 한글 입력 호환성 및 https://github.com/xpressengine/xe-core/issues/2118 이슈와 같은 문제가 있어서 검토 후 결정하겠습니다.

**Comment by bnu** [comment]
table resize 기능 추가
셀 border에 마우스 커서를 두고 컬럼 및 테이블 크기 변경 가능
![2018-08-08 2 52 48](https://user-images.githubusercontent.com/53764/43818726-df165cd6-9b1a-11e8-8d29-d665a6543a2b.png)

https://github.com/xpressengine/xe-core/issues/2118 이슈에 대해서는 추가 확인이 필요 함
(테스트용 실기 없음)

**Comment by bnu** [comment]
https://github.com/xpressengine/plugin-ckeditor/issues/47 이슈로 이동
