### ISSUE TITLE
최근 수정된 내용으로 사이트를 업데이트 했더니 로그인을 해야 페이지를 열 수 있습니다.

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#84]
http://xe3.1sam.kr/

<blockquote class="imgur-embed-pub" lang="en" data-id="2CYVqFT"><a href="//imgur.com/2CYVqFT">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
권한 설정에 문제가 있는 것 같습니다.

**Comment by jhyeon1010** [comment]
해당 현상이 재현되질 않습니다.
재설치 후에도 정상적으로 사이트 홈의 페이지가 노출됩니다.
혹시 데이터 베이스 상의 권한이 어떤 경로에 의해 변경되지 않았는지 확인부탁드립니다.
확인중 메뉴 권한 설정페이지관련 오류(#85) 가 있어 수정되었습니다.

**Comment by 1Sam** [comment]
새로 설치하고 #85 대로 수정했습니다. 권한 설정 페이지 잘 보입니다.
