### ISSUE TITLE
error page 가 skin 을 사용하지 않고 출력되는 문제.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#844]
https://www.xpressengine.io/qna/%EC%8A%A4%ED%82%A8-%EB%8D%AE%EC%96%B4%EC%94%8C%EC%9A%B0%EA%B8%B0

akasima 님께서 대안을 알려주셨습니다!
하지만 테마가 출력되지 않는 순수한 error 만 나오는 스킨을 만들고 싶고, XE3 에서 고쳐져야 가능한것으로 생각되어 issue 올립니다!

**Comment by jhyeon1010** [comment]
테마를 제외할 수 있는 설정을 추가하였습니다.
에러가 표시되는 페이지를 변경하고 싶은경우 `config/production/view.php` 파일을 추가하신 후 다음 처럼 작성해주시면 됩니다.
```
'error' => [
    // 플러그인 내에 새로 생성한 뷰 파일을 사용하는경우 해당 플러그인 이름의 네임스페이스와 함께 경로를 지정
    'path' => 'plugin_name::view.path',
    // 테마를 표시하는 경우 true, 표시하고 싶지 않은 경우 false
    'theme' => false,
]
```

**Comment by Laeng** [comment]
오우!! 고맙습니다!!!!
