### ISSUE TITLE
파일을 선택해서 업로드 하려고 할 때 에러

### ISSUE THREAD

**Issue by woongbin** [xpressengine/xpressengine#847]
에디터에서 파일을 끌어서 첨부하는 방식이 아닌 파일 선택 창에서 선택해서 업로드 할 때 에러 발생
request에 파일에 대한 정보가 없음

**Comment by bnu** [comment]
사파리 버그로 인한 문제.
선택한 파일의 정보가 정상적으로 넘어오지 않았을 때 예외처리로 진행하겠습니다.

**Comment by bnu** [comment]
jquery fileupload의 버그였음..
아직 라이브러리에서 문제가 고쳐지지 않았으나 최신 버전으로 업데이트 후 문제되는 코드를 임의 패치 예정.
https://github.com/blueimp/jQuery-File-Upload/pull/3512
