### ISSUE TITLE
editor 파일 업로드 size 설정 값이 php.ini에서 설정한 값보다 클 경우 변경 안되도록 설정

### ISSUE THREAD

**Issue by woongbin** [xpressengine/xpressengine#849]
관리자 권한을 가진 사용자는 php.ini 설정 파일에서 설정된 값을 최대 값으로 지정(#848)

일반 사용자가 업로드 하는 설정을 변경 할 때 현재 설정 되 있는 upload_max_filesize, post_max_size를 비교해서 
php 설정보다 큰 값을 설정 못 하도록 변경하는 것이 좋을 것 같습니다.

**Comment by bnu** [comment]
attachMaxSize는 하나의 글(+댓글 등)에 첨부할 수 있는 총 용량의 제한이므로 'upload_max_filesize', 'post_max_size' 등으로 최대값을 제한 할 필요가 없습니다.

attachMaxSize의 값은 '0(무제한) 또는 1 이상의 값'으로 제한 없이 설정할 수 있어야 합니다.
조건을 하나 더 설정한다면 attachMaxSize 값은 fileMaxSize보다 커야겠죠.

attachMaxSize는
- 0(무제한)으로 설정할 수 있어야 함
- 1이상의 값을 가질 수 있으며 최대값의 제한이 없어야 함
- fileMaxSize 이상이어야 함
