### ISSUE TITLE
rc3 버전으로 업데이트 하고부터 설정의 플러그인 목록 페이지가 동작하지 않습니다.

### ISSUE THREAD

**Issue by limslee** [xpressengine/xpressengine#855]
rc3 버전으로 업데이트 하고부터 설정의 플러그인 목록 페이지가 동작하지 않습니다.
시스템 오류가 있습니다. 관리자에게 문의하세요
라고만 나오네요.

https://www.xpressengine.io/qna/rc3-%EB%B2%84%EC%A0%84%EC%9C%BC%EB%A1%9C-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8%ED%95%98%EB%8B%88-%EC%84%A4%EC%A0%95%EC%9D%98-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EB%AA%A9%EB%A1%9D-%ED%8E%98%EC%9D%B4%EC%A7%80%EA%B0%80-%EB%8F%99%EC%9E%91%ED%95%98%EC%A7%80-%EC%95%8A%EB%84%A4%EC%9A%94

**Comment by akasima** [comment]
최근 배포에 database connection 관련해서 변경된 내용 때문에 그럴 것 같습니다.
 
우선 아래 명령어 실행하고 
php artisan cache:clear
 
안되면 아래 명령어도 실행해 보세요.
rm storage/app/interception/*php
