### ISSUE TITLE
회원 가입 설정에서 이메일 인증 활성화시 에러

### ISSUE THREAD

**Issue by limslee** [xpressengine/xpressengine#861]
제목대로 회원 가입 설정에서 이메일 인증 활성화시 에러가 나네요
자세한 스크린샷은 링크로 대신합니다.

https://www.xpressengine.io/qna/%ED%9A%8C%EC%9B%90-%EA%B0%80%EC%9E%85-%EC%84%A4%EC%A0%95%EC%97%90%EC%84%9C-%EC%9D%B4%EB%A9%94%EC%9D%BC-%EC%9D%B8%EC%A6%9D-%ED%99%9C%EC%84%B1%ED%99%94%EC%8B%9C-%EC%97%90%EB%9F%AC

**Comment by limslee** [comment]
아 본문을 정확하게 쓰지 않았는데
이메일 인증을 확성화하고
회원 가입시 이메일 입력하고 인증 이메일 전송 버튼을 누르면
에러 화면이 나오네요.

**Comment by jhyeon1010** [comment]
#853 이슈와 같은 문제로 보이네요.
`app/Providers/UserServiceProvider.php` 194번 줄에 `$connection = $app['xe.db']->connection('user');` 를 `$connection = $app['xe.db']->connection();` 로 변경하면 문제가 해결될것 같습니다.
