### ISSUE TITLE
플러그인 ExternalPage 작동 안 됨

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#87]
http://xe3.1sam.kr/settings/plugins/external_page

설정 페이지가 열리지 않습니다.

**Comment by jhyeon1010** [comment]
https://github.com/xpressengine/plugin-external_page/commit/5b2fc63c24e17e2689b0383d54a466565d194c0a 에서 수정되었습니다.

**Comment by 1Sam** [comment]
작동 됩니다. 수고하셨습니다.
