### ISSUE TITLE
페이지 설정 시, 아무것도 입력하지 않았을 때 발생하는 버그

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#870]
![screenshot-simplesoft io-2018 09 17-11-50-09](https://user-images.githubusercontent.com/1732040/45604479-cd1a7700-ba6f-11e8-9107-7b23f0e96f17.png)

스크린샷으로 대체합니다.

**Comment by woongbin** [comment]
https://github.com/xpressengine/plugin-page/issues/17
page plugin에서 수정하도록 하겠습니다
