### ISSUE TITLE
XE 문서의 내용이 현재 버전과 많이 다릅니다.

### ISSUE THREAD

**Issue by thorwel** [xpressengine/xpressengine#874]
https://xpressengine.gitbooks.io의 back, front 문서가 현재 버전과 많이 다릅니다.

없는 내용은 건너 뛰더라도, 저처럼 처음 접하는 사람에게는 잘못된 정보가 너무 많은 것 같습니다.

하다 못해 플러그인 만드는 것과 테마 만드는 부분까지...

점점 발전하는건 너무 고마운 일이지만,

이렇게 문서가 잘못된 정보를 전달한다면, 진입이 너무 어려워 포기 하는 경우가 많을 것 같습니다.

번거로우시더라도 잘 부탁드립니다. ㅜㅜ

**Comment by akasima** [comment]
문서 관련해서 일정 잡아보겠습니다.

**Comment by akasima** [comment]
https://xpressengine.gitbook.io/xpressengine-manual/summary

문서 개선 1차 작업으로 틀린 내용을 바로잡고, 추가해야할 문서에 대해서 파악했습니다.
문서 개선 2차 작업은 1월, 2월 중에 하게 될 것 같습니다. 

계속 지켜봐 주시구요~ 문서 관련한 문제점은 이슈에 계속 남겨주세요.
