### ISSUE TITLE
관리자사이트 게시물 관리 페이지에서 게시판 별 검색 기능 필요

### ISSUE THREAD

**Issue by akasima** [xpressengine/xpressengine#875]
관리자사이트 > 콘텐츠 > 게시물 관리 페이지(/settings/module/board@board/docs)에서 게시판 별 검색 기능이 추가되었으면 합니다.
각각의 게시판에 게시물 담당자를 배정했는데 따로 볼 수 있는 기능이 없어서 운영에 불편이 있습니다.

**Comment by woongbin** [comment]
https://github.com/xpressengine/plugin-board/issues/205
게시판 issue에서 처리하겠습니다
