### ISSUE TITLE
class가 없어서 에러가 떠요..

### ISSUE THREAD

**Issue by Yangseok** [xpressengine/xpressengine#876]
xpressengine/core/tests/Plugin/invalid_plugins/plugin_sample2/plugin.php 파일 13번째 라인
----------------------------------------------------------------------
PluginSample2 extends AbstractPlugin
----------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++
class PluginSample2 extends AbstractPlugin
+++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by woongbin** [comment]
검토해 보고 테스트 소스의 수정을 진행 해야 될 것 같습니다.
그런데 특별한 수정 없이 지금 상태에서 테스트를 돌렸을 때나 xe를 사용할 때 에러가 발생하지는 않는것 같은데 혹시 어떤 상황에서 에러가 발생했는지 알 수 있을까요?
