### ISSUE TITLE
소셜로그인 연동한 계정의 이메일 중복체크가 안되는 문제

### ISSUE THREAD

**Issue by nogcha234** [xpressengine/xpressengine#879]
기존 아이디에 NAVER 계정을 연동하게되면 기존 계정에 네이버 이메일주소가 자동으로 등록이 되는데
등록이된 이메일을 가지고 사이트 회원가입을 진행할경우 중복체크가 되지 않고 회원가입이 가능한 문제가 있습니다.

예)
이메일아이디/구글 아이디로 회원가입한 계정을 로그인하여 소셜로그인 AAAA라는 네이버 계정을 연결 함 (연동한 계정에 AAAA@NAVER.COM) 이라는 이메일이 등록됨

이후  AAAA@NAVER.COM 이메일을 가지고 사이트 회원가입을 진행할경우 중복체크가 되지 않고 회원가입이 진행되는 문제

**Comment by nogcha234** [comment]
(예를 네이버를 들은것이지만 구글과 같은 타 계정도 포함될 수 있습니다)

**Comment by akasima** [comment]
비밀번호 찾기를 기능을 이용하면 비밀번호 재 설정이 가능하지 않나요?
