### ISSUE TITLE
plugins/board/assets/css/doc.css 누락

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#88]
http://imgur.com/aG7L1Qo

plugins/board/assets/css/doc.css 파일이 누락된 것 같습니다.

**Comment by 1Sam** [comment]
D:\Orions\Downloads\xe3 latest v3-dev\plugins\board\views\defaultSkin\_frame.blade.php:
    4  {{ XeFrontend::js('plugins/board/assets/js/respond.min.js')->appendTo('body')->load() }}
    5  {{ XeFrontend::css('plugins/board/assets/css/board.css')->load() }}
    6: {{ XeFrontend::css('plugins/board/assets/css/doc.css')->load() }}
    7  {{ XeFrontend::css('plugins/board/assets/css/tomorrow-night-eighties.css')->load() }}
    8  

D:\Orions\Downloads\xe3 latest v3-dev\plugins\board\views\defaultSkin\index.blade.php:
    2  {{ XeFrontend::js('plugins/board/assets/js/respond.min.js')->appendTo('body')->load() }}
    3  {{ XeFrontend::css('plugins/board/assets/css/board.css')->load() }}
    4: {{ XeFrontend::css('plugins/board/assets/css/doc.css')->load() }}
    5

**Comment by akasima** [comment]
board 에서 관련 코드를 제거했습니다.
