### ISSUE TITLE
https로 접속했을 때 mixed content block 되는 문제

### ISSUE THREAD

**Issue by jdssem** [xpressengine/xpressengine#888]
xe3를 설치할 때 도메인명을 http://domain 으로 하였습니다.
이후 https 접속도 가능해서 https//domain 으로 접속하였더니 mixed content들이 모두 block 되어서 사이트가 깨집니다.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/978944/46742938-0054cc80-cce3-11e8-88ee-3a7c40a359fa.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/978944/46742981-15316000-cce3-11e8-81d6-3159c6547203.png">

브라우저 캐싱을 비활성화 해도 그렇고 ```config/production/app.php```에서 url에 https 주소를 넣은 후 ```composer dump-autoload```와 ```php artisan optimize```를 해도 마찬가지입니다.

**Comment by akasima** [comment]
한달이 지나서야 답변 드리네요.

```php
        intercept(\Xpressengine\Presenter\Html\HtmlPresenter::class . '@render', 'myplugin.html.replace', function ($func) {
            $result = $func();
                $result = str_replace(['http://domain', 'http://newoss.xef.kr'], 'https://domain', $result);
            return $result;
        });
```

추가한 플러그인이 있으시면,  `plugin.php` boot() 에 위 내용을 추가하세요.
```php
class Plugin extends AbstractPlugin
{
...
public function boot()
{
 // 여기에 추가
}
...
}

```

위 코드는 HtmlPresenter::render()에 intercept 추가해서 html 결과물에 http://domain 으로 된 걸 https://domain 으로 바꾸는 겁니다.
