### ISSUE TITLE
게시판 권한 설정 문제

### ISSUE THREAD

**Issue by brian-sj** [xpressengine/xpressengine#893]
1. 게시판 권한이 작동하지 않습니다. 
    read,list 권한,     포함할 그룹에 %그룹명 
    이렇게 했는데도 그룹에 포함되지 않는 사람이 읽기 및 메뉴가 보입니다. 

2. 댓글권한 설정하는 부분이 없습니다. 
   댓글 권한은 어디서 설정하나요?

**Comment by akasima** [comment]
1. 게시판 권한이 작동하지 않습니다.
* 회원등급을 관리자로 설정하고 해보세요.
<img width="647" alt="_2018-10-16_ _2_18_54" src="https://user-images.githubusercontent.com/5836237/46994259-ac1c7300-d14e-11e8-8c47-3c596f5c2230.png">
권한을 설정할 때 관리자, 또는 특정 회원 그룹 이라고 설정해야합니다.

* 메뉴가 보이는 문제 
메뉴 노출은 사이트 맵에서 설정해야 합니다. 
관리자사이트 > 사이트 맵 > 게시판 메뉴 클릭 > 권한 탭 클릭 > 노출 권한, 접근 권한을 설정하세요.
<img width="942" alt="_2018-10-16_ _2_22_49" src="https://user-images.githubusercontent.com/5836237/46994384-38c73100-d14f-11e8-8acb-55f8a0158c07.png">
<img width="890" alt="_2018-10-16_ _2_23_02" src="https://user-images.githubusercontent.com/5836237/46994385-3b298b00-d14f-11e8-8044-1bc155113747.png">
<img width="656" alt="2018-10-16 2 23 13" src="https://user-images.githubusercontent.com/5836237/46994387-3d8be500-d14f-11e8-83ba-4cb0a7de1e29.png">

2. 댓글 권한의 설정
게시판 상세 설정에서 댓글 항목에 있는 설정 클릭 > 권한 탭 클릭 > 권한을 설정하세요.

<img width="1286" alt="_2018-10-16_ _2_25_16" src="https://user-images.githubusercontent.com/5836237/46994505-b1c68880-d14f-11e8-8111-280052415673.png">
<img width="1289" alt="_2018-10-16_ _2_25_27" src="https://user-images.githubusercontent.com/5836237/46994508-b4c17900-d14f-11e8-82ca-39490b3741fd.png">

**Comment by brian-sj** [comment]
감사합니다.
