### ISSUE TITLE
[user / skins / default / settings /edit.blade.php ]

### ISSUE THREAD

**Issue by brian-sj** [xpressengine/xpressengine#894]
117번째줄 

null object에 format 함수 없다고 에러나옴. 

117번째줄 
FROM @if($user->password  &&  )
                        에러나는 부분   --> $user->password_updated_at->format('Y-m-d H:i:s') 

TO   @if($user->password  && $user->password_updated_at )

**Comment by kimyu711** [comment]
회원이 개인정보 수정하려고 할 때에 일어나는 오류 같습니다.
어떤 이유인지는 모르겠지만 해당 회원의 데이터항목이 null처리되었습니다.
관리자 계정으로 로그인 후에,
관리자페이지 - 회원 - 회원목록 (관리자 인증 후) - 테이블에서 해당 회원의 관리버튼으로 이동 후 비밀번호를 한번 변경해주시면 정상적으로 작동할 것 같습니다.
