### ISSUE TITLE
플러그인 ckeditor_plugin 의 자취가 아직 남아 있나 봅니다.

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#90]
http://xe3.1sam.kr/plugins/ckeditor_plugin/assets/plugins/append.js

글작성시에 위의 파일이 누락되었다고 콘솔에 표시됩니다.

**Comment by 1Sam** [comment]
D:\Orions\Downloads\xe3 latest v3-dev\plugins\board\views\defaultSkin\_frame.blade.php:
    4  {{ XeFrontend::js('plugins/board/assets/js/respond.min.js')->appendTo('body')->load() }}
    5  {{ XeFrontend::css('plugins/board/assets/css/board.css')->load() }}
    6: {{ XeFrontend::css('plugins/board/assets/css/doc.css')->load() }}
    7  {{ XeFrontend::css('plugins/board/assets/css/tomorrow-night-eighties.css')->load() }}
    8  

D:\Orions\Downloads\xe3 latest v3-dev\plugins\board\views\defaultSkin\index.blade.php:
    2  {{ XeFrontend::js('plugins/board/assets/js/respond.min.js')->appendTo('body')->load() }}
    3  {{ XeFrontend::css('plugins/board/assets/css/board.css')->load() }}
    4: {{ XeFrontend::css('plugins/board/assets/css/doc.css')->load() }}
    5  
    6  <div class="board">

**Comment by 1Sam** [comment]
Searching 8945 files for "append.js"

D:\Orions\Downloads\xe3 latest v3-dev\plugins\ckeditor\src\Extension\CkEditorPlugin.php:
   63              $path = '/plugins/ckeditor/assets/plugins';
   64              XeFrontend::js([
   65:                 asset(str_replace(base_path(), '', $path . '/append.js')),
   66              ])->load();
   67          }

D:\Orions\Downloads\xe3 latest v3-dev\plugins\comment\views\skin\user\default\container.blade.php:
   12      '/plugins/ckeditor/assets/ckeditor/styles.js',
   13      '/plugins/ckeditor/assets/ckeditor/xe3.js',
   14:     '/plugins/ckeditor_plugin/assets/plugins/append.js'
   15      ])->appendTo('body')->load() }}
   16  @endif

2 matches across 2 files

**Comment by akasima** [comment]
문제가 재현되지 않아 확인할 수 없습니다.

cooment 남겨주신것 보면 경로가 수정되어 문제 없을걸로 생각됩니다. 문제가 계속 발생되면 다시 알려주세요.

**Comment by 1Sam** [comment]
ckeditor_plugin 은 ckeditor로 통합되지 않았나요?
다시 확인 해 주시기 바랍니다.
