### ISSUE TITLE
boolean dynamic field 개선

### ISSUE THREAD

**Issue by woongbin** [xpressengine/xpressengine#908]
현재 boolean dynamic field가 생성할 때 입력 필수 여부에 상관 없이 true 값만 받을 수 있게 되어있음
입력이 필수이면 radio button으로 출력해서 true, false를 지정하고 사용자가 dynamic field를 생성 할 때
radio button에 보여질 label 값을 입력 가능하도록 변경
입력이 필수가 아니면 check box로 출력해서 true, false를 받도록 변경

**Comment by woongbin** [comment]
boolean dynamic field가 입력이 필수가 아닐 때 true인 값을 false로
변경하지 못하는 issue가 있습니다.
추후 패치에 수정하도록 하겠습니다.

**Comment by jhyeon1010** [comment]
default 값을 처리하는 문제로 view 에서 radio 로 표현되도록 변경되었습니다.
