### ISSUE TITLE
xe3 alice 테마 플러그인 슬라이드 이미지 변경 버그 

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#91]
https://www.youtube.com/watch?v=c3h6lxeuNA4&feature=youtu.be

이미지는 서버에 저장되었지만 페이지 에러로 적용이 안 됩니다.

**Comment by khongchi** [comment]
https://github.com/xpressengine/plugin-alice/issues/5에서 처리하겠습니다.
