### ISSUE TITLE
OS 에 따른 사례 기록

### ISSUE THREAD

**Issue by lispro06** [xpressengine/xpressengine#916]
rc5, 6를 설치해봤으나, centos-7.3 에서는 원인을 알 수 없이 링크 오류 등이 발생
해당 환경에서는 안되는 것으로 판단되며, ubuntu 18.04 환경에서는 설치 후 문제 없이 동작함.
아래 사양에서 이슈가 되는 사양에 대한 내용이 있으면 이슈 유지

[fail]
centos-7.3
WebServer : nginx/1.15.5
PHP Version : 7.1.24
Debug Mode : No
Cache Driver : file
Document Root : /var/www/html
Maintenance : Off
TimeZone : Asia/Seoul

[Success]
WebServer : Apache
PHP Version : 7.2.10-0ubuntu0.18.04.1
Debug Mode : No
Cache Driver : file
Document Root : /var/www/html
Maintenance : Off
TimeZone : Asia/Seoul

**Comment by akasima** [comment]
centos-7.3 서버 설치를 어디에 한건가요? 가상머신인가요?

**Comment by lispro06** [comment]
naver cloud platform 에 야심차게 설치했는데 안되네요.

**Comment by jdssem** [comment]
@lispro06 혹시 selinux가 활성화 되어 있거나 설정이 제대로 안 된게 아닐까요?

**Comment by lispro06** [comment]
Um. no. I'll install PHP 7.2.x. later.

# sestatus
SELinux status:                 disabled

# vi /etc/sysconfig/selinux

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

"/etc/sysconfig/selinux" 14L, 545C

**Comment by inasis** [comment]
Centos에서도 동일하게 Apache에서 돌려볼 수 있나요?

**Comment by kimyu711** [comment]
@lispro06 https://github.com/xpressengine/xpressengine/blob/master/example.xe3-nginx-rewrite.conf nginx rewrite 관련 설정샘플파일이 있습니다. 사이트 설정파일 (일반적으로 /etc/nginx/conf.d 안에 위치되어 있을 확률이 높습니다.)에서 해당 샘플처럼 rewrite설정을 맞추시면 작동할 것으로 예상합니다.

**Comment by lispro06** [comment]
안녕하세요.

알려주신 경로의 rewrite rule을 nginx.conf 에 적용하여 정상 작동 확인하였습니다.

설치 매뉴얼에 해당 내용 추가해 주시면 될 것 같네요.

감사합니다.

    rewrite ^/?$ /index.php redirect;
    location ^~ /assets/ {
        try_files $uri /index.php?$args;
    }
    location ^~ /plugins/ {
        try_files $uri /index.php?$args;
    }
    location ^~ /storage/app/public/ {
        try_files $uri /index.php?$args;
    }
    location ~ ^/favicon* {
        try_files $uri /index.php?$args;
    }
    location /robots.txt {
        try_files $uri /index.php?$args;
    }

    rewrite ^.* /index.php;

    location ~ ^/?index.php$ {
        fastcgi_pass unix:/var/run/php72-fpm/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
