### ISSUE TITLE
address 타입 확장필드 추가 시 게시판 접근 불가  문제

### ISSUE THREAD

**Issue by pwnbit** [xpressengine/xpressengine#919]
category 타입 확장 필드가 목록에서 출력되지 않는 문제로 이슈를 작성하려다가
몇 일 전 등록된 이슈가 있는 것을 보고 다른 확장 필드들을 테스트 하다보니 
주소 타입의 확장필드 추가 시 게시판 자체에 접근이 불가능한 문제가 확인되었습니다.

![image](https://user-images.githubusercontent.com/20031110/48743854-4456cc00-eca8-11e8-8fee-37c60548220d.png)

이런 문제가 발생되고 있구요.
제 서버와 체험하기 기능에서도 모두 에러가 발생됩니다.

================
추가로 category 타입 확장 필드를 추가하면서 ID 를 category로 하는 경우
별 다른 에러 메시지 없이 추가가 가능하고, 게시판에 분류 기능을 설정하면
분류 기능에 나와야 하는 값 대신 확장 필드(id:category)의 값이 나옵니다.
게시판의 분류 기능과 category type 확장 필드의 중복되는게 문제가 아닐까 싶습니다.

![image](https://user-images.githubusercontent.com/20031110/48744104-36ee1180-eca9-11e8-82e3-c993bdab6944.png)

**Comment by woongbin** [comment]
안녕하세요.

게시판에 주소 확장 필드를 추가 했을 때 에러가 발생한다고 하셨던 부분을 확인하려고 하는데 제가 테스트 했을 때는 말씀해주셨던 것과 같은 현상이 발생하지 않았습니다. 게시판에 주소 타입의 확장 필드를 추가하고 게시물 목록 페이지에 주소 타입 확장필드 출력 설정을 했는데 혹시 다른 작업이 더 필요한가요?

게시판 카테고리 타입 id 중복에 대한 문의는 xpressengine/plugin-board#220 issue에서 처리하도록 하겠습니다.

감사합니다.
