### ISSUE TITLE
plugins/ckeditor_plugin/assets/plugins/append.js 파일 누락

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#92]
ckeditor_plugin 은 ckeditor로 통합되지 않았나요?

dev 3.0 플러그인에는 ckeditor_plugin 폴더가 더이상 존재하지 않습니다.

append.js 파일이 꼭 필요한 것인가요?

#90 에 대해 다시 확인 해 주시기 바랍니다.

**Comment by akasima** [comment]
ckeditor_plugin 플러그인은 통합되었습니다. append.js 파일은 꼭 필요합니다. 

@1Sam 님 테스트중인 사이트에서 append.js 가 잘못 로드되고 있는걸 확인해보려고 했는데.. 확인 못했습니다.
어느 페이지에서 에러가 발생하는지 알려주시면 확인해 볼께요.

**Comment by 1Sam** [comment]
https://www.youtube.com/watch?v=jWZzXIyMYvE&feature=youtu.be

게시판의 글을 열람할 때 콘솔창에 표시됩니다. 특별한 다른 에러는 발생하지 않습니다. @akasima

**Comment by akasima** [comment]
comment 플러그인에서 불러오는 문제 였네요 

Comment plugin 을 수정해서 커밋했습니다. [commit](https://github.com/xpressengine/plugin-comment/commit/76c9eb7fb785e84adef1e9d2052bae7611ff9ac2)
