### ISSUE TITLE
어드민 설정의 관리페이지 권한 설정 에러 

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#94]
어드민 설정의 관리페이지 권한 설정을 실행하면 에러 메시지가 표시됩니다.

http://xe3.1sam.kr/settings/setting/permissions

https://www.youtube.com/watch?v=s_4HbPostss&feature=youtu.be

''
FatalErrorException in /home/kmdb/public_html/xe3/resources/UIObjects/Settings/SettingsPermission.php line 24:
Call to undefined method Xpressengine\Permission\PermissionHandler::make()
''

xe3\resources\UIObjects\Settings\SettingsPermission.php

위 파일의 아래 코드를 보면

24라인의 $permissionFactory->make($type, $target); 에서 오류가 있는 것 같습니다.

>     public function render()
>     {
>         $htmlString = [];
>         $args = $this->arguments;
> 
>         $title = $args['title'];
>         $type = $args['type'];
>         $target = $args['target'];
> 
>         /* @var Factory $permissionFactory */
>         $permissionFactory = app('xe.permission');
>         $permission = $permissionFactory->make($type, $target);
>         $actions = $permission->getActions();
>         $registered = $permission->getRegistered();
> 
>         $groups = app('xe.user.groups')->all();

xe3\core\src\Xpressengine\Permission\PermissionHandler.php

위 파일에는 make 메소드가 정의되지 않았습니다. 확인 바랍니다.

**Comment by khongchi** [comment]
개선된 코드가 dev4에 적용되었습니다.
