### ISSUE TITLE
로그인 오류

### ISSUE THREAD

**Issue by giverny** [xpressengine/xpressengine#941]
XE3 로그인시 오류가 있습니다.
항상 그런 것은 아닙니다. 
경로 문제 같은데 이미지 첨부합니다

![symfony](https://user-images.githubusercontent.com/13218664/52186625-e92a8380-286b-11e9-909f-d5db0b96d871.jpg)

**Comment by akasima** [comment]
로그인 후 이전 페이지로 이동하는데,
이전 페이지가 글쓰기 같은 post 로 전송할 페이지여서 나오는 문제가 아닐까 생각됩니다.

이 오류가 발생 했더라도, 로그인은 정상적으로 됐을 것 같은데요. (아닐 수 있구요.)
