### ISSUE TITLE
XE3 DEMO에서 게시판 확장 필드 주소 타입 에러

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#943]
Address타입의 확장 필드를 게시판에 추가하는 경우, 글쓰기는 가능하지만, 정상적으로 주소를 입력할 수 없는 문제가 있습니다.

**Comment by woongbin** [comment]
https://github.com/xpressengine/xpressengine/issues/935
위 이슈에서 처리된 내역입니다.
