### ISSUE TITLE
php artisan 위젯 생성

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#946]
테마를 제작하며 한번에 위젯과 게시판 스킨을 제작하려 하고 있으나, php artisan make:widget 이 되지 않습니다.

Widget을 추가해야할 것 같습니다.

**Comment by kimyu711** [comment]
네 맞습니다. 추후 추가하겠습니다.
현재 제공되고 있는 artisan 명령어는 php artisan list를 통해서 확인할 수 있습니다. 
현재 제공되고 있는 XE 컴포넌트 생성 관련 명령어는
플러그인(make:plugin), 
스킨(make:skin), 
테마(make:theme),
다이나믹필드(make:field), 
다이나믹필드 스킨
(make:fieldSkin) 이상 다섯가지 입니다.

**Comment by Kazto-lsk** [comment]
추가적으로는.. lost_temple 이라는 테마를 제작하다가, 이 테마에 번들형태로 포함된 Main_widget을 만들어서, 새로운 게시글을 보여주는 위젯을 만들려고 하면
```ssh
php artisan make:skin lost_temple Main_widget widget/skin
````

이 맞는건가요?
아니면, 다른 방법이 있을까요?

**Comment by kimyu711** [comment]
네, 스킨을 생성하는 문법은
php artisan make:skin 이후에
해당 스킨이 위치할 플러그인,(디렉토리명)
스킨이 사용할 이름(skinId)
해당 스킨을 적용할 대상 컴포넌트(targetId)
를 차례로 입력하면 됩니다.

**Comment by kimyu711** [comment]
기능을 구현해야하는 각 컴포넌트들은 개발자의 재량으로 가독성에 맞게 디렉토리와 클래스 구성이 가능합니다. 알맞은 해당 추상클래스를 구현하고 해당 플러그인을 composer.json에 등록해주면 되기 때문에 스킨과 테마 제작을 제외한 나머지 컴포넌트 생성 커맨드에 대한 룰셋 규정은 무의미하다고 판단되었습니다.
