### ISSUE TITLE
Storage에 쌓인 파일을 정리(삭제)할 수 있게 해주세요.

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#955]
![screenshot-simplesoft io-2019 03 15-11-26-51](https://user-images.githubusercontent.com/1732040/54403964-417b5d80-4715-11e9-8cc4-51cbd268d82e.png)

**Comment by akasima** [comment]
삭제는.. 사용하지 않는 파일을 정리하는 형태 겠죠?
어떤 방식으로 정리할 수 있을까요?

**Comment by smaker** [comment]
급하게 이슈를 작성하느라 스샷만 올려놨는데요.

XE1에는 파일 모듈이 있어서 사용하지 않는 파일을 관리자 페이지에서 삭제할 수 있었는데요.
XE3에서는 garbage file이 누적되면 정리하기가 쉽지 않네요. XE1 처럼 파일을 관리할 수 있으면 좋겠습니다.

**Comment by jhyeon1010** [comment]
core 에서 `php artisan storage:optimize` 명령어를 제공하고 있습니다.
위 명령어는 파일과 파일이 사용된 대상간에 relation 을 통해 파일이 사용되중임을 판단하고,
사용중이 아닌 파일을 일괄삭제 처리하도록 되어있습니다.
