### ISSUE TITLE
관리자 사이트에서 코어 업데이트를 할 수 없습니다.

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#956]
업데이트를 실행하려고 업데이트 페이지로 이동하였으나 업데이트 할 수 없었습니다.

**Comment by jhyeon1010** [comment]
업데이트 관련하여 몇몇 문제들을 파악하고 개선하여 배포되었습니다. 기존 방식으로 최신버전으로 업데이트를 하신 후 이후에도 같은 문제가 발생하시는 경우 이슈 남겨주세요
