### ISSUE TITLE
플러그인 설치시 언어 통일

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#957]
<img width="158" alt="스크린샷 2019-03-22 오후 2 58 45" src="https://user-images.githubusercontent.com/47233861/54803494-1499ee00-4cb3-11e9-96e5-6dcf495b1bda.png">
설치하기 멘트로 변경 되었으면 좋겠습니다.

**Comment by woongbin** [comment]
Develop 브랜치에서 다국어 import를 하지 않아서 발생한 문제로 생각됩니다.
php artisan translation:import 명령을 수행하고도 계속 같은 문제가 발생한다면
해당 문제가 발생하는 경로가 보이도록 다시 알려주시면 확인해보도록 하겠습니다.
