### ISSUE TITLE
코어 업데이트 이후 lang읽을 수 없음

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#958]
언어를 수동으로 추가 한 후 코어를 업데이트 하면 정상적으로 사이트 맵이 노출되지 않습니다(관리자 사이트에서).

관련해서 원래 파일로 원복 하였으나.. 동일한 증상이 계속 지속되어, 정상적인 사이트 운영이 불가능합니다.

**Comment by jhyeon1010** [comment]
언어파일은 파일->디비->파일(캐시) 과정을 거쳐 저장, 사용됩니다. 이미 등록된 키워드에 대한 업데이트는 사용자 지정문제로 처리하지 않습니다. 
기존 등록된 키워드까지 모두 업데이트 하려고 하는 경우 `-f` 옵션을 추가하여 명령을 실행하시기 바랍니다. `php artisan translation:import -f`
결과가 정상적으로 반영되지 않았다면 캐시를 삭제해보시기 바랍니다.
