### ISSUE TITLE
코어 기본 테마 설정 변경시 미반영

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#959]
별도로 만든 pc 테마 플러그인과 번들 테마인 Alice를 각각 pc와 모바일로 설정 후 페이지를 새로고침 하여도, 모바일에서는 앨리스로 변경되지 않습니다.

**Comment by akasima** [comment]
첨부 이미지 처럼 pc, mobile 다른게 설정할 때 정상 동작되는 걸 확인했습니다.
메뉴 구성 할 때 `상위 테마와 동일하게 지정합니다.` 옵션 체크로 인한 착오가 아닐지 확인 바랍니다.

![스크린샷 2021-07-22 오후 1 34 05](https://user-images.githubusercontent.com/5836237/126590316-88da3b7f-e32f-4604-ab82-56e20f6e3b1b.png)
