### ISSUE TITLE
어드민페이지>회원>설정>기본설정>로그인시 CAPTCHA 사용 에러 

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#96]
#86 의 버그를 아래의 영상처럼 해결하고

https://www.youtube.com/watch?v=lOcz_6kRXJA&feature=youtu.be

로그인시 CAPTCHA 사용 에서 '사용'을 체크하고 save 하면 에러 페이지가 뜹니다.

**Comment by akasima** [comment]
캡차 설정하기 전에 구글에 API 등록해서 XE3/config/captcha.php 을 수정해야 하는데요.

설정 절차에 문제가 있네요;; 관리자에서 captcha 를 사용함으로 설정하면 아래에 api key 를 등록하는 설정을 하는게 좋아보이는데,.. @khongchi 와 논의를 해봐야겠습니다.

**Comment by khongchi** [comment]
captcha 기능이 회원에 종속된 설정이 아니고, 구글이 아닌 다른 제공자를 사용할수도 있으므로 captcha설정 UI를 제공하는게 불가능해보입니다.

captcha 설정이 되어있지 않다면, '로그인시 CAPTCHA 사용' 체크박스를 disabled하도록 변경하는게 좋겠습니다.

조금더 친절하려면 설정값을 보여주는 정도가 좋아보입니다.

**Comment by khongchi** [comment]
현상태 유지하는게 좋다고 판단됩니다. 차후 경험이 더 누적되고나서 이슈가 된다면 다시 한번 고려해보려고 합니다.
