### ISSUE TITLE
3.0.1 최신 버전 대시보드 파일 로드 버그

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#960]
<img width="922" alt="스크린샷 2019-03-27 오후 2 52 30" src="https://user-images.githubusercontent.com/47233861/55054246-82268f80-50a2-11e9-9cfb-51e81ce1a742.png">

새로이 코어를 업그레이드 한 이후, admin.css를 불필요 하게 불러옴과 동시에, 잘못된 경로에서 불러오고 있습니다.
수정후 배포가 필요할 것 같습니다.

**Comment by bnu** [comment]
plugins/news_client/src/NewsWidget.php

**Comment by bnu** [comment]
https://github.com/xpressengine/plugin-news_client/issues/4 이슈에서 처리 함
