### ISSUE TITLE
Blade 문법인 @component가 예상과 다르게 동작

### ISSUE THREAD

**Issue by bearjuny** [xpressengine/xpressengine#968]
스킨이나 테마를 만들때 @include는 view가 현재 플러그인의 뷰 기준으로 동작하는데,
@component 명령어를 쓰려고 하면, root/resources/views 기준으로 뷰를 찾습니다.
@section은 아직 테스트 해보지 못했습니다.

**Comment by kimyu711** [comment]
뷰를 사용할 때에 사용하고자 하는 플러그인의 디렉토리를 기준으로 작성하기 위해서는 [plugin_name::]와 같이 플리그인명과 ::를 사용하여 접두어를 붙여주시면 정확한 뷰 디렉토리를 찾습니다. prefix없이 자동으로 플러그인의 뷰기준으로 동작했다면 해당 뷰를 로드한 스킨에서 미리 path 속성을 통해 뷰 경로를 잡아두었을 것으로 보입니다.

**Comment by akasima** [comment]
`plugin_name::` 접두어 설정으로 해보시기 바랍니다.
각 플러그인은 등록 과정에서 해당 플러그인의 디렉토리를 참조할 수 있도록 view에 alias를 등록합니다.
