### ISSUE TITLE
플러그인 설치를 실패한 경우, 메시지에 오타가 있음

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#974]
You have been denied permission to **`acccess`** [/home/simplesoft/public_html/composer.lock] file. To install the plugin, you must have write permission to access this this file. [file: /home/simplesoft/public_html/app/Console/Commands/ComposerRunTrait.php, line: 68]

acccess 를 access 로 변경해야 합니다.

**Comment by woongbin** [comment]
수정 완료했습니다. 감사합니다.
