### ISSUE TITLE
최초 설치 시, utf8mb4 환경에서 인덱스가 생성되지 않음

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine#977]
![screenshot-simplesoft io-2019 05 08-11-13-16](https://user-images.githubusercontent.com/1732040/57344515-873b2c00-7182-11e9-9bd8-dbb2d73192d8.png)

위의 사진과 같이 에러가 나고 설치가 제대로 되지 않고 있습니다.
utf8로 charset을 다시 변경하면 설치가 됩니다.

https://github.com/xpressengine/xpressengine/commit/407e013180d89ae99ad7028dcb6510374bc3d8d2

**Comment by jhyeon1010** [comment]
이전 버전에서 이모지 사용을 위해 utf8mb4를 기본 charset 으로 변경했었습니다. 
그런데 문제 없이 설치되려면 최신 버전의 데이터베이스를 사용해야 하는데, 많은 분들의 환경이 그렇지 못하여 같은 문제를 겪는것으로 보입니다.
기존 처럼 utf8을 기본으로 변경하였고, utf8mb4 를 필요로 하는 사용자는 가이드를 통해 해결할 수 있도록 하겠습니다.
