### ISSUE TITLE
출력순서 변경시 깨짐

### ISSUE THREAD

**Issue by Kazto-lsk** [xpressengine/xpressengine#978]
<img width="823" alt="issue" src="https://user-images.githubusercontent.com/47233861/57347285-af2f8d00-718c-11e9-9c58-22c3eb7e7df6.PNG">

순서를 바꾸려는 아이템의 순서를 바꾸면 테이블이 깨지듯이 깨져버립니다.

**Comment by bnu** [comment]
UI 변경 예정으로 처리하지 않음
