### ISSUE TITLE
설치 에러 'The maximum column size is 767 bytes. '

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/xpressengine#982]
https://www.popit.kr/mysql-index-column-size-too-large-error/
위의 설명대로 제가 사용중인 홈페이지에 테스트했더니 똑같은 현상이 나타났습니다.

![image](https://user-images.githubusercontent.com/10809941/58287737-bd1c1980-7dec-11e9-8a2c-ad04e48f7503.png)

문장 끝에 ROW_FORMAT=DYNAMIC; 를 추가했더니 제대로 테이블이 생성됩니다.

아래의 내용은 웹페이지에서 xe 인스톨할 때 발생하는 에러입니다.

![image](https://user-images.githubusercontent.com/10809941/58287532-38c99680-7dec-11e9-89a1-59420d5f6958.png)

아래의 내용은 설치시에 생성된 테이블들입니다.
![image](https://user-images.githubusercontent.com/10809941/58287830-fb193d80-7dec-11e9-974d-e21dec2050f0.png)

(2/2) QueryExceptionSQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (SQL: alter table `xe_instance_route` add unique `instance_route_instance_id_unique`(`instance_id`))
--
in Connection.php line 664
at Connection->runQueryCallback('alter table `xe_instance_route` add unique `instance_route_instance_id_unique`(`instance_id`)', array(), object(Closure))in Connection.php line 624
at Connection->run('alter table `xe_instance_route` add unique `instance_route_instance_id_unique`(`instance_id`)', array(), object(Closure))in Connection.php line 459
at Connection->statement('alter table `xe_instance_route` add unique `instance_route_instance_id_unique`(`instance_id`)')in Blueprint.php line 86
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar))in Builder.php line 252
at Builder->build(object(Blueprint))in Builder.php line 165
at Builder->create('instance_route', object(Closure))in Facade.php line 221
at Facade::__callStatic('create', array('instance_route', object(Closure)))in RoutingMigration.php line 52
at RoutingMigration->install()in XeInstall.php line 808
at XeInstall->migrateCore()in XeInstall.php line 726
at XeInstall->installFramework()in XeInstall.php line 229
at XeInstall->process()in XeInstall.php line 159
at XeInstall->handle()
at call_user_func_array(array(object(XeInstall), 'handle'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(XeInstall), 'handle'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(XeInstall), 'handle'), array(), null)in Container.php line 549
at Container->call(array(object(XeInstall), 'handle'))in Command.php line 183
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 170
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 960
at Application->doRunCommand(object(XeInstall), object(ArrayInput), object(BufferedOutput))in Application.php line 255
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 148
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 88
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 177
at Application->call('xe:install', object(Collection), null)in Kernel.php line 249
at Kernel->call('xe:install', array('--config' => '/home2/kmdb/public_html/1sam0/storage/app/installConfig', '--no-interaction' => true))in Facade.php line 221
at Facade::__callStatic('call', array('xe:install', array('--config' => '/home2/kmdb/public_html/1sam0/storage/app/installConfig', '--no-interaction' => true)))in InstallController.php line 178
at InstallController->install(object(Request), object(CookieJar))
at call_user_func_array(array(object(InstallController), 'install'), array(object(Request), object(CookieJar)))in Controller.php line 54
at Controller->callAction('install', array(object(Request), object(CookieJar)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(InstallController), 'install')in Route.php line 212
at Route->runController()in Route.php line 169
at Route->run()in Router.php line 658
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 68
at VerifyCsrfToken->handle(object(Request), object(Closure))in ExceptAppendableVerifyCsrfToken.php line 49
at ExceptAppendableVerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 660
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 635
at Router->runRoute(object(Request), object(Route))in Router.php line 601
at Router->dispatchToRoute(object(Request))in Router.php line 590
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 57

**Comment by jhyeon1010** [comment]
#977 과 같은 문제입니다. 새로 배포될 버전에서는 기존처럼 utf8 을 기본으로 하도록 수정되어질 것입니다.
