### ISSUE TITLE
XE3 설치 오류

### ISSUE THREAD

**Issue by calvinsnax** [xpressengine/xpressengine#984]
Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `xe_config` add primary key `config_site_key_name_primary`(`site_key`, `name`))

시스템 검사 내용도 다 정상으로 나오는데 마지막 설치 과정에서 이런 오류가 표시되네요.
이전에는 호스팅에서 사용 가능했는데 지금은 필요한 권한이 더 있는건가요?

phpmysql로 환경설정값 확인해보니 key buffer size는 256 MB로 나옵니다.

![34344](https://user-images.githubusercontent.com/30161600/58381660-9af7e680-7ffa-11e9-8fef-a44adc046410.png)

- 추가
innodb index key 제약 사항에 걸리면 저렇게 된다고 합니다.
db 설정에서 innodb large prefix를 켜면 된다고 하는데 일반적인 호스팅 환경에서는 db 환경설정을 함부로 바꿀 수가 없기 때문에 설치 자체가 안됩니다.

**Comment by jdssem** [comment]
아마도 아래 링크와 관련된 이슈가 아닐까 싶네요.
https://laravel-news.com/laravel-5-4-key-too-long-error

Laravel 5.4부터 utf8mb4를 기본으로 사용하는데 MySQL v5.7.7 미만이거나 MariaDB를 사용하면 발생하는 문제 같습니다. 해결책은 AppServiceProvider.php에

```
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```
를 추가하면 되긴하는데 #351 이슈와 관련이 있어 보이네요.

**Comment by calvinsnax** [comment]
음 왜인진 모르겠지만 해당 구문을 추가해도 계속 되네요. 범용적인 환경이 고려되지 않은 것 같아 아쉽습니다ㅠㅠ

**Comment by jdssem** [comment]
음 잘 안 되셨다니 아쉽네요. @calvinsnax 님 레이아웃과 스킨 매우 잘 쓰고 있는데요😂

아래 링크를 참고하셔서 homestead를 로컬에 설치하고 가상 머신에서 xe3를 설치하는 방법도 있기는 합니다. 맥을 사용하신다면 valet을 설치해서 로컬에서도 테스트 해볼 수 있기는 하고요.

https://laravel.kr/docs/5.8/homestead
https://laravel.kr/docs/5.8/valet

개발팀에서 보다 정확한 답변을 해주실 것 같습니다.

**Comment by kimyu711** [comment]
XE3도 3.0.1부터 utf8mb4를 기본으로 사용하면서 발생하는 이슈입니다. https://www.xpressengine.io/blog/XE-301-%EB%B0%B0%ED%8F%AC-%EC%95%88%EB%82%B4 해당 게시물 참고하셔서 사용하시는 db환경에 맞게 대응해주시면 될 것 같습니다.

**Comment by Lastorder-DC** [comment]
#977 기본 charset이 utf8로 바뀐 것으로 보이는데요, develop 브랜치에 적용되어 있으니 그걸 이용하시거나 3.0.2 릴리즈후 설치하시면 될것 같습니다.
