### ISSUE TITLE
플러그인 최근 작업 내역 삭제 오류

### ISSUE THREAD

**Issue by calvinsnax** [xpressengine/xpressengine#985]
![image](https://user-images.githubusercontent.com/30161600/58392041-1eedb500-8073-11e9-9287-df61f8255988.png)

![image](https://user-images.githubusercontent.com/30161600/58392029-0d0c1200-8073-11e9-9b36-5cdb2903386c.png)

스크린샷처럼 내역 삭제를 클릭하면 삭제는 되지 않고 403 오류가 출력됩니다.

또한 스토어 플러그인 추가 기능으로 추가한 xero_commerce 플러그인의 활성화 / 삭제가 안됩니다.

**Comment by jhyeon1010** [comment]
3.0.2 에서 플러그인 작업내역에 대한 부분이 변경되었습니다. 내역 삭제 기능은 제거되었습니다.
xero_commerce 플러그인은 테스트 해보았으나 문제점이 발견되지 않았습니다. log 등 정보가 더 필요할 것 같습니다.
