### ISSUE TITLE
임시저장된 게시글이 삭제되지 않는 문제

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine#992]
`draft/destroy/d205ec55-9feb-48fa-b33f-7ae4ab610170` 형태로
`DraftController@destroy` 를 호출해도 삭제가 되지 않습니다. 확인 부탁드립니다.

**Comment by woongbin** [comment]
수정된 내용은 다음 XE3 배포에 적용될 예정입니다.
감사합니다.
